aiven/terraform-provider-aiven

- resource_service_user.go
@jelmersnoeck This removes the no-op service user update. In the 0.11 series of terraform having this present gives the following error on run:
```
Error: provider.aiven: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:
1 error occurred:
* resource aiven_service_user: All fields are ForceNew or Computed w/out Optional, Update is superfluous
```
> Removes service user update

- Gopkg.lock
- Gopkg.toml
- resource_service.go
@jelmersnoeck integrates support for user config into the Aiven provider. Before merging this I'll have to either update the dep to point to master of the aiven repo, or we'll need to cut a `0.1.0` or `0.0.3` in the Aiven repo.
One other note -- I had to add some type transformations on the user config because [Terraform converts bools to strings](https://www.terraform.io/docs/configuration/variables.html#booleans). The Aiven API uses JSON Schema or something similar to type check values, and was thus rejecting the API requests without the type munging you see here.
Its also worth noting that Aiven doesn't document whats in the `user_config` for each service. We're reaching out to them to see if we can get a list of whats officially documented without having to reverse-engineer the API w/ …
> Add support for User Config and Kafka User Config checking.

- .gitignore
- resource_service.go
- service_change.go
@jelmersnoeck @FranOis 
When Aiven creates a Kafka service with Kafka Connect, and/or, Kafka Rest, and/or schema registry enabled, Aiven will report that Kafka is ready potentially before any of those peripheral services are actually ready. This PR ensures that when a resource is a Kafka service the resource shouldn't be considered ready until all the peripheral services are healthy; if a service is reachable, it is considered ready. This is a feature @benjigoldberg and I need so that resources that are dependent on Kafka Connect being ready don't fail immediately after Terraform creates the Kafka service in Aiven.
> Wait for Kafka auxillary services to start up

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- LICENSE
- Makefile
- README.md
- generate_templates.sh
- kafka_topic_change.go
- main.go
- provider.go
- resource_connection_pool.go
- resource_database.go
- resource_kafka_acl.go
- resource_kafka_topic.go
- resource_project.go
- resource_project_user.go
- resource_project_vpc.go
- resource_service.go
- resource_service_integration.go
- resource_service_integration_endpoint.go
- resource_service_user.go
- resource_vpc_peering_connection.go
- sample.tf
- service_change.go
- templates/integration_endpoints_user_config_schema.json
- templates/integrations_user_config_schema.json
- templates/service_user_config_schema.json
- terraform.tfvars.sample
- user_config.go
Note: This change is not backwards compatible. Things like identifier format and names of some parameters have changed and existing Terraform scripts do not work with this version. For most part the changes are fairly straightforward and discarding existing `terraform.tfstate` and importing the resources after minor changes to .tf files should work.
> Support all Aiven resources

- sample.tf
VPCs are quota restricted and the VPC didn't do anything useful so drop
it to avoid unused VPCs consuming quota.
> Remove VPC creation from sample script

- Gopkg.lock
- Gopkg.toml
- README.md
- resource_service.go
Termination protection can be useful for preventing accidental deletion
of production services. Because it only prevents deletion of the service
itself and not any sub resources one must still be extremely careful
with the diffs when applying changes but at least it will ensure that
backups are not lost for services that do keep backups.
> Add support for service termination protection

- resource_service.go
- resource_service_integration.go
- resource_service_integration_endpoint.go
- user_config.go
Files must not be referenced from global context because the init
function that makes embedded files available has not yet been run.
> Delay referencing packr managed resources

- Gopkg.lock
- Gopkg.toml
- user_config.go
MustBytes has been marked as deprecated and will be removed in
version 2. Find works in both.
> Use Box.Find instead of Box.MustBytes

- kafka_topic_create.go
- resource_kafka_topic.go
Server may return 409 in case there aren't currently enough brokers to
complete the request. Wait until timeout before failing operation if
that happens.
> Don't fail Kafka topic creation immediately on 409

- resource_service.go
Fix two bugs that caused service_port property to be never available and service type specific connectivity info for new services to usually not be available until Terraform state is refreshed.
> Make service connectivity info properly available

- resource_database.go
Fixes #76
resourceDatabaseRead() did not fill the project and service_name
resulting in partial import that then later trigger recreation
of the database.
Previously imported database resources having this issue will have
to be removed from the state and reimported.
> fix aiven_database resource importing

- resource_project_vpc.go
- resource_service.go
State will always automatically change from APPROVED to ACTIVE (unless
there's some error in configuration) so instead of handling waiting in
places where the VPC is used, just always wait during creation. Fixes
case where new VPC is created and existing service moved to that VPC
during the same apply and also some other issues.
Also increased timeout from 2 two 4 minutes since in some cases the
cloud provider APIs can be slow enough for 2 minutes to be enough.
Fixes https://github.com/aiven/terraform-provider-aiven/issues/54
> Wait for VPC to become active before completing creation

- aiven/kafka_topic_change.go
- aiven/resource_kafka_acl.go
- go.mod
- pkg/cache/kafka_acl_cache.go
- pkg/cache/kafka_topic_cache.go
Cc @mteiste 
Apologies it took me so long to get this PR in..
For anyone checking this, the TL;DR is that we have a large number (thousands) of resources in Aiven that we've Terraformed in a single GitHub repo. Running `tf plan` and `tf apply` commands are taking an extremely long time for Topics and ACLs due to an API call being made for each.
This change introduces an ACL and a Topic cache, which are populated using a single List API call for each. It's cut our tf plan/applies down to sub-2mins, and I hope it could reduce the impact on your API too?
We also added a sleep into each resource, as without them we were seeing most plan/applies failing with a gRPC error: `Error: rpc error: code = Canceled desc = context canceled`. Unfortunately we don't have much gRPC expertise currently, so …
> Add topic and acl caching

- aiven/templates/service_user_config_schema.json
This addresses #104 (Timescale Cloud Support).
Allows variant of type "timescale" or "aiven" in the `aiven_service` resource.
> added variant to the schema definition to enable timescale support

- pkg/cache/kafka_acl_cache.go
- pkg/cache/kafka_topic_cache.go
this code was causing a nil pointer dereference when `liveACL` was nil:
```
liveACL, err = client.KafkaACLs.Get(project, service, aclID)
acl = *liveACL
```
..so I added a nil check.
I also changed the topic cache to return the error that `client.KafkaTopics.Get()` returns instead of creating its own (this also has a nil check).
> Fix caching nil pointer dereference

- README.md
Haven't found a way to enforce the terraform version constraints in the code, added them to Readme file. Tested on Terraform v0.10.1 and the newest version all works fine, does not make a lot of sense to go to versions before v0.10.X since almost all terraform providers do not support them.
> add requirements block

- aiven/resource_service.go
- aiven/user_config.go
For all the boolean configuration options without a default value use type string instead of boolean for internal representation. We will be using string instead of boolean to track whether a user is setting any values for such configuration options or not since Terraform boolean type cannot provide such indication. 
This solution is based on the fact that Terraform seamlessly for a user converts any simple type value to a string, for example:
`action_destructive_requires_name = true` if resource filed `action_destructive_requires_name` has a type `string` true value will be converted to `"true"` string value.
> fix <service>_user_config Boolean fields without default value

- Makefile
- aiven/aiven_sweeper_test.go
- aiven/provider_test.go
- aiven/resource_project_test.go
use `make testacc` to run the acceptance tests
`AIVEN_TOKEN` environment variable is required and should contain a valid Aiven API token
> test-acc: project

- Makefile
Disable golangci-lint `unused` checks. 
**Motivation:**
Aiven in-house Jenkins build job fails from time to time with the following error:
```
golangci-lint run  -D errcheck --no-config --issues-exit-code=0 ./...
level=warning msg="[runner] Can't run linter goanalysis_metalinter: fact_deprecated: failed prerequisites: fact_deprecated@github.com/hashicorp/go-plugin"
level=error msg="Running error: fact_deprecated: failed prerequisites: fact_deprecated@github.com/hashicorp/go-plugin"
```
It looks like it is somehow related to these issues:
- https://github.com/golangci/golangci-lint/issues/885
- https://github.com/golangci/golangci-lint/issues/827
And the remedy for this problem could be to temporary disable `unused` checks.
> golangci-lint disable unused checks

- aiven/resource_project_user.go
- aiven/resource_project_user_test.go
Solition for the following problem:
The `aiven_project_user` resource destroy operation wasn't working correctly, during `terraform destroy` en error is occurring: ```403: {"errors":[{"message":"User does not exist","status":403}],"message":"User does not exist"} ```
> fix aiven_project_user resource destroy operation

- aiven/datasource_service.go
- aiven/resource_service.go
- aiven/user_config.go
When a user tries to import `aiven_service` data source `<service_type>_user_config` is not populated due to the error which was omitted in the code, this PR will fix this problem. 
Also related to this issue: https://github.com/aiven/terraform-provider-aiven/issues/87
> fix service datasource user config

- Makefile
add a possibility to run a specific test using `make testacc` for example:
```
make testacc TESTARGS='-run=<TEST_NAME>'
```
> testacc: add possibility to run specific tests using arguments

- aiven/resource_project_user_test.go
- aiven/resource_service_cassandra_test.go
- aiven/resource_service_influxdb_test.go
- aiven/resource_service_kafka_connect_test.go
- aiven/resource_service_redis_test.go
Add service type-specific tests
Covers Cassandra, InfluxDB, Kafka Connect and Redis
> testacc: Add service type specific tests

- aiven/resource_service_test.go
Kafka service has no service username and password properties in API response unlike all other Aiven services
> testacc: disable kafka service specific checks

- aiven/resource_account_test.go
`billing_enabled` property was deleted from TF resource but not from the account acceptance tests.
> testacc: fix account tests

- aiven/resource_service_mysql_test.go
Configuration option sql_require_primary_key is set to true by Aiven API during MySQL service creation
> testacc: fix MySQL service tests

- README.md
- aiven/resource_database.go
- aiven/resource_database_test.go
- aiven/resource_kafka_topic.go
- aiven/resource_kafka_topic_test.go
- aiven/resource_service_test.go
Spent a lot of time searching for a way to test `termination_protection` accurately, but TF testing framework does not provide a way to interrupt or replace delete plan cycle. Therefore only test plan for use case when `termination_protection` is enabled.
> testacc and termination protection

- aiven/kafka_topic_availability.go
- aiven/resource_kafka_topic.go
- pkg/cache/kafka_topic_cache.go
- Will solve a situation when a user has an old TF state file created before Kafka `topic` field was renamed to `topic_name`.
- Extra debug and trace logging for Kafka Topic cache and waiter layers
> Kafka topic old TF state backwards compatibility

- aiven/kafka_topic_availability.go
- go.mod
- pkg/cache/kafka_topic_cache.go
- pkg/cache/kafka_topic_cache_test.go
Improve Kafka Topic availability performance:
- remove waiter delay which sets TF timeout before start checking availability
- avoid multiple calls to Aiven API to refresh Topic Cache, since TF calls multiple waiters at the same time solution would be to make the first waiter refresh cache and put all others in the waiting position.
https://github.com/aiven/terraform-provider-aiven/issues/212
> speed up kafka topic availability waiter

- aiven/datasource_kafka_acl.go
- aiven/resource_kafka_acl_test.go
It is possible to create multiple Kafka ACL's for the same topic/username in a project for multiple roles, added permission as a required field.
> fix kafka acl datasource

- .gitignore
- CHANGELOG.md
- Makefile
- README.md
- _config.yml
- aiven/resource_project.go
- docs/data-sources/index.md
- docs/guides/getting-started.md
- docs/guides/index.md
- docs/index.md
- docs/resources/index.md
- scripts/docgen.py
- scripts/schema.json
- scripts/template_all.md
- scripts/template_ds.md
- scripts/template_re.md
Generating schema for provider from `terraform providers schema -json` (not in build task)
Add `docs` directory following format outlined in: https://www.terraform.io/docs/registry/providers/docs.html
- docs/
- datasources/
- resources/
- guides/
Add scripts directory to generate documentation for `index.md` based on
schema. Others will need to be written manually.
Github Pages config added and using `Just the Docs` theme with search enabled.
Once merged, Github Pages needs to be enabled for `master docs/ folder`
Structure exists but docs are **WIP**
> Github Pages support and static docs generation

- README.md
- aiven/provider.go
- aiven/provider_test.go
- aiven/resource_kafka_topic.go
- aiven/resource_kafka_topic_test.go
- aiven/resource_project_vpc.go
- aiven/resource_project_vpc_test.go
- aiven/resource_service.go
- aiven/resource_service_pg_test.go
- aiven/resource_vpc_peering_connection.go
- aiven/resource_vpc_peering_connection_test.go
`client_timeout `is marked as deprecated and instead, and users welcome to use native Terraform `timeouts` functionality
> add TF native timeouts support

- aiven/provider.go
- aiven/resource_kafka_topic_test.go
- aiven/resource_service_cassandra_test.go
- aiven/resource_service_elasticsearch_test.go
- aiven/resource_service_kafka_connect_test.go
- aiven/resource_service_kafka_test.go
- aiven/resource_service_mysql_test.go
- aiven/resource_service_pg_test.go
- aiven/resource_service_redis_test.go
- aiven/user_config.go
- aiven/user_config_test.go
- go.mod
- go.sum
User configuration options refactoring include two major updates: 
- All configuration options regardless of the original Aiven API type will have a string type in Terraform. When an option is not set in the plan, the default not-set value will be `""` an empty string (also interpreted as null in TF). This will allow us to get reed of ad-hock checks depending on the type like `"<<value not set>>"`, `-1`, etc. and will make TF plans look cleaner without having these default unset values in it. 
- Diff suppress function extended such that all configuration options (with or without default values) that do not have any value set in a TF plan will be excluded from the diff. It should fix this issue https://github.com/aiven/terraform-provider-aiven/issues/179/  
This PR was well tested and …
> user configuration options refactoring

- _config.yml
- aiven/resource_kafka_acl.go
- aiven/resource_kafka_acl_test.go
Default Kafka ACL is `*`. Alphanumeric check does not allow this to be removed before adding new ACLs. Regexp has been changed to allow either a single `*` or an alphanumeric string.
> Allow wildcard for username in Kafka ACL

- aiven/resource_kafka_acl.go
- aiven/resource_kafka_acl_test.go
Username ACL allows:
* Literal - "user1"
* Prefixed - "group-user-"
* Wildcard - "*"
Suffixed ("*-user-group") is not supported. Regex username check has been updated to
reflect this.
> Kafka ACL regex update to allow wildcard as suffix

- Makefile
- aiven/provider_test.go
- aiven/resource_connection_pool_test.go
- aiven/resource_database_test.go
- aiven/resource_elasticsearch_acl_test.go
- aiven/resource_kafka_acl_test.go
- aiven/resource_kafka_connector_test.go
- aiven/resource_kafka_schema_configuration_test.go
- aiven/resource_kafka_schema_test.go
- aiven/resource_kafka_topic_test.go
- aiven/resource_mirrormaker_replication_flow_test.go
- aiven/resource_project_test.go
- aiven/resource_project_user_test.go
- aiven/resource_service_cassandra_test.go
- aiven/resource_service_elasticsearch_test.go
- aiven/resource_service_grafana_test.go
- aiven/resource_service_influxdb_test.go
- aiven/resource_service_integration_endpoint_test.go
- aiven/resource_service_integration_test.go
- aiven/resource_service_kafka_connect_test.go
- aiven/resource_service_kafka_test.go
- aiven/resource_service_mirrormaker_test.go
- aiven/resource_service_mysql_test.go
- aiven/resource_service_pg_test.go
- aiven/resource_service_redis_test.go
- aiven/resource_service_test.go
- aiven/resource_service_user_test.go
Change acceptance tests to use one pre-existing project instead of creating a new project each time during execution, with exceptions for the projects that are not using services.
> make acc tests use one project

- aiven/resource_kafka_acl.go
- aiven/resource_kafka_acl_test.go
Add check that * is not first char of strings of length > 1
Some tests (KafkaACLWildcardPrefix) were reporting as being skipped so I will check if this is happening in CI as well.
> Kafka ACL regex modification

- docs/index.md
- examples/timescale/main.tf
- examples/timescale/variables.tf
Here's an example configuration showing how to deploy a TimescaleDB service in Timescale Cloud. The required `variant` option is slightly unexpected for users so I think it is worth including in an explicit example like this.
> Add example initial configuration for Timescale Cloud

- aiven/resource_kafka_topic.go
It only appears when topics are without config are automatically created using the for_each loop.
> fix kafka topic empty config issues

- aiven/kafka_topic_availability.go
- aiven/kafka_topic_create.go
- aiven/resource_kafka_topic.go
The idea of PR is to optimise Kafka Topic performance. Since we are using a new Kafka Topic API endpoint to get Kafka Topic configuration in addition to list endpoint, it drastically increases the number of API calls. Kafka Topic endpoint may behave unstable when a user has 200+ topics and Terraform client performing multiple operations simultaneously. 
To remedy this, we reduce the number of API calls where possible, tune timings and improve error handling to reduce the number of API calls.
> optimise kafka topic resource performance

- docs/resources/kafka_topic.md
`partitions` and `replication` are both required parameters but were marked Optional in docs. Fixing that.
> Fixed docs for mandatory kafka topic params which were marked optional

- aiven/resource_project_test.go
- aiven/resource_project_user_test.go
With this fix the `testAccProjectResourceAccounts` and `testAccProjectUserResource` are passing now. 
Please double check if it's the correct way.
> tests: fix some testacc

- aiven/datasource_project_test.go
- aiven/resource_project_test.go
When we run this test `TestAccAivenProjectDataSource_basic` we have the following failure:
`--- FAIL: TestAccAivenProjectDataSource_basic (3.33s)
datasource_project_test.go:14: Step 1/1 error: Check failed: Check 3/3 error: data.aiven_project.project: Attribute "card_id" is "", but "card_id" is not set in aiven_project.foo`
This fix the test but, I'm wondering if it's normal: the `card_id` is  `""`. Should this attribute (card_id) have some value?
> tests: add card_id to project resource

- aiven/datasource_transit_gateway_vpc_attachement.go
- aiven/datasource_vpc_peering_connection.go
- aiven/resource_transit_gateway_vpc_attachement.go
- aiven/resource_vpc_peering_connection.go
- We update the VPC peering connection code eliminating all TF SDK v2 deprecated function, updating them with the context. 
- Change creation function, such that only when VPC peering connection is in the `ACTIVE` state - TF resource is created. Also, the extended error messages aim to communicate a guide a user to achieve the `ACTIVE` state.
> Change VPC peering connection state handling

- aiven/datasource_project_vpc.go
This test `TestAccAivenProjectVPC_basic` fails with the following:
```
=== CONT  TestAccAivenProjectVPC_basic
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1062073]
goroutine 7076 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/diag.FromErr(...)
/srv/jenkins/workspace/terraform-provider-aiven-testacc/terraform-provider-aiven/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/diag/helpers.go:16
github.com/aiven/terraform-provider-aiven/aiven.datasourceProjectVPCRead(0x17ac380, 0xc000031e00, 0xc000c10d80, 0x130e4e0, 0xc000beac00, 0xc00104d950, 0x0, 0x0)
/srv/jenkins/workspace/terraform-provider-aiven-testacc/terraform-provider-aiven/aiven/datasource_project_vpc.go:33 +0x293 …
```
> project_vpc: fix project vpc error handling

- aiven/kafka_topic_availability.go
- aiven/resource_kafka_topic.go
- aiven/resource_kafka_topic_test.go
Some customers with 450+ topics per Kafka service report `error: error waiting for Aiven Kafka topic to be ACTIVE: couldn't find resource (21 retries)`, even after upgrading to `2.1.4`, after analyzing log files I found that many TF goroutines are waiting for the semaphore to unlock the refresh cache function, lots of messages like `Kafka Topic Availability cache refresh already in progress ...`.
Also, I can reproduce that on my box with 500 topics all present in the state file. Terraform is waiting for all of them to be created and accessible. Sometimes, it takes quite some time before TF waiters internal limit accedes. Also, we only allow one request to API at the time, which makes things drastically slower.
So I have added the following improvements:
- Let semaphore run 5 goroutines to …
> kafka topic availability improvements

- aiven/kafka_topic_availability.go
- aiven/kafka_topic_create.go
- aiven/resource_kafka_topic.go
- go.mod
- pkg/cache/kafka_topic_cache.go
- pkg/cache/kafka_topic_cache_test.go
We are using v2 Kafka Topic API endpoint as a default way of getting Kafka Topics, and if it is not available for a particular Kafka service, we do have a fallback of v1 Endpoint.
Also logic is a bit different, now the first TF goroutine from the batch will warm up the cache by adding topic names to cache queue by running v1 API endpoint get all Kafka topics for a service. All topic names from the cache queue will be bundled in batches up to 100 topics at the time, and v2 API endpoint will be queried until we get data for all topics in the cache.  
Please note that v1 fallback logic was not tested, since it is hard to find any old Kafka nodes that do not support  v2.
> kafka topic v2

- aiven/resource_database.go
Fixes wrong lc_ctype used during database creation and avoid destroying a database on next apply.
```
-/+ resource "aiven_database" "mydb" {
database_name          = "mydb"
~ id                     = "test/postgres/users" -> (known after apply)
lc_collate             = "C.UTF-8"
~ lc_ctype               = "en_US.UTF-8" -> "C.UTF-8" # forces replacement
project                = "test"
service_name           = "postgres"
termination_protection = false
}
Plan: 1 to add, 1 to change, 1 to destroy.
```
> fix: type in lc_ctype postgresql database parameter

- aiven/provider.go
Will prevent Kafka Topics without config populating config with zeros. 
In my tests, I haven't seen empty configs, not sure if this is even possible, but hypothetically this might fix this issue: https://github.com/aiven/terraform-provider-aiven/issues/438#issuecomment-778896199
> add empty string validation for OptionalStringToX conversion

- examples/gcp_marketplace/main.tf
- examples/gcp_marketplace/variables.tf
Need to test this out but it should demonstrate how to avoid the most common gotchas when using the Terraform provider with GCP Marketplace projects.
> Add example initial configuration for GCP Marketplace

- go.mod
- go.sum
The latest go-client contains an updated version of the Account Team Project update method.
> use latest go-client

- docs/resources/redis.md
Just fix a typo with the title referring to Prometheus instead of Redis.
> Fix documentation

- docs/resources/kafka_schema.md
- examples/kafka_schemas/external_schema.avsc
- examples/kafka_schemas/kafka_schema.tf
A customer was wondering how they could avoid having to inline their Avro schema in the Terraform file when using the `aiven_kafka_schema` resource. I think it's a good enough reason for us to demonstrate the use of the [Terraform file function](https://www.terraform.io/docs/language/functions/file.html) in these examples.
> add examples using external kafka schema file

- examples/gcp_marketplace/main.tf
The API does not allow underscores in project names, but
it supports dashes
> examples: modify GCP Marketplace project name

- aiven/resource_project.go
Project Name updates fail with the following error because the update attempts to use the "new" projectName instead of the original projectName:
```
Error: 404: {"errors":[{"message":"Project does not exist","status":404}],"message":"Project does not exist"} -
```
This change uses the projectName that is currently set in the state file prior to the name update.
> Use original Project Name which fixes Project name updates

- docs/resources/kafka_mirrormaker.md
- Add definition for `sync_group_offsets_enabled`.
- Rename 'refresh_groups_interval_seconds' to 'refresh_topics_enabled' (typo)
- Trim some trailing whitespace. Was automatically done by vscode, but thought that it wouldn't hurt to have this included in this commit.
> docs: some updates to MirrorMaker arguments list

- docs/resources/connection_pool.md
I noticed the docs were slightly out of sync with the API behaviour while using the Terraform provider.
> fix required and optional aiven_connection_pool options

- aiven/user_config.go
- aiven/user_config_test.go
It will prevent services from REBUILDING when updated to the new TF provider version, which has some new default values to be propagated.
> remove default values for user configuration options

- aiven/resource_kafka_topic.go
- aiven/resource_kafka_topic_test.go
Terraform Kafka topic resource's `delete_retention_ms` state was not tracked by the provider, this PR fixes that
> add delete_retention_ms to kafka topic read method

- aiven/resource_vpc_peering_connection.go
Had a confusing error message when trying to import a VPC peering in the terraform state
This is just a one line fix of this error message
> Small cleaning VPC peering log error

- go.mod
- go.sum
go.mod: update the dependency of github.com/aiven/aiven-go-client
addresses https://github.com/aiven/terraform-provider-aiven/issues/532
> update github.com/aiven/aiven-go-client to v1.5.13

- aiven/resource_service.go
- aiven/resource_service_integration.go
- aiven/resource_service_integration_test.go
- aiven/resource_service_pg_test.go
- go.mod
In some cases, service creation may trigger the creation of service integration. For example, PG read replica service integration does that. PG replica service is created with service integration user configuration options that trigger the creation of service integration. To handle such cases correctly, we update the creation logic for the service_integration resource; it should work correctly when a service integration already exists.
> change service integration behaviour

- aiven/provider.go
- aiven/resource_account.go
- aiven/resource_account_authentication.go
- aiven/resource_account_team.go
- aiven/resource_account_team_project.go
- aiven/resource_connection_pool.go
- aiven/resource_database.go
- aiven/resource_elasticsearch_acl.go
- aiven/resource_kafka_acl.go
- aiven/resource_kafka_schema.go
- aiven/resource_kafka_schema_configuration.go
- aiven/resource_kafka_topic.go
- aiven/resource_mirrormaker_replication_flow.go
- aiven/resource_project_vpc.go
- aiven/resource_service.go
- aiven/resource_service_integration.go
- aiven/resource_service_integration_endpoint.go
- aiven/resource_service_user.go
Before the SDK v2 upgrade ([here](https://github.com/aiven/terraform-provider-aiven/commit/0b0aa87) and [here](https://github.com/aiven/terraform-provider-aiven/commit/514649b)), those existence checking functions (`resourceXYZExists`) [were not returning errors](https://github.com/aiven/terraform-provider-aiven/blob/514649bad3e734e8b8d6a276528fbf6e0fb50bc5/aiven/provider.go#L261) in the case of non-existent resources (status `404`). [According to this upgrade guide](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#deprecation-of-helper-schema-existsfunc), these functions are deprecated, but their logic needs to be moved to Read functions (by `SetId("")` and returning no errors). 
This PR will revert those non-existent checks back to the Read functions. I tried to cover …
> Handle non-existent resource

- README.md
I could just update the version reference, but it would be obsolete soon.
Removing the version here would force people to check the latest version :)
> Remove old version reference

- aiven/datasource_service_component_test.go
- aiven/resource_aws_privatelink_test.go
- aiven/resource_connection_pool_test.go
- aiven/resource_database_test.go
- aiven/resource_elasticsearch_acl_test.go
- aiven/resource_elasticsearch_test.go
- aiven/resource_kafka_acl_test.go
- aiven/resource_kafka_connector_test.go
- aiven/resource_kafka_schema.go
- aiven/resource_kafka_schema_configuration_test.go
- aiven/resource_kafka_schema_test.go
- aiven/resource_kafka_test.go
- aiven/resource_kafka_topic_test.go
- aiven/resource_m3aggregator_test.go
- aiven/resource_m3db_test.go
- aiven/resource_mirrormaker_replication_flow_test.go
- aiven/resource_mysql_test.go
- aiven/resource_pg_test.go
- aiven/resource_service_elasticsearch_test.go
- aiven/resource_service_integration_endpoint_test.go
- aiven/resource_service_integration_test.go
- aiven/resource_service_kafka_test.go
- aiven/resource_service_mysql_test.go
- aiven/resource_service_pg_test.go
- aiven/resource_service_user_test.go
It is not a good idea to use a specific service version for acceptance testing since Aiven services always evolve, and certain versions get old and eventually reach EOL, which will break tests.
> remove specific version from acceptance tests

- CHANGELOG.md
- aiven/datasource_elasticsearch_acl.go
- aiven/datasource_elasticsearch_acl_config.go
- aiven/datasource_elasticsearch_acl_rule.go
- aiven/provider.go
- aiven/resource_elasticsearch_acl.go
- aiven/resource_elasticsearch_acl_common.go
- aiven/resource_elasticsearch_acl_config.go
- aiven/resource_elasticsearch_acl_config_test.go
- aiven/resource_elasticsearch_acl_rule.go
- aiven/resource_elasticsearch_acl_rule_test.go
- aiven/resource_elasticsearch_acl_test.go
- docs/resources/elasticsearch_acl.md
- docs/resources/elasticsearch_acl_config.md
- docs/resources/elasticsearch_acl_rule.md
- examples/elasticsearch/elasticsearch_acl.tf
This PR aims to split `elasticsearch_acl` into `elasticsearch_acl_config` to configure acls  and `elasticsearch_acl_set` to create the acl rules. This way we can add acls in different resources and attempt to make our terraform configuration more modularizable.
> RFC: split elasticsearch resource ACLs

- aiven/resource_elasticsearch.go
- aiven/resource_grafana_test.go
- aiven/resource_m3db_test.go
- aiven/resource_service.go
- aiven/resource_service_elasticsearch_test.go
- aiven/resource_service_grafana_test.go
- aiven/resource_service_pg_test.go
- aiven/service_change.go
- aiven/user_config.go
This PR changes how ES `index_patterns` array-based user configuration options behave; an empty array will result in an empty JSON array in a PUT API request.
> fix es indexes deletion

- docs/resources/opensearch.md
The `opensearch_dashboards_request_timeout` in the opensearch docs example is an invalid argument name and presumably should be `opensearch_request_timeout`
> Fix invalid argument name in opensearch example

- aiven/resource_connection_pool.go
- go.mod
- go.sum
The API allows pools to be created with no pool-specific username specified.
This switches the field on the aiven_connection_pool resource similarly
and allows to reuse the incoming user by not specifying a username,
which matches behavior of the UI.
Depends on changes top aiven-go-client via https://github.com/aiven/aiven-go-client/pull/134
> Convert connection pool username field to optional

- docs/resources/opensearch.md
Change privatelink_access directive `opensearch_dashboard` to `opensearch_dashboards`
> Fix typo in opensearch resource doc

- aiven/resource_opensearch.go
- aiven/resource_service.go
After upgrading an existing Elasticsearch service to Opensearch, we create a "hybrid" service, and this PR adds support of such services to the `aiven_opensearch` resource.
> add hybrid opensearch service support

- .semgrep.yml
- CHANGELOG.md
- aiven/resource_service_integration.go
- aiven/resource_service_integration_test.go
resource_service_integration: simplify handling of preexisting service integrations
currently it is allowed to import arbitary service integrations which is non canonical behaviour. preexisting resources should be imported as opt-in. This PR restricts the allowed preexisting integrations to be of `read_replica` type since that is the only type that can be created alongside a service by terraform itself.
> resource_service_integration: only allow read_replica as preexisting resource

- aiven/service_change.go
This PR adds a little more logging to the service waiter to help debug why some service time out without apparent reason.
> service_change.go: add more logging to service waiter

- .github/workflows/acceptance-tests.yml
This PR enables long acc test for kafka topics in nightly runs where we do not care about the time too much.
> actions: enable long acc tests in nightly test runs

- aiven/resource_account_authentication.go
The auth provider was returning the SAMLCertificate for the saml_idp_url
and saml_entity_id attributes, which prevents use of this resource in
the provider.
> saml auth provider: lookup URLs correctly

- aiven/resource_kafka_schema.go
- aiven/resource_kafka_schema_test.go
This PR adds kafka schema validation, such that we can block updates that violate the compatibility rules
> kafka_schema: validate update in custom diff

- .github/workflows/lint.yml
- Makefile
This PR performs a few cleanup duties and adds a linter that fails if doc generation was forgotten
> remove unneeded makefile directives, repair testing step, add linter for doc generation

- CHANGELOG.md
- aiven/resource_service_user.go
- aiven/resource_service_user_test.go
This PR fixes the service_user.password field by adding the `Computed` attribute. That way it can be referenced in template interpolations again.
> resource service user: mark password as computed

- CHANGELOG.md
- aiven/resource_service_user.go
- aiven/resource_service_user_test.go
- docs/data-sources/service_user.md
- docs/resources/service_user.md
The attribute "pg_allow_replication" is available to be set via the Aiven Golang API, but it is not exposed within the terraform layer.
**We are unable to currently assign this role via terraform. This PR fixes the missing attribute.**
I would be very grateful for a review. Many thanks.
> Fix missing resource service user attribute "pg_allow_replication"

- README.md
- docs/index.md
- templates/index.md
This PR removes the flashy [🚨](https://registry.terraform.io/providers/aiven/aiven/latest/docs#%F0%9F%9A%A8-a-word-of-caution-%F0%9F%9A%A8) and repositions the warning message. Based on some feedback, I understand that the warning message, while much needed, is too flashy and can deter developers from trying the provider. The warning sign shouldn't be the first thing a developer should see for this provider.
For some website preview, only the [🚨](https://registry.terraform.io/providers/aiven/aiven/latest/docs#%F0%9F%9A%A8-a-word-of-caution-%F0%9F%9A%A8) warning sign shows up.
Moving the warning message on the same page.
> Removing the flashy warning and repositioning the warning message

- README.md
we should not tell people to use `sudo podman`, this PR fixes that line
> readme: remove sudo from podman

- docs/resources/kafka_connector.md
- examples/resources/aiven_kafka_connector/resource.tf
This PR addresses the following issues:
1. Breaks down the ``connection.url`` into **host**, **port**, **username**, and **password**. It was **service_uri** and there was a risk of basic auth to be logged as a part of the URL.
2. Uses OpenSearch instead of ElasticSearch example.
> Updating Kafka connector example to modify config params

- aiven/resource_billing_group_test.go
- aiven/resource_project.go
- docs/resources/project.md
- go.mod
- go.sum
Project resource has deprecated fields related to billing group, and in a scenario when a project is associated with a billing group and these deprecated fields are not set in Terraform manifest TF refresh generates none empty plan. With this patch, we will only refresh those fields if they are set to any non zero value since API retrieves back values transferred from associated billing groups.
v3 has no such problem
> v2: project resource fix import and read for deprecated billing group fields

- examples/flink/main.tf
Removing `partitioned_by` field from the resource "aiven_flink_table" as Aiven API has no such argument.
> Removing `partitioned_by` field as Aiven API has no such argument.

- docs/resources/kafka.md
- examples/resources/aiven_kafka/resource.tf
- Updating the Kafka version in the example. You cannot create services using 2.4 version anymore.
- Karapace Boolean is a throwback to when there was a choice between Confluent Schema Registry and Karapace
- The type for `auto_create_topics_enable` is a Boolean; not a String
> Update Kafka version, remove Karapace and fix data type

- .github/workflows/changelog-checker.yml
enforces `CHANGELOG.md` entry to be expected for every PR, i.e. enables `.github/workflow/changelog-checker.yml` to run on every PR
it's difficult for maintainers to put everything in place when preparing a release
> enforce changelog entry for every PR

- CHANGELOG.md
- docs/data-sources/account_authentication.md
- docs/resources/account_authentication.md
- internal/service/account/resource_account_authentication.go
- internal/service/account/resource_account_authentication_test.go
adds support for `auto_join_team_id` in account authentication resource
resolves: #794
to match API docs
> add support for `auto_join_team_id` in account authentication resource

- CHANGELOG.md
- internal/acctest/acctest.go
- internal/schemautil/custom_diff.go
- internal/schemautil/static_ips.go
- internal/schemautil/wait.go
- internal/service/pg/resource_pg_test.go
- internal/service/static_ip/resource_static_ip.go
- fixes PostgreSQL acceptance test with `static_ips` to actually check for their existence after service's creation
- adds acceptance test coverage for modification of `static_ips` in Terraform configs (via PostgreSQL)
- fixes `CustomizeDiffCheckStaticIpDisassociation` behavior
- made it possible to delete static IPs in a single step, without dissociating them
- to make acceptance tests better
- to improve user experience
> test modification of `static_ips` in Terraform configs

- CHANGELOG.md
- internal/service/kafka/resource_kafka_acl_test.go
Change the username in the test to an invalid value. The test was failing.
> Fix testAccKafkaACLWrongUsernameResource

- .github/workflows/acceptance-tests.yml
- .github/workflows/lint.yml
- .github/workflows/release-artifacts.yml
- .github/workflows/sweep.yml
- .github/workflows/unit-tests.yml
- CHANGELOG.md
- go.mod
- go.sum
Newer goreleaser versions require go1.17 to build all GOOS/GOARCH combinations
> fix: use go117

- CHANGELOG.md
- internal/service/kafka/kafka_topic_availability.go
- internal/service/kafka/resource_kafka_topic.go
- User `ImportStatePassthroughContext` for Kafka Topic importer
- Remove v1 API fallback functionality for Kafka Topic availability waiter
- Kafka topic availability waiter optimization by reducing `PollInterval` to `5s`
Before TF v2 (v2.0.7), we've been using the Kafka Topics List endpoint that retrieves a list of all Kafka Topics for service. Around that time, Aiven added support for Kafka Topic config. Unfortunately, the config wasn't included in the Kafka Topic List API response `GET v1/project/{$project}/service/${service}/topic`. As a result, we had to query each topic one by one `GET v1/project/{$project}/service/${service}/topic/${topic_name}`, which is not optimal from the requests per second to API point of view and customer perspective (clearly, this approach would jeopardize …
> Kafka Topic waiter optimizations

- .github/workflows/acceptance-tests.yml
- CHANGELOG.md
To get a better picture of the pipeline in case of flakiness
> tests: disable fail-fast

- .github/workflows/acceptance-tests.yml
- CHANGELOG.md
- internal/schemautil/helpers.go
- internal/schemautil/service.go
- internal/service/service_integration/datasource_service_integration.go
- internal/service/static_ip/resource_static_ip.go
- internal/service/vpc/resource_project_vpc_test.go
When a user provides a wrong Project VPC ID for the service TF provider panic, this PR adds an error handling.
ci: adding `vpn` package to acceptance tests
```
make testacc  PKG=vpc                                            
TF_ACC=1 go test ./internal/service/vpc/... -v -count 1 -parallel 20   -timeout 180m
2022/07/27 09:37:31 [DEBUG] Creating an instance of TopicCache ...
=== RUN   Test_validateVPCID
=== RUN   Test_validateVPCID/basic
=== RUN   Test_validateVPCID/wrong_id
--- PASS: Test_validateVPCID (0.00s)
--- PASS: Test_validateVPCID/basic (0.00s)
--- PASS: Test_validateVPCID/wrong_id (0.00s)
=== RUN   TestAccAivenAWSPrivatelink_basic
resource_aws_privatelink_test.go:20: AIVEN_AWS_PRIVATELINK_VPCID and AIVEN_AWS_PRIVATELINK_PRINCIPAL env variables are required to run this test
--- …
```
> service project vpc id error handling

- .goreleaser.yml
- CHANGELOG.md
- internal/provider/provider.go
fixes version ldflag
introduced in #798
currently, our `User-Agent` string contains misleading `dev` version, and this is not correct
> fix version ldflag

- CHANGELOG.md
- Makefile
makes use of `BUILD_DEV_DIR` in Makefile
it was intended this way
> make use of BUILD_DEV_DIR in Makefile

- CHANGELOG.md
- Makefile
Fix `test-acc` command when user is using PGK
> fix Makefile test-acc command

- internal/schemautil/helpers.go
fix service project vpc custom diff
do not error when id is empty or not set by a user
> fix service project vpc custom diff

- .github/workflows/changelog-enforcer.yml
- CHANGELOG.md
prevents changelog enforcement for PRs from dependabot[bot]
we don't want to have changelog entries for dependency bumps
> prevent changelog enforcement for PRs from dependabot[bot]

- .github/workflows/changelog-enforcer.yml
- CHANGELOG.md
delete me
updates Changelog Enforcer workflow
it has built-in functionality for labels that skip changelog enforcement
also we use a different version pattern in changelog, which is different from what [KeepAChangelog](https://keepachangelog.com) offers
> update Changelog Enforcer workflow

- .golangci.yml
- internal/schemautil/common.go
- dropped unused exclusion rules
- rearranged linters alphabetically
- drop timeout setting, the linter never takes more than several seconds to run—default is 30 minutes
- set linters to believe that we use Go 1.17, see https://github.com/golangci/golangci-lint/issues/2649
- replace `vet` with `govet`
there's going to be a bunch of clean up PRs, I will add a changelog entry for it with the last PR
to improve `.golangci.yml`
> small .golangci.yml fix

- CHANGELOG.md
- internal/service/kafka/resource_kafka_topic.go
- internal/service/kafka/resource_kafka_topic_test.go
retention_hours field is deprecated in v2 and gone from the resource in v3, and the code that sets this value can be deleted.
> remove retention_hours from the kafka topic resource

- CHANGELOG.md
- internal/schemautil/custom_diff.go
- internal/schemautil/service.go
Disk space is not updated during the TF refresh/read, and it may cause some discrepancy between TF state and remove the Aiven state of the resource
> update disk space on refresh

- CHANGELOG.md
- docs/guides/install-terraform-v012.md
- docs/index.md
- examples/account/README.md
- examples/kafka_mirrormaker_bidirectional/README.md
- examples/kafka_mirrormaker_global/README.md
- templates/guides/install-terraform-v012.md
- templates/index.md
The public Terraform Registry docs included some instances of "Aiven Terraform Provider" whereas the official name of the product is "Aiven Provider for Terraform".
This PR updates those texts as well as some outdated docs link for creating authentication tokens.
This is the only way to make a docs change.
I didn't make any change to `docs/` directory since I believe that the docs are auto-generated from the template. Please review if I made changes to the correct place/directory.
> Update official provider name

- CHANGELOG.md
- docs/resources/flink.md
- examples/resources/aiven_flink/resource.tf
- internal/schemautil/templates/service_user_config_schema.go
- internal/schemautil/templates/service_user_config_schema.json
The Flink version in Aiven for be updated to 1.15. The support for 1.13 will be removed. 
Change all references to Flink 1.15.
> update Flink version to 1.15

- .github/CODEOWNERS
I used to be able to approve PRs and in some situations am still required to.
> codeowners: add mhoffm-aiven

- .github/workflows/examples-tests.yml
Copy/pasted job name, should be renamed.
> rename examples-tests job

- internal/service/account/sweep.go
Sweep refers to old and non-existing AuthenticationMethod fields.
> fix: update auth fields for sweep

- docs/resources/service_integration.md
- docs/resources/vpc_peering_connection.md
- templates/resources/service_integration.md.tmpl
- templates/resources/vpc_peering_connection.md.tmpl
In the cases where the resource documentation has been overridden the code for importing the example import statement was incorrect leading to the terraform registry documentation stating the following;
> Import is supported using the following syntax: {{codefile "shell" "examples/resources/aiven_service_integration/import.sh"}}
With this change the import statement is rendered correctly in the documentation.
There is no other way to achieve correctly rendered documentation.
> Fixes rendering of import examples

- CHANGELOG.md
- docs/resources/clickhouse.md
- internal/service/clickhouse/resource_clickhouse.go
Changes the wording in the clickhouse resource documentation to reflect the currently available service integrations.
It's a simple doc wording change.
> docs: update available clickhouse integrations

- CHANGELOG.md
- internal/service/vpc/resource_aws_vpc_peering_connection.go
- internal/service/vpc/resource_azure_vpc_peering_connection.go
- internal/service/vpc/resource_gcp_vpc_peering_connection.go
- internal/service/vpc/resource_transit_gateway_vpc_attachement.go
- internal/service/vpc/resource_vpc_peering_connection.go
VPC peering connection id parser doesn't validate user input and panics.
New parser:
- validates user input has valid size
- won't panic because of validation
> fix vpc peering connection `terraform import`

- CHANGELOG.md
- docs/data-sources/service_integration_endpoint.md
- docs/resources/service_integration_endpoint.md
- internal/service/service_integration/resource_service_integration_endpoint.go
Adds the OpenSearch schema for external integration endpoints which is currently missing and a customer would like to use
> Added missing OpenSearch external integration endpoint schema

- CHANGELOG.md
- docs/resources/azure_privatelink_connection_approval.md
- examples/resources/aiven_azure_privatelink_connection_approval/resource.tf
- go.mod
- go.sum
- internal/service/vpc/resource_azure_privatelink_connection_approve.go
- internal/service/vpc/resource_azure_privatelink_connection_approve_test.go
- adds aiven_azure_privatelink_connection_approval test
- fixes add aiven_azure_privatelink_connection_approval docs
- downgrades terraform-plugin-sdk to run multiple providers in [tests](https://github.com/hashicorp/terraform-plugin-sdk/issues/1064)
> add aiven_azure_privatelink_connection_approval test

- CHANGELOG.md
- docs/data-sources/project_vpc.md
- examples/data-sources/aiven_project_vpc/data-source.tf
- internal/service/vpc/datasource_project_vpc.go
- internal/service/vpc/datasource_project_vpc_test.go
Reverts `project` and `cloud_name` deprecation for `datasource_project_vpc`.
> revert datasource_project_vpc project and cloud_name deprecation

- CHANGELOG.md
- docs/data-sources/service_integration.md
- docs/resources/service_integration.md
- internal/service/service_integration/resource_service_integration.go
- internal/service/service_integration/resource_service_integration_test.go
Adds `clickhouse_kafka_user_config` to the service integration type schema 
to support `clickhouse_kafka` integration type
Resolves: #968.
> support "clickhouse_kafka" integration type in "aiven_service_integration"

- CHANGELOG.md
- internal/schemautil/service.go
- internal/schemautil/userconfig/apiconvert/fromapi.go
- internal/schemautil/userconfig/apiconvert/fromapi_test.go
- internal/schemautil/userconfig/apiconvert/toapi.go
- internal/schemautil/userconfig/apiconvert/toapi_test.go
- internal/schemautil/userconfig/apiconvert/util.go
- internal/schemautil/userconfig/apiconvert/util_test.go
- internal/schemautil/userconfig/convert.go
- internal/schemautil/userconfig/handle.go
- internal/schemautil/userconfig/userconfig_test.go
- internal/schemautil/userconfig/util.go
- internal/service/pg/resource_pg.go
- internal/service/service_integration/resource_service_integration.go
- internal/service/service_integration/resource_service_integration_endpoint.go
replaces `panic` calls with `error` types where possible in static schema generator
to make things better
> refactor(ssg): replace panics with errors

- CHANGELOG.md
- internal/service/vpc/resource_aws_vpc_peering_connection_test.go
- internal/service/vpc/resource_azure_privatelink_connection_approve_test.go
- internal/service/vpc/resource_transit_gateway_vpc_attachement.go
- internal/service/vpc/resource_transit_gateway_vpc_attachement_test.go
- internal/service/vpc/resource_vpc_peering_connection.go
- Fix `aiven_transit_gateway_vpc_attachment` fails to parse ID, add test
- Add `aiven_aws_vpc_peering_connection` tests
Resolves: #967.
> fix `aiven_transit_gateway_vpc_attachment` fails to parse ID

- CHANGELOG.md
- docs/data-sources/gcp_vpc_peering_connection.md
- docs/resources/gcp_vpc_peering_connection.md
- internal/service/vpc/resource_gcp_vpc_peering_connection.go
- internal/service/vpc/resource_gcp_vpc_peering_connection_test.go
- add `self_link` computed field field, to support this: 
```hcl
resource "google_compute_network_peering" "foo" {
name         = "acc-test-vpc-peering"
network      = data.google_compute_network.foo.id
peer_network = aiven_gcp_vpc_peering_connection.foo.self_link
}
```
- GCP VPC peering e2e tests (including import and data-source validation) 
```shell
TF_ACC=1 CGO_ENABLED=0 go test ./internal/service/vpc/... \
-v -count 1 -parallel 10  -run=TestAccAivenGCPPeeringConnection_basic -timeout 180m
2022/11/30 10:56:01 [DEBUG] Creating an instance of kafkaTopicCache ...
=== RUN   TestAccAivenGCPPeeringConnection_basic
resource_gcp_vpc_peering_connection_test.go:86: GCP VPC peering connection in VPC (7d072ab3-0256-4693-81fe-d39a33758ef3) is in state PENDING_PEER, waiting for it to be ACTIVE... …
```
> add gcp vpc self link

- CHANGELOG.md
- docs/guides/examples.md
- examples/clickhouse/main.tf
- examples/clickhouse/services.tf
- examples/clickhouse_integrations/kafka_source/Readme.rst
- examples/clickhouse_integrations/kafka_source/access.tf
- examples/clickhouse_integrations/kafka_source/clickhouse.tf
- examples/clickhouse_integrations/kafka_source/kafka.tf
- examples/clickhouse_integrations/kafka_source/project.tf
- examples/clickhouse_integrations/kafka_source/provider.tf
- examples/clickhouse_integrations/kafka_source/variables.tf
- examples/clickhouse_integrations/postgres_source/Readme.rst
- examples/clickhouse_integrations/postgres_source/clickhouse.tf
- examples/clickhouse_integrations/postgres_source/postgres.tf
- examples/clickhouse_integrations/postgres_source/project.tf
- examples/clickhouse_integrations/postgres_source/provider.tf
- examples/clickhouse_integrations/postgres_source/variables.tf
- templates/guides/examples.md
This PR adds three ClickHouse examples: 
- a standalone service example showcasing privilege grants, and 
- two service integration examples for Kafka and PostgreSQL sources respectively
The standalone ClickHouse service example is on the toplevel examples dir to stay consistent with other services' examples.
The service integrations examples are grouped in a `clickhouse_integrations` directory: there may be more sources and sinks in the future. The two examples are split into two sub-directories for clarity and because users may want to tweak and test them separately as a first step.
The examples are not very worked in terms of access controls from the PostgreSQL and Kafka side of things because the goal is to highlight the integrations more than the other aspects of the provider's …
> Add three ClickHouse examples (standalone service, Postgres & Kafka integrations)

- CHANGELOG.md
- internal/schemautil/service.go
Would it be possible to add `kafka_authentication_method` attribute to the list of components from the output of an Aiven service  ? 
We would like to be able to differentiate components between "sasl" and "certificate" and as of today, this value (`aiven.kafka.components[].kafka_authentication_method`) is always an empty string. 
The [Aiven API](https://api.aiven.io/doc/#tag/Service/operation/ServiceGet) returns this attribute (it's not required though) and it seems to be supported by the [Aiven Go Client](https://github.com/aiven/aiven-go-client/blob/master/service.go#L84)
> add kafka_authentication_method support

- CHANGELOG.md
- internal/schemautil/common.go
- internal/schemautil/schemautil_test.go
- internal/schemautil/service.go
- internal/service/kafka/resource_kafka_test.go
- Exposes `ssl` field in service components.
- Adds test for `kafka_authentication_method` field
Resolves #992.
> expose ssl field in service components

- CHANGELOG.md
- internal/schemautil/userconfig/util.go
Fixes races in tests because of concurrent map writes to `cachedRepresentationMaps`.
> fix concurrent map writes

- internal/service/clickhouse/resource_clickhouse_database_test.go
- internal/service/clickhouse/resource_clickhouse_grant_test.go
- internal/service/clickhouse/resource_clickhouse_role_test.go
- internal/service/clickhouse/resource_clickhouse_test.go
- internal/service/clickhouse/resource_clickhouse_user_test.go
- internal/service/service_integration/resource_service_integration_test.go
Fixes clickhouse acc tests by replacing deprecated plans.
> fix clickhouse acc tests

- CHANGELOG.md
- internal/schemautil/mutations.go
- internal/schemautil/mutations_test.go
- internal/schemautil/userconfig/apiconvert/toapi.go
- internal/schemautil/userconfig/apiconvert/toapi_test.go
this PR adds support for normalization of `ip_filter_object`
additionally, it introduces a small fix to the `apiconvert` package which is going to prevent the omit of nested items if the top item has been changed, e.g. if we modify only the `description` field of an `ip_filter_object`, the API expects us to send a full `ip_filter_object` array, instead of only modified items; this should as well be the case for other nested structures
resolves #987
currently, we didn't have a way to utilize the functionality that is provided via `ip_filter_object`
this PR makes `ip_filter_object` to function properly
> feat(schemautil): normalize ip_filter_object

- CHANGELOG.md
- internal/service/account/resource_account_team_member.go
- internal/service/account/resource_account_team_member_test.go
If user's email not on the members list terraform won't warn.
With this fix it will return an error.
> improve team member deletion

- .github/workflows/examples-tests.yml
- examples/kafka_connect/provider.tf
- examples/kafka_connectors/os_sink/provider.tf
- examples/kafka_connectors/os_sink/services.tf
- examples/kafka_prometheus/provider.tf
- examples/mysql/provider.tf
- examples/mysql/service.tf
- examples/mysql/variables.tf
- examples/postgres/provider.tf
- examples_tests/base.go
- examples_tests/base_test.go
- examples_tests/kafka_connect_test.go
- examples_tests/kafka_connector_test.go
- examples_tests/kafka_prometheus_test.go
- examples_tests/mysql_test.go
- examples_tests/postgres_test.go
- sample_project/sample.tf
- Adds mysql example test.
- Adds prefixed random name generator which shares same seed for each service within a test. That makes easier to track belonging resources. Prefix is hardcoded for the sweep command.
- Adds `workflow_dispatch` to the examples tests job to trigger it on demand.
- Limits required provider version for existing example tests
> add mysql example test

- internal/schemautil/userconfig/stateupgrader/typeupgrader/typeupgrader.go
- internal/schemautil/userconfig/stateupgrader/typeupgrader/typeupgrader_test.go
moves `switch` to `convert` fn
deduplicates code and reduces complexity
> refactor(typeupgrader): move switch to convert fn

- CHANGELOG.md
- internal/schemautil/userconfig/apiconvert/toapi.go
- internal/service/cassandra/cassandra_test.go
- internal/service/kafka/kafka_test.go
Fixes service's user config "to api" serialisation. If object has null fields only it's not send nor casted to object.
Resolves #1033
> fix kafka user config with null values only

- CHANGELOG.md
- internal/service/flink/flink_job.go
fixes incorrect state name spelling in Flink resource
it panics otherwise
> fix(flink): incorrect state name spelling

- internal/sweep/sweep.go
Sweeps services with `test-tf` prefix
> sweep test-tf prefix too

- internal/schemautil/common.go
- internal/service/flink/flink_job.go
- internal/service/flink/flink_table.go
Mark `aiven_flink_table` and `aiven_flink_job` resources as deprecated.
> chore: mark flink job and table resources as deprecated

- .github/workflows/acceptance-tests.yml
adds an automatic retry for 15 times OR the timeout of 1 hour, whichever hits faster
we already have this behavior for the `sweep` step
unfortunately, the tests are flaky, but we want to have better view of tests that are actually failing
> ci(acctests): fix flaky tests failing

- internal/service/kafka/kafka_test.go
this test is completely wrong, the `default_acl` field is immutable, and checking for any changes in it makes no sense
currently, the test is failing
> test(kafka): fix default_acl behavior

- CHANGELOG.md
- internal/schemautil/schemautil.go
it appears that when Terraform calls for `DiffSuppressFunc`, it has not yet reached enough context with the internal [`Apply`](https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/resource.go#L762) method of `*schema.Resource`
it makes it that https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/resource.go#L835 hasn't been executed yet, and when calling for `d.IsNewResource()` within `DiffSuppressFunc` context, it always results in `false`
we want to have `CreateOnlyDiffSuppressFunc` working :)
> fix(schemautil): CreateOnlyDiffSuppressFunc

- CHANGELOG.md
- internal/schemautil/helpers.go
- internal/schemautil/service.go
When `maintenance_window_dow` set to `never` on the backend terraform send it back on updates. And that fails with the validation, because `never` is not available through the API.
> fix(schemautil): maintenance_window_dow=never resource update

- docs/index.md
- templates/index.md
Change the example provider configuration to use at least version 3.10.0. 
Resolves: no issue
By using the example provider configuration users may accidentally use old version of the provider on their projects.
> fix(docs): index.md provider version

- .github/dependabot.yml
This will make it compliant with commit message linters
> fix: add commit message prefix to dependabot

- .github/dependabot.yml
This reverts commit 60f44239b88079a8f7277a7e621b809ec67eb098.
it was added erroneously
> revert: fix: add commit message prefix to dependabot (#1077)

- CHANGELOG.md
- internal/sdkprovider/service/kafka/kafka_topic_create.go
- internal/sdkprovider/service/kafka/kafka_topic_test.go
Because of retries, kafka topic creation process may get already existing topic.
> fix(kafkatopic): conflict on create existing topic

- internal/schemautil/service.go
makes it possible to change the default timeout of the provider's resources on compile time via `-ldflags "-X github.com/aiven/terraform-provider-aiven/internal/schemautil.DefaultTimeoutMinutes=30"`
resolves #1054 
to allow to change timeouts values outside of Terraform protocol during compile time
> refactor(schemautil): global default timeout minutes

- CHANGELOG.md
- internal/schemautil/userconfig/apiconvert/toapi.go
- internal/schemautil/userconfig/apiconvert/toapi_test.go
fixes `ToAPI` for objects and arrays
resolves #1088
to make it work :)
> fix(apiconvert): ToAPI for objects and arrays

- CHANGELOG.md
- docs/data-sources/kafka_connector.md
- docs/resources/kafka_connector.md
- internal/sdkprovider/service/kafka/kafka_connector.go
makes `config` field of `aiven_kafka_connector` resource non-sensitive
resolves #1099 
reverts #810 (introduced in #701)
we cannot predict fields in the `config` field at all, so this has to remain a schemaless map on our side
users would still be able to mark specific fields sensitive if they wish to do so by using `sensitive()` HCL function, e.g.:
```hcl
config = {
"topics"                         = aiven_kafka_topic.topic-logs-app-1.topic_name
"connector.class"                = "io.aiven.kafka.connect.opensearch.OpensearchSinkConnector"
"type.name"                      = "os-connector"
"name"                           = "kafka-os-con1"
"connection.url"                 = "https://${aiven_opensearch.os-service1.service_host}:${aiven_opensearch.os-service1.service_port}" …
```
> feat(kafka_connector): make config non-sensitive

- CHANGELOG.md
- internal/schemautil/custom_diff.go
- internal/sdkprovider/service/m3db/m3db_test.go
IP filters and M3 namespaces have only one field in the API request and response but can be set in 3 different ways using Terraform. However, adding a custom diff logic that triggers an error if a user sets more than one field in Terraform for these two corresponding properties.
> fix: add conflicting with logic for namespaces and ip_filters

- .golangci.yml
drops forced Go version in `golangci-lint`
https://github.com/golangci/golangci-lint/issues/2649 was resolved
> ci(lint): drop forced Go version in golangci-lint

- CHANGELOG.md
- internal/schemautil/userconfig/apiconvert/toapi.go
- internal/schemautil/userconfig/apiconvert/toapi_test.go
- internal/schemautil/userconfig/dist/service_types.go
- internal/schemautil/userconfig/handle.go
fixes double apply necessity on migration from typeless keys to typed keys
resolves #1073 
to eliminate the bug
> fix(apiconvert): double apply necessity on migration

- CHANGELOG.md
- docs/data-sources/service_integration_endpoint.md
- docs/resources/service_integration_endpoint.md
- internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration_endpoint.go
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
drops `signalfx` from supported integration types
this is no longer supported in the backend, relevant changes were merged in the upstream library https://github.com/aiven/go-api-schemas/commit/b72e6a79b0ebefe1d726a0923b04174bace827c0
since this no longer works, we have no other option but to drop this from our Terraform provider as well
> feat: drop signalfx from supported integration types

- CHANGELOG.md
- go.mod
- go.sum
- internal/sdkprovider/service/mysql/mysql_user.go
When a MySQL user has no password field set but has an authentication, it won't be propagated to Aiven. Lets fix that.
> fix(mysql): user creation authentication field

- CHANGELOG.md
- docs/resources/clickhouse_grant.md
- examples/resources/aiven_clickhouse_grant/resource.tf
- internal/sdkprovider/service/clickhouse/grant.go
1. Fix `" WITH GRANT"` that should be `" WITH GRANT OPTION"`.
2. When a table is unspecified, write `.*` instead of nothing.
A query like `GRANT SELECT ON foo TO bar` grants `SELECT` on the table `foo` of the current database of the connection.
Instead we want to generate `GRANT SELECT ON foo.* TO bar` to grant `SELECT` on all tables of the `foo` database.
3. Adjust the documentation to not suggest using `"*"` as the table name.
A `"*"` table name does not grant privilege on all tables, it grants privilege on the table named `*`.
To grant privilege on all tables, the table name should be completely omitted.
Reference: https://clickhouse.com/docs/en/sql-reference/statements/grant#granting-privilege-syntax
> fix: adjust generated SQL for ClickHouse privilege grants

- CHANGELOG.md
- docs/resources/kafka.md
- internal/sdkprovider/service/kafka/kafka.go
Deprecates `karapace` option on `kafka`.
> chore(kafka): deprecate karapace option

- docs/resources/kafka.md
- internal/sdkprovider/service/kafka/kafka.go
Fixes documentation for kafka.
> fix(docs): remove optional mark from kafka's computed fields

- internal/schemautil/common.go
- internal/schemautil/service.go
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow_test.go
- internal/sdkprovider/service/serviceintegration/service_integration.go
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
Replaces custom enum validator with builtin one.
> refactor: use default validation.StringInSlice

- CHANGELOG.md
- internal/sdkprovider/service/kafka/kafka_topic.go
- internal/sdkprovider/service/kafka/kafka_topic_cache.go
- internal/sdkprovider/service/kafka/kafka_topic_cache_test.go
- internal/sdkprovider/service/kafka/kafka_topic_wait.go
We query Kafka Topics in batches with up to 100 topics simultaneously using the v2 list endpoint. If we add a topic name that does not exist to the query batch, API retrieves a 404 response. Furthermore, it retrieves a 404 even in case all topics in the batch do exist except one.
This API behavior causes problems when Terraform clients accidentally delete one or more topics outside of Terraform and then try to refresh a state. In this case, an nonexistent topic in the state will trigger a 404 response from the API.
In case we get 404 from the v2 list endpoint we will query v1 list (that has all topics for a services but topics data is not fully present in the response) and use to to determine which of the Kafka Topics do not exist and propagate 404 further for these topics only.
> fix(kafka_topic): 404 error handling

- CHANGELOG.md
- internal/sdkprovider/service/account/account_team_project.go
un-deprecates `aiven_account_team_project`
we should deprecate it when there's an alternative
> chore(aiven_account_team_project): un-deprecate

- CHANGELOG.md
- internal/sdkprovider/service/opensearch/opensearch_acl_config.go
- internal/sdkprovider/service/opensearch/opensearch_acl_rule.go
- internal/sdkprovider/service/organization/organization.go
- internal/sdkprovider/service/organization/organizational_unit.go
- internal/sdkprovider/service/organization/util.go
fixes wrong ID used for `organization` resources
the `aiven_organization` resource should have `organization_id` used as its ID, while still being able to create nested units, which require organization's account ID
this ID is more important to us since it's used in other organization-related resources (which aren't implemented yet), thus abolishing the need in organization's account ID
> fix(organization): wrong ID used

- internal/sdkprovider/service/project/project.go
The debug log message for associating a project with a billing group seems to have a typo, so fix it.
> fix: fix typo in a debug log message

- CHANGELOG.md
- internal/schemautil/schemautil.go
- internal/sdkprovider/service/kafka/kafka_schema.go
- internal/sdkprovider/service/kafka/kafka_schema_test.go
Kafka schema `compatibility_level` is handled in a special way. 
If it is not set by user it is not stored in state.
However, import command get's empty resource with empty compatibility_level.
Then when `plan` is called terraform shows the diff: now it reads compatibility_level value but the state doesn't have it.
> fix(kafka_schema): compatibility_level import shows non empty plan

- Makefile
Verbose output is displayed as linter errors on github. 
This pr runs terraform format check in quiet mode.
> chore(ci): quiet terraform fmt linter

- CHANGELOG.md
- internal/sdkprovider/service/project/project.go
fixes incorrect `account_id` behavior in mixed constraint setup
it didn't work
> fix(project): incorrect account_id behavior in mixed constraint setup

- CHANGELOG.md
- go.mod
- go.sum
- internal/sdkprovider/service/kafka/kafka_connector.go
- internal/sdkprovider/service/kafka/kafka_connector_test.go
- internal/sdkprovider/service/kafka/kafka_topic.go
- internal/sdkprovider/service/kafka/kafka_topic_cache.go
- internal/sdkprovider/service/kafka/kafka_topic_create.go
- internal/sdkprovider/service/kafka/kafka_topic_data_source_test.go
- internal/sdkprovider/service/kafka/kafka_topic_test.go
- internal/sdkprovider/service/kafka/kafka_topic_wait.go
- internal/sdkprovider/service/serviceintegration/service_integration.go
- internal/sdkprovider/service/vpc/project_vpc_test.go
- Uses client's retries for corner cases
- Fixes KafkaConector create (retries 404 on POST)
- Fixes VPC test
> chore: use client's retries

- internal/sdkprovider/service/kafka/kafka_connector.go
Sets a minute for KafkaConnector create retries.
> fix(kafka_connector): set a minite timeout for create retries

- docs/data-sources/kafka.md
- docs/resources/kafka.md
- internal/schemautil/userconfig/dist/service_types.go
- main.go
> revert(kafka): remove the tiered storage functionality

- CHANGELOG.md
We have uploaded [draft](https://github.com/aiven/terraform-provider-aiven/actions/runs/5599055326) of v4.8, this release just overrides the binary in the registry.
> chore(release): v4.8.1

- CHANGELOG.md
- internal/sdkprovider/service/vpc/transit_gateway_vpc_attachment.go
Sends empty slices as arrays, not nil for `aiven_transit_gateway_vpc_attachment`. 
API doesn't accept nil for arrays.
Resolves #1310 
Zero value slice is [equal to nil](https://go.dev/blog/slices-intro).
```golang
var p []int // == nil
```
> fix(transit_gateway_vpc_attachment): send empty slices on update, not nil

- internal/sdkprovider/service/kafka/kafka_topic.go
- internal/sdkprovider/service/kafka/kafka_topic_cache.go
- internal/sdkprovider/service/kafka/kafka_topic_cache_test.go
Inits cache on module level to run unit test without having provided initialized. See `initTopicCache()`.
> refactor(kafka_topic_cache): init cache on module level

- .github/workflows/acceptance-tests.yml
- internal/sdkprovider/provider/provider.go
- internal/sdkprovider/service/kafka/kafka_test.go
- internal/sdkprovider/service/kafkaschema/kafka_schema.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_configuration.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_configuration_data_source.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_configuration_test.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_data_source.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl_data_source.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl_test.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_test.go
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_cache.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_cache_test.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_create.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_data_source.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_data_source_test.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_wait.go
Splits `kafka` package to run tests faster.
> refactor(kafka): split kafka package to run tests faster

- docs/resources/clickhouse_grant.md
- internal/sdkprovider/service/clickhouse/clickhouse_grant.go
It's not immediately obvious that the table field should be omitted, instead of specifying a "*" table.
Add a phrase to highlight that trap.
This can reduce user frustration.
> docs(clickhouse): highlight how to grant privilege on all tables

- internal/sdkprovider/service/clickhouse/clickhouse_grant.go
- internal/sdkprovider/service/clickhouse/clickhouse_role.go
- internal/sdkprovider/service/clickhouse/clickhouse_user.go
- internal/sdkprovider/service/clickhouse/common.go
Clickhouse ressources are in place for more a years and we still have deprecated warning message.
The purpose of this pull request is to remove this deprecated message from clickhouse ressources
aiven_clickhouse_user
aiven_clickhouse_grant
aiven_clickhouse_role
I'm not 100% sure why those ressources was still not in GA if i look the change log ressource seem to be in GA since a while ([3.0.0] - 2022-05-13)
If this ressource should stay in beta feel free to update this PR to update documentation on those ressources.
> docs(clickhouse): remove deprecation warnings

- internal/sdkprovider/service/connectionpool/connection_pool_test.go
fixes misuse of `aiven_opensearch_user` resource instead of `aiven_pg_user` in a `connectionpool` test, that is `pg`-related
the test was failing
> test(connectionpool): fix misuse of wrong user resource

- sample_project/sample.tf
* Replace `ip_filter` with `ip_filter_object`
* Fix typo
> docs(sample_project): replace deprecated ip_filter argument

- CHANGELOG.md
- docs/resources/project.md
- internal/sdkprovider/service/project/project.go
- internal/sdkprovider/service/project/project_test.go
removes obsolete fields from `project` resource
they are no longer functioning since the release of organizations
> chore(project): deprecate obsolete fields

- CHANGELOG.md
- internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_wait.go
Fixes acceptance but performance patch get reverted
> fix(kafkatopic): acc tests but reverting performance fix

- internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
Fixing 409 error:
```
Error: 409: {"errors":[{"message":"Cluster only has 2 broker(s), cannot set replication factor to 3","status":409}],"message":"Cluster only has 2 broker(s), cannot set replication factor to 3"} - 
```
> fix(kafkatopic): replication for startup-2 plan

- CHANGELOG.md
- docs/data-sources/pg_user.md
- docs/resources/pg_user.md
- internal/sdkprovider/service/pg/pg_user.go
- internal/sdkprovider/service/pg/pg_user_test.go
allows to modify `pg_user` replication settings
resolves #1362 
this is long ago supported by the API
> feat(pg): allow to modify user replication settings

- internal/sdkprovider/service/kafka/mirrormaker_replication_flow_test.go
fixes mirrormaker invalid offset syncs topic location test
the error message was updated in backend, I've made it a bit more fail-proof as well in this PR
> test(kafka): fix mirrormaker invalid offset syncs topic location

- CHANGELOG.md
- internal/service/kafka/kafka_topic_cache_test.go
- internal/service/project/project_user.go
V3 fix for project user when user invitation has yet to be accepted, but we try to refresh data and send another invitation, resulting in 409 error from Aiven.
> fix(project_user): invite error handling

- CHANGELOG.md
- docs/data-sources/kafka_schema.md
- docs/data-sources/kafka_schema_configuration.md
- docs/resources/kafka_schema.md
- internal/sdkprovider/service/kafkaschema/kafka_schema.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_test.go
allows usage of `protobuf` schema in Kafka resources
resolves #1366
we would want to have this feature in place
> feat(kafka): allow protobuf schema

- go.mod
> fix(go.mod): fix broken dependency

- internal/plugin/service/serviceintegration/service_integration_resource.go
- internal/plugin/service/serviceintegration/userconfig.go
- internal/plugin/service/userconfig/integration/clickhousekafka/clickhouse_kafka_test.go
- internal/plugin/service/userconfig/integration/clickhousepostgresql/clickhouse_postgresql_test.go
- internal/plugin/service/userconfig/integration/datadog/datadog_test.go
- internal/plugin/service/userconfig/integration/externalawscloudwatchmetrics/external_aws_cloudwatch_metrics_test.go
- internal/plugin/service/userconfig/integration/kafkaconnect/kafka_connect_test.go
- internal/plugin/service/userconfig/integration/kafkalogs/kafka_logs_test.go
- internal/plugin/service/userconfig/integration/kafkamirrormaker/kafka_mirrormaker_test.go
- internal/plugin/service/userconfig/integration/logs/logs_test.go
- internal/plugin/service/userconfig/integration/metrics/metrics_test.go
- internal/schemautil/plugin.go
- internal/schemautil/userconfig/dist/integration_endpoint_types.go
- internal/schemautil/userconfig/dist/integration_types.go
- internal/schemautil/userconfig/dist/service_types.go
- ucgenerator/tests.go
Some errors has been omitted because of diags vs error approaches
> fix: user config marshal error omitted

- internal/sdkprovider/service/opensearch/opensearch_security_plugin_config_test.go
- internal/sdkprovider/service/opensearch/opensearch_user_test.go
fixes a weak password error in our [acceptance tests](https://github.com/aiven/terraform-provider-aiven/actions/runs/6540687245/job/17761032810)
to make it work :)
> test(opensearch): fix weak password error

- CHANGELOG.md
- internal/sdkprovider/service/account/account_team.go
- internal/sdkprovider/service/account/account_team_member.go
- internal/sdkprovider/service/project/project_user.go
Deprecating account teams and team member resources alongside project users, as discussed internally. 
:warning: The deprecation message does not contain a particular resource as the recommended replacement because we do not expect a 1-to-1 transition from account to organization, and not all organization-related functionality will be transferred to the Terraform provider due to an internal investigation.
> chore: deprecating account and project user

- .github/workflows/acceptance-tests.yml
- internal/sdkprovider/service/account/account_authentication_test.go
- internal/sdkprovider/service/account/account_team_data_source_test.go
- internal/sdkprovider/service/account/account_team_member_data_source_test.go
- internal/sdkprovider/service/account/account_team_member_test.go
- internal/sdkprovider/service/account/account_team_project_test.go
- internal/sdkprovider/service/account/account_team_test.go
fixes failing team test
to make them work
> test(account): fix failing team tests

- CHANGELOG.md
- internal/sdkprovider/service/mysql/mysql_user.go
uses correct read context fn in mysql user resource
resolves #1401
to fix it
> fix(mysql): use correct read context fn

- internal/sdkprovider/service/flink/flink_application_version.go
fixes Flink application version flakiness
to make it work :)
> test(flink): fix application version flakiness

- CHANGELOG.md
drops v4 changelog entry: https://github.com/aiven/terraform-provider-aiven/blob/v4/CHANGELOG.md
it will already be released in v4, so we don't need to duplicate the changelog entry here
> chore(changelog): drop v4 entry

- .github/workflows/acceptance-tests-v4.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/examples-tests.yml
- .github/workflows/lint.yml
- .github/workflows/release-artifacts.yml
- .github/workflows/sweep.yml
- .github/workflows/unit-tests.yml
- ci(checkout): set fetch-depth zero globally
- ci(acctests): run for v4 branch
- we want to have CI in place for v4 and v3 branches
- we want the CI to work properly
> ci(acctests): run for v4 branch

- CHANGELOG.md
- Makefile
- internal/schemautil/schemautil.go
- main.go
- fixes unmarshalling empty userconfig crash
- improves debugging experience
- to have userconfig unmarshalling working
- to be able to debug in a more efficient way
> fix(schemautil): unmarshalling empty userconfig crash

- CONTRIBUTING.md
Improves documentation of the environment variables that are used or influence the running of the acceptance tests.
Fully running the acceptance tests uses more than just a project, there are tests which interact with accounts and orgs, and it took some questioning on Slack and searching the source code to figure out how to properly run these tests locally and against a dev environment, so we should probably document how to get them to run here to save future engineers time.
> docs: document other env vars for make test-acc

- examples_tests/base.go
fixes `semgrep` failing on `math/rand` import
we don't need no failures :)
> test(examples): fix semgrep failing on math/rand import

- CHANGELOG.md
- internal/schemautil/userconfig/apiconvert/toapi.go
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint_test.go
prevents skipping basic auth username/password in certain service integrations
resolves #1411
API always wants us to send these details, regardless of if they're changed or not
> fix(apiconvert): never skip basic auth username/password

- go.mod
- go.sum
bumps `aiven-go-client` to v2.4.0
to have the latest one in place
> build(deps): bump aiven-go-client to v2.4.0

- CHANGELOG.md
- docs/data-sources/account_team_member.md
- docs/data-sources/organization_user.md
- docs/data-sources/project_user.md
- docs/resources/account_team_member.md
- docs/resources/organization_user.md
- docs/resources/project_user.md
- internal/schemautil/schemautil.go
- internal/sdkprovider/service/account/account_team_member.go
- internal/sdkprovider/service/organization/organization_user.go
- internal/sdkprovider/service/project/project_user.go
makes sure emails are lowercase and valid
uppercase emails are not accepted by our backend
resolves #1450
it should be this way
> feat: make sure emails are lowercase and valid

- CHANGELOG.md
- docs/resources/kafka_topic.md
- internal/service/kafka/kafka_topic.go
Kafka Topic config options `unclean_leader_election_enable` deprecation, since it is no longer function on the back-end side.
> chore(backport): deprecate unclean_leader_election_enable in aiven_kafka_topic

- CHANGELOG.md
- docs/data-sources/cassandra.md
- docs/data-sources/clickhouse.md
- docs/data-sources/flink.md
- docs/data-sources/grafana.md
- docs/data-sources/influxdb.md
- docs/data-sources/kafka.md
- docs/data-sources/kafka_connect.md
- docs/data-sources/kafka_mirrormaker.md
- docs/data-sources/m3aggregator.md
- docs/data-sources/m3db.md
- docs/data-sources/mysql.md
- docs/data-sources/opensearch.md
- docs/data-sources/pg.md
- docs/data-sources/redis.md
- docs/resources/cassandra.md
- docs/resources/clickhouse.md
- docs/resources/flink.md
- docs/resources/grafana.md
- docs/resources/influxdb.md
- docs/resources/kafka.md
- docs/resources/kafka_connect.md
- docs/resources/kafka_mirrormaker.md
- docs/resources/m3aggregator.md
- docs/resources/m3db.md
- docs/resources/mysql.md
- docs/resources/opensearch.md
- docs/resources/pg.md
- docs/resources/redis.md
- internal/schemautil/service.go
adds `connection_info` field to components of all services
resolves #1444 
to provide with a convenient way to retrieve `host:port` string and ease the process of usage of those fields
> feat(service): add connection_info field to components

- CHANGELOG.md
- docs/data-sources/cassandra.md
- docs/data-sources/clickhouse.md
- docs/data-sources/flink.md
- docs/data-sources/grafana.md
- docs/data-sources/influxdb.md
- docs/data-sources/kafka.md
- docs/data-sources/kafka_connect.md
- docs/data-sources/kafka_mirrormaker.md
- docs/data-sources/m3aggregator.md
- docs/data-sources/m3db.md
- docs/data-sources/mysql.md
- docs/data-sources/opensearch.md
- docs/data-sources/pg.md
- docs/data-sources/redis.md
- docs/resources/cassandra.md
- docs/resources/clickhouse.md
- docs/resources/flink.md
- docs/resources/grafana.md
- docs/resources/influxdb.md
- docs/resources/kafka.md
- docs/resources/kafka_connect.md
- docs/resources/kafka_mirrormaker.md
- docs/resources/m3aggregator.md
- docs/resources/m3db.md
- docs/resources/mysql.md
- docs/resources/opensearch.md
- docs/resources/pg.md
- docs/resources/redis.md
- internal/schemautil/service.go
renames services' `connection_info` field to `connection_uri`
better naming
> chore(service): rename connection_info field to connection_uri

- internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
Should not expect non-empty plan:
> When a test is ran, Terraform runs plan, apply, refresh, and then final plan for each TestStep in the TestCase. If the last plan results in a non-empty plan, Terraform will exit with an error. This enables developers to ensure that configurations apply cleanly. In the case of introducing regression tests or otherwise testing specific error behavior, TestStep offers a boolean field [ExpectNonEmptyPlan](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-testing/helper/resource#TestStep.ExpectNonEmptyPlan) as well ExpectError regex field to specify ways the test framework can handle expected failures. If these properties are omitted and either a non-empty plan occurs or an error encountered, Terraform will fail the test.
> fix(kafka_topic): remove expect non empty diff in test

- CHANGELOG.md
- internal/sdkprovider/service/account/account_team_member.go
no err on `aiven_account_team_member` deletion if it does not exist
to avoid edge cases, e.g. invitations
> fix(account_team_member): no err on deletion if it does not exist

- .github/workflows/acceptance-tests.yml
- .github/workflows/examples-tests.yml
- .github/workflows/sweep.yml
- tools/selproj/README.md
- tools/selproj/main.go
- tools/selproj/selectproject.go
- tools/selproj/selectproject_test.go
- proper project name prefix var substitution.
- additionally adds support for `sweep.yml` (forgot to do this earlier)
resolves CI error https://github.com/aiven/terraform-provider-aiven/actions/runs/7247944868/job/19742908213
> ci(test): proper project name prefix var substitution

- CHANGELOG.md
- internal/schemautil/service.go
fix migration issues from v3 to v4 related to cloud_name diff
> fix(service): v3 to v4 migration cloud_name field

- CHANGELOG.md
- internal/sdkprovider/kafkatopicrepository/create.go
Actually fixes "insufficient brokers error".
> fix(kafka_topic): insufficient brokers error

- CHANGELOG.md
- docs/resources/kafka_topic.md
- go.mod
- go.sum
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
temporarily disable `local_retention_*` fields in `aiven_kafka_topic` resource
hotfix, there's a bug and it looks quite complex
> fix(kafkatopic): temporarily disable local_retention_* fields

- internal/sdkprovider/service/connectionpool/sweep.go
> feat(sweep): connection pool support

- internal/acctest/acctest.go
- internal/plugin/provider.go
- internal/plugin/service/organization/organization_application_user_test.go
- internal/plugin/service/organization/organization_group_project_test.go
- internal/plugin/service/organization/organization_user_group_member_test.go
- internal/plugin/util/helpers.go
- deduplicate beta checks in codebase
- drop unnecessary period from error messages
good stuff
> refactor: deduplicate beta checks

- internal/acctest/acctest.go
- internal/plugin/service/organization/organization_application_user_test.go
- internal/plugin/service/organization/organization_group_project_test.go
- internal/plugin/service/organization/organization_user_group_member_test.go
skip option support for `acctest`
makes code cleaner
> refactor(acctest): skip option support

- docs/data-sources/organization_user_group.md
- docs/resources/organization_group_project.md
- docs/resources/organization_user_group.md
- docs/resources/organization_user_group_member.md
- internal/plugin/service/organization/organization_group_project.go
- internal/plugin/service/organization/organization_user_group_member.go
- internal/sdkprovider/service/organization/organization_user_group.go
- internal/sdkprovider/service/organization/organization_user_group_data_source.go
Small changes to the descriptions for the resources and data source for user groups for clarity.
> docs: rewrite descriptions for groups resources

- internal/sdkprovider/service/vpc/project_vpc_test.go
- tools/selproj/client.go
- tools/selproj/mock_client.go
- tools/selproj/selectproject.go
- tools/selproj/selectproject_test.go
Fixes VPC cloud name conflict in tests.
> chore(vpc): fix tests conflict

- internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
User story test case doesn't have `local_retention_bytes` value.
This PR just proves user case is covered.
> chore(kafka_topic): improve config zero-value test

- Makefile
- internal/schemautil/database.go
- internal/schemautil/service_user.go
- internal/schemautil/wait.go
- internal/sdkprovider/service/organization/organization_user_data_source.go
- internal/sdkprovider/service/organization/sweep.go
> chore(imports): improve regexp

- .github/workflows/lint.yml
- Makefile
- internal/sdkprovider/service/account/sweep.go
- internal/sdkprovider/service/connectionpool/sweep.go
- internal/sdkprovider/service/organization/sweep.go
- internal/sdkprovider/service/project/sweep.go
- internal/sdkprovider/service/serviceintegration/sweep.go
- internal/sdkprovider/service/staticip/sweep.go
- internal/sdkprovider/service/vpc/sweep.go
- internal/sweep/sweep.go
- internal/sweep/sweep_test.go
> ci: add sweep check

- CHANGELOG.md
- internal/sdkprovider/service/flink/flink.go
Add Flink service deletion check, it is impossible to delete a Flink service if we have active Deployments with Jobs that are managed outside of Terraform via Web UI. Expectation is that users clean up all the running Jobs via Web UI and remove all deployments prior to deletion of Flink service.
> feat(flink): add pre deletion check

- CHANGELOG.md
- docs/resources/flink_application_version.md
- examples/resources/aiven_flink_application_version/resource.tf
- Fix extraneous quotation marks
- Remove references to deprecated schema values and use current ones instead (`sinks` and `sources` -> `sink` and `source`)
We shouldn't display invalid code in our examples
> docs: update flink_application_version docs

- .golangci.yml
- internal/schemautil/common.go
- internal/schemautil/service.go
- internal/schemautil/userconfig/util.go
- internal/sdkprovider/service/flink/flink_application_version.go
- internal/sdkprovider/service/kafka/kafka_connector.go
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
- internal/sdkprovider/service/project/project.go
- internal/sdkprovider/service/vpc/aws_privatelink.go
- internal/sdkprovider/service/vpc/azure_privatelink.go
Add https://github.com/alexkohler/prealloc to find slice declarations
that could potentially be pre-allocated and address linter errors.
This is partial implementation of #858.
`make` + assign pattern was used in codebase already and it works faster than `append`.
> ci(lint): add prealloc

- docs/resources/organization_user.md
- internal/sdkprovider/service/organization/organization_user.go
Make the deprecation warning for `aiven_organization_user` more obvious.
> docs: make deprecation warning bold

- CHANGELOG.md
- docs/resources/organization_user_group.md
- internal/sdkprovider/service/organization/organization_user_group.go
Marks the description field for user groups as required.
> fix(organization_user_group): make description field required

- CHANGELOG.md
- CONTRIBUTING.md
- go.mod
- tools/go.mod
- tools/selproj/go.mod
Use the latest version of golang.
Go 1.22 brings performance improvements, see: https://go.dev/blog/go1.22
> chore(go): upgrade go 1.22

- CHANGELOG.md
- internal/schemautil/database.go
- internal/schemautil/wait.go
- internal/sdkprovider/service/flink/flink_application_deployment.go
- internal/sdkprovider/service/influxdb/influxdb_database.go
- internal/sdkprovider/service/kafka/kafka_connector.go
- internal/sdkprovider/service/mysql/mysql_database.go
- internal/sdkprovider/service/pg/pg.go
- internal/sdkprovider/service/pg/pg_database.go
- internal/sdkprovider/service/project/project.go
- internal/sdkprovider/service/serviceintegration/service_integration.go
- internal/sdkprovider/service/staticip/static_ip.go
- internal/sdkprovider/service/vpc/aws_privatelink.go
- internal/sdkprovider/service/vpc/aws_vpc_peering_connection.go
- internal/sdkprovider/service/vpc/azure_privatelink.go
- internal/sdkprovider/service/vpc/azure_privatelink_connection_approve.go
- internal/sdkprovider/service/vpc/azure_vpc_peering_connection.go
- internal/sdkprovider/service/vpc/gcp_privatelink.go
- internal/sdkprovider/service/vpc/gcp_privatelink_connection_approve.go
- internal/sdkprovider/service/vpc/gcp_vpc_peering_connection.go
- internal/sdkprovider/service/vpc/project_vpc.go
- internal/sdkprovider/service/vpc/vpc_peering_connection.go
github.com/hashicorp/terraform-plugin-testing/helper/resource is deprecated, and it was recommend that github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry be used instead.
Resolves: #xxxxx.
To eliminate the use of deprecated APIs
> refactor: use v2/helpers/retry instead of helper/resource

- CHANGELOG.md
- internal/schemautil/service.go
When `termination_protection = true` is removed the diff shows `true -> null`, and sends zero-value, which is `false` [service.go](https://github.com/aiven/terraform-provider-aiven/blob/d6b602b6e1f136ead0e9a385e23c9e59f99f5b0d/internal/schemautil/service.go#L547-L547).
This PR outputs `true -> false` transition, because explicit is better than implicit.
> fix: termination_protection diff `true -> null`

- CHANGELOG.md
- internal/sdkprovider/service/kafkaschema/kafka_schema.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_test.go
Fixes version issues for `aiven_kafka_schema`:
1. When a `aiven_kafka_schema` is updated it doesn't necessarily get the latest _version_.
Instead, if it just reverts to a previous state it get's an existing _version_.
Takes schema ID from "update" response and fetches the valid _version_.
2. Version list is not updated instantly, there is a tiny lag. Polls until finds the given schema ID from the "update" response. This case is flaky, hence it can't be covered in tests.
Resolves #1608.
> fix(aiven_kafka_schema): update schema version

- docs/resources/flink_application_version.md
- docs/resources/kafka_schema.md
- examples/flink/main.tf
- examples/kafka_schemas/kafka_schema.tf
- examples/resources/aiven_flink_application_version/resource.tf
- examples/resources/aiven_kafka_schema/resource.tf
- internal/sdkprovider/service/flink/flink_application_version_test.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_test.go
- fixes incorrect sql in `aiven_flink_application_version` resource's test, which resulted the job being in infinite `RESTARTING` state right after its creation
- fixes heredoc formatting in all docs and tests
- sql should be correct in the test to reduce the load the test generates on the service
- maintainers should later decide whether this is incorrect to report success on creation of such job or not
- heredoc formatting was broken
> test(flink_application_version): fix incorrect sql

- docs/resources/account.md
- docs/resources/account_authentication.md
- internal/sdkprovider/service/account/account.go
- internal/sdkprovider/service/account/account_authentication.go
Add notice in the docs that `account` and `account_authentication` have been deprecated.
> docs: add deprecation notice to account and authentication resources

- CHANGELOG.md
- internal/sdkprovider/userconfig/converters/converters.go
improves the `ip_filter` safeguard, adds some docs about it
it's simply better
> chore(userconfig/converters): improve ip_filter safeguard

- internal/sdkprovider/userconfig/converters/converters.go
there's a missing negation in the `ip_filter` safeguard, this PR brings it
it was missing 🤷
> fix(userconfig/converters): missing negation in ip_filter safeguard

- docs/resources/organization_application_user.md
- docs/resources/organization_application_user_token.md
- docs/resources/organization_group_project.md
- docs/resources/organization_user_group_member.md
- internal/plugin/service/organization/organization_application_user.go
- internal/plugin/service/organization/organization_application_user_token.go
- internal/plugin/service/organization/organization_group_project.go
- internal/plugin/service/organization/organization_user_group_member.go
- internal/schemautil/userconfig/desc.go
- internal/sdkprovider/service/organization/organization_user_data_source.go
- adds entity and availability types to the description builder
- removes the `BetaDescription` helper that we used previously
- adjusts old resources/datasources for the new implementation
this could be useful for optimizing the resources and effort that we need to make the docs
> feat(userconfig/desc): add entity and availability types

- CHANGELOG.md
- docs/resources/mirrormaker_replication_flow.md
- go.mod
- go.sum
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
Fix incorrect behavior of `aiven_mirrormaker_replication_flow` schema fields:
- `sync_group_offsets_enabled`
- `sync_group_offsets_interval_seconds`
- `emit_heartbeats_enabled`
- `emit_backward_heartbeats_enabled`
- `offset_syncs_topic_location`
- `replication_policy_class`
Resolves: #1632.
The current way it works is broken. Additionally, `offset_syncs_topic_location` and `replication_policy_class` should be required, because they can't be empty, and API then converts an empty string to their default values, `source` and `org.apache.kafka.connect.mirror.DefaultReplicationPolicy` respectively.
> fix(mirrormaker_replication_flow): incorrect behavior of schema fields

- CHANGELOG.md
- internal/schemautil/service.go
- internal/sdkprovider/service/cassandra/cassandra.go
- internal/sdkprovider/service/clickhouse/clickhouse.go
- internal/sdkprovider/service/dragonfly/dragonfly.go
- internal/sdkprovider/service/flink/flink.go
- internal/sdkprovider/service/grafana/grafana.go
- internal/sdkprovider/service/influxdb/influxdb.go
- internal/sdkprovider/service/kafka/kafka.go
- internal/sdkprovider/service/kafka/kafka_connect.go
- internal/sdkprovider/service/kafka/kafka_mirrormaker.go
- internal/sdkprovider/service/m3db/m3aggregator.go
- internal/sdkprovider/service/m3db/m3db.go
- internal/sdkprovider/service/mysql/mysql.go
- internal/sdkprovider/service/opensearch/opensearch.go
- internal/sdkprovider/service/pg/pg.go
- internal/sdkprovider/service/redis/redis.go
- internal/sdkprovider/service/serviceintegration/service_integration.go
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint_test.go
- internal/sdkprovider/userconfig/converters/converters.go
This PR covers two related to the issue bugs:
- user config field required for `aiven_service_integration_endpoint`
- the `external_postgresql` doesn't have `_user_config` suffix, which was expected in a few cases. The field name generation is now managed by a single source of truth
Resolves #1589
> fix(aiven_service_integration_endpoint): can't create external_postgresql

- internal/sdkprovider/service/serviceintegration/service_integration.go
- internal/sdkprovider/userconfig/converters/converters.go
- internal/sdkprovider/userconfig/service/service.go
- internal/sdkprovider/userconfig/serviceintegration/serviceintegration.go
- internal/sdkprovider/userconfig/serviceintegrationendpoint/serviceintegrationendpoint.go
- main.go
- ucgenerator/main.go
- replaces old converter in service integration update handler
- the check if resource has a user config is moved to the converter to encapsulate the logic further
> refactor: encapsulate user config checks

- CHANGELOG.md
- docs/resources/organization_group_project.md
- docs/resources/organization_user_group_member.md
- internal/plugin/provider.go
- internal/plugin/service/organization/organization_group_project.go
- internal/plugin/service/organization/organization_user_group_member.go
Removes the beta flag for `aiven_organization_user_group_member` and `aiven_organization_group_project`
> refactor: mark user_group_member and group_project as ga

- .goreleaser.yml
fixes incorrect reference to `version` variable of the `main` package in `ldflags` of `.goreleaser.yml` config file
to have proper version in the `User-Agent`
> ci(release-artifacts): incorrect reference in ldflags

- .github/workflows/incremental-acceptance-tests.yml
- adds sweeping functionality to `incacctests` workflow
- some small fixes
to prevent dangling resources from appearing
> ci(incacctests): add sweeping functionality

- docs/data-sources/mirrormaker_replication_flow.md
- docs/resources/mirrormaker_replication_flow.md
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
offset_syncs_topic_location takes a string of "source" or "target" but the docs did not reflect that. The config also lacks a default and that was not captured. This adds the valid options and the lack of a default
offset_syncs_topic_location takes a string of "source" or "target" but the docs did not reflect that. The config also lacks a default and that was not captured. This adds the valid options and the lack of a default
Based on the other configs, this is the approach that is used to document.
> docs(mirromaker): added valid options for config

- CHANGELOG.md
- internal/sdkprovider/userconfig/converters/converters.go
- internal/sdkprovider/userconfig/converters/converters_test.go
- internal/sdkprovider/userconfig/converters/utils.go
When `ip_filter` object list is converted into string list, and there is no specific `ip_filter` entries in the config, it crashes with type conversion `interface {} is []string, not []interface {}` because `convertIPFilter` sets `[]string`.
- improves error messages
- adds explicit casting
- fixes `ip_filter` type conversion
- adds integration tests
Resolves #1734
> fix: ip_filter conversion issue

- .github/workflows/release-artifacts.yml
- .goreleaser.yml
The release workflow printed deprecation warnings.
* --rm-dist: https://goreleaser.com/deprecations/#__tabbed_17_1
* changelog.skip: https://goreleaser.com/deprecations/#changelogskip
Example: https://github.com/aiven/terraform-provider-aiven/actions/runs/9268626143/job/25497661979
> chore(ci): remove deprecated gorelease args and options

- examples/clickhouse/services.tf
- examples/clickhouse_integrations/kafka_source/access.tf
PR #1331 added instructions on granting privileges on all tables in a database. This commit aligns the examples with the docs.
> docs(clickhouse): update clickhouse examples to align with docs

- CHANGELOG.md
- docs/resources/organization_user_group.md
- internal/sdkprovider/service/organization/organization_user_group.go
Marks the `name` field as required for the user group resource.
> fix(organization_user_group): make name field required

- CHANGELOG.md
- docs/data-sources/transit_gateway_vpc_attachment.md
- docs/resources/transit_gateway_vpc_attachment.md
- internal/sdkprovider/service/vpc/transit_gateway_vpc_attachment.go
The field has been mistakenly deprecated in #1204.
Marks `peer_region` as create only, removes deprecation.
Resolves #1751
> fix(aiven_transit_gateway_vpc_attachment): remove peer_region deprecation

- docs/resources/organization_application_user.md
- docs/resources/organization_application_user_token.md
- docs/resources/organization_group_project.md
- docs/resources/organization_user_group_member.md
- internal/plugin/service/organization/organization_group_project.go
- internal/plugin/service/organization/organization_user_group_member.go
- internal/sdkprovider/service/organization/organization_application_user.go
- internal/sdkprovider/service/organization/organization_application_user_token.go
Adds more information on how application users and their tokens work and how they can be assigned to groups. Clarifies the roles available for projects.
> docs: improve documentation for application users, tokens, and groups

- docs/resources/account_team.md
- docs/resources/account_team_member.md
- docs/resources/account_team_project.md
- internal/sdkprovider/service/account/account_team.go
- internal/sdkprovider/service/account/account_team_member.go
- internal/sdkprovider/service/account/account_team_project.go
- templates/resources/account_team.md.tmpl
- templates/resources/account_team_member.md.tmpl
- templates/resources/account_team_project.md.tmpl
Changes the date for the Account Owners team removal and updates the deprecation notice for the teams resources.
Adds warning about the effects of deleting all teams.
> docs: fix deprecation info for teams resources

- docs/resources/clickhouse_grant.md
- internal/sdkprovider/service/clickhouse/clickhouse_grant.go
CREATE is not a valid option for ClickHouse grants. This replaces that
example in the docs with CREATE TABLE and fixes
formatting of the other example values.
> docs(clickhouse): fix grant example

- internal/plugin/util/pluginhelpers.go
- internal/sdkprovider/provider/provider.go
Removes resources marked as Beta when env flag is missing.
Doesn't require a dedicated list of resources.
> refactor: manage beta resources automatically

- CHANGELOG.md
- internal/sdkprovider/service/project/project_user.go
The resource was deprecated prematurely.
> feat(project_user): remove deprecation

- docs/resources/kafka_schema_registry_acl.md
- examples/resources/aiven_kafka_schema_registry_acl/import.sh
The import command required ACL id [kafka_schema_registry_acl.go](https://github.com/aiven/terraform-provider-aiven/blob/0f362d6e368f07b65c5abdfa34b3c64bb61192bb/internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl.go#L91-L91)
> docs(aiven_kafka_schema_registry_acl): fix import

- CHANGELOG.md
- internal/sdkprovider/service/kafkaschema/kafka_schema.go
Doesn't throw "not found"; instead, acts like the source never existed.
> fix(aiven_kafka_schema): create missing schema

- internal/common/client.go
- internal/sdkprovider/service/kafka/kafka_mirrormaker_replication_flow_data_source.go
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
- internal/sdkprovider/service/organization/organization_application_user.go
- internal/sdkprovider/service/organization/organization_application_user_data_source.go
- internal/sdkprovider/service/organization/organization_application_user_token.go
- internal/sdkprovider/service/valkey/valkey_user.go
- internal/sdkprovider/service/valkey/valkey_user_data_source.go
Returns a plain error in functions wrapped with `WithGenClient`.
This way it is cleaner and easier to code.
> refactor: return plain error

- examples_tests/base.go
- internal/acctest/acctest.go
- internal/common/client.go
- internal/common/client_test.go
- internal/plugin/provider.go
- internal/schemautil/common.go
- internal/sdkprovider/provider/provider.go
There are multiple places where we use old client (plugin, sdkv2, tests), and multiple constructors to build it. That adds unnecessary complexity, and complicates the new client integration.
- Replaces multiple client constructors with a single approach
- Unifies old and new client configuration
> refactor: unify clients configuration

- examples/get-started/README.md
- examples/get-started/get-started.tf
Adds prerequisites for adding users to example for setting up user groups.
> docs: update get started example

- internal/schemautil/service.go
- internal/schemautil/service_test.go
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
Checks GET response doesn't contain `<redacted>` substring.
> feat: check user config for redacted creds

- go.mod
- go.sum
- internal/sdkprovider/service/serviceintegration/service_integration.go
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
Uses upcoming changes https://github.com/aiven/go-client-codegen/pull/131
> chore: use service module from the gen client

- CHANGELOG.md
- docs/data-sources/kafka_topic.md
- docs/resources/kafka_topic.md
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
Add capability to set description and owner group per topic.
topic description and owner user group are now supported per topic in aiven API's. Both fields are optional. Especially the owner group field will provide basic governing functionality by being able to mark owner to a topic. 
Worth mentioning is that due to how the Aiven topic update endpoint works (fields are reset by sending the field as null to the endpoint) it is not possible to remove the field from config to unset it. In order to unset one of these fields, `terraform destroy` and `terraform apply` must be done in order to completely unset these fields.
> feat: add support for topic description and ownership

- CHANGELOG.md
- docs/data-sources/valkey.md
- docs/data-sources/valkey_user.md
- docs/resources/valkey.md
- docs/resources/valkey_user.md
- internal/sdkprovider/provider/provider.go
Promote `aiven_valkey` and `aiven_valkey_user` resources / data sources out of beta.
> feat: promote aiven_valkey and aiven_valkey_user out of beta

- .goreleaser.yml
* Adds `version` field to goreleaser config file
* Adds `yaml-language-server` as instructed in https://goreleaser.com/customization/
Fixes the following warning printed on the release GHA:
> fix: add version to .goreleaser.yml

- CHANGELOG.md
- docs/data-sources/thanos.md
- docs/resources/thanos.md
- internal/sdkprovider/provider/provider.go
Promotes `aiven_thanos` to GA
Aiven Thanos is now GA
> feat: remove `aiven_thanos` from beta resources

- docs/data-sources/kafka_topic.md
- docs/resources/kafka_topic.md
- examples/resources/aiven_kafka_topic/resource.tf
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
Updates the description of for the `owner_user_group_id` field to provide more information and link to governance conceptual docs.
> docs(kafka): update description for topic owner group

- CHANGELOG.md
- internal/sdkprovider/service/project/project.go
- internal/sdkprovider/service/project/project_test.go
Diff suppressors made impossible to migrate to `parent_id` field.
> fix(aiven_project): account_id -> parent_id transition

- docs/guides/update-deprecated-resources.md
- docs/resources/organization_group_project.md
- docs/resources/organization_permission.md
- docs/resources/project_user.md
- internal/plugin/service/organization/organization_group_project.go
- internal/sdkprovider/provider/provider.go
- internal/sdkprovider/service/project/project_user.go
- templates/guides/update-deprecated-resources.md
Adds deprecation notices to the `aiven_project_user` and `aiven_organization_group_project` resources. Consolidates existing migration guides into one and adds instructions for migrating these deprecated resources to `aiven_organization_permission`.
> docs: add instructions for updating deprecated resources

- internal/sdkprovider/service/servicecomponent/service_component_data_source_test.go
The test flow:
1. It creates a kafka service, runs checks
2. Destroys it, the code makes sure `ServiceGet` returns `NotFound` to prove it is destroyed
3. Creates another kafka with the very same name, but gets `[409 ServiceCreate]: Service name is already in use in this project`
Looks like it takes a bit longer now to destroy a service for real.
The fix reuses kafka from the step 1) updating it in 3).
> test: fix aiven_service_component race

- docs/resources/organization_permission.md
- examples/resources/aiven_organization_permission/resource.tf
- internal/sdkprovider/service/organization/organization_permission.go
Adds language that clarify that the permissions resource grants both roles and permissions. Improves the example usage to show that multiple roles and permissions can be granted to a principal.
> docs: improve permissions documentation

- docs/resources/organization_permission.md
- examples/resources/aiven_organization_permission/resource.tf
Fixes the example usage to include adding both a user as well as a group with multiple permissions to the same project.
> docs: combine examples into one for permissions

- .github/workflows/update-schemas.yml
- Makefile
- changelog/formatter.go
- changelog/formatter_test.go
git diff exposes all the changes.
> fix(update-schemas): commit message description

- examples/clickhouse/services.tf
Fixes the references to the project resource in the ClickHouse example.
> fix: clickhouse example

- docs/resources/organization_user.md
- internal/sdkprovider/service/organization/organization_user.go
Replaces the references to the group_project resource in the deprecation notices for the organization_user resource with the new permission resource as group_project is also deprecated now.
> docs: point to new permission resource instead of group_project

- CHANGELOG.md
- docs/data-sources/mirrormaker_replication_flow.md
- docs/resources/mirrormaker_replication_flow.md
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow_test.go
We update the `aivenMirrorMakerReplicationFlowSchema` with `exactly_once_delivery_enabled` config flag so users can toggle the exactly once message delivery semantics.
> feat: MM2 exactly-once delivery

- internal/sdkprovider/service/serviceintegration/service_integration.go
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint_test.go
- internal/sdkprovider/service/serviceintegration/sweep.go
There was `IsNotFound` usage from v2 client, which doesn't work with gen client errors.
> fix(service_integration): remove v2 client checks

- Makefile
- internal/sdkprovider/service/organization/organization_user_group_data_source.go
The current command looks for `'s/"[\r\n\t]\+"/"\n"/g'`— newlines and tabs before `"`.
Hence, fails to sort lines with aliases: `\n\tmymodule"`.
> fix: make fmt-imports

- internal/sdkprovider/service/organization/organization_user.go
- internal/sdkprovider/service/organization/organization_user_data_source.go
- internal/sdkprovider/service/organization/organization_user_data_source_test.go
- internal/sdkprovider/service/organization/organization_user_test.go
Replaced aiven-go-client with avngen in OrganizationUser resource
> refactor(organization_user): replaced client-v2 with avngen

- CHANGELOG.md
- docs/data-sources/service_integration.md
- docs/resources/service_integration.md
- internal/sdkprovider/service/serviceintegration/service_integration.go
- internal/sdkprovider/service/serviceintegration/service_integration_test.go
- Add `aiven_service_integration` resource field `destination_service_project`: Destination service project name
- Add `aiven_service_integration` resource field `source_service_project`: Source service project name
- Add `aiven_service_integration` datasource field `destination_service_project`: Destination service project name
- Add `aiven_service_integration` datasource field `source_service_project`: Source service project name
> feat(service_integration): add source and destination project names

- CHANGELOG.md
- changelog/differ.go
- changelog/differ_test.go
- changelog/main.go
- changelog/text.go
- changelog/types.go
- docs/data-sources/alloydbomni.md
- docs/data-sources/pg.md
- docs/resources/alloydbomni.md
- docs/resources/pg.md
- go.mod
- go.sum
- internal/sdkprovider/userconfig/service/alloydbomni.go
- internal/sdkprovider/userconfig/service/pg.go
- Fixes enums in the changlog for user config fields
- Groups similar changes for resources and datasources
- Updates schemas and the client (the most of the diff)
> fix: changelog doesn't show diff for user config enums

- docs/resources/organization_permission.md
- examples/resources/aiven_organization_permission/resource.tf
- internal/sdkprovider/service/organization/organization_permission.go
Adds examples of permissions at project and org level.
> docs: add org level permissions example

- docs/guides/update-deprecated-resources.md
- templates/guides/update-deprecated-resources.md
Fixes a misspelling in the guide for updating deprecated resources.
> docs: fix typo in guide

- .golangci.yml
- internal/sdkprovider/service/account/account_team.go
- internal/sdkprovider/service/account/account_team_data_source.go
- internal/sdkprovider/service/account/account_team_test.go
- replaced `client-v2` with `avngen` in `account_team` resource
> refactor(account_team): replaced client-v2 with avngen

- internal/sdkprovider/service/account/account_team_project.go
- internal/sdkprovider/service/account/account_team_project_data_source.go
- internal/sdkprovider/service/account/account_team_project_test.go
- replaced `client-v2 `with `avngen` in `account_team_project` resource
> refactor(account_team_project): replaced client-v2 with avngen

- internal/plugin/util/helpers.go
- internal/sdkprovider/service/account/account.go
- internal/sdkprovider/service/account/account_authentication.go
- internal/sdkprovider/service/kafka/kafka_quota.go
- internal/sdkprovider/service/kafka/kafka_quota_test.go
- changed `request_percentage` field to float type in `kafka_quota` resource
> feat(kafka_quota): changed request_percentage field to float type

- CHANGELOG.md
- internal/common/client.go
- internal/schemautil/service_user.go
- internal/sdkprovider/service/alloydbomni/alloydbomni_user.go
- internal/sdkprovider/service/alloydbomni/alloydbomni_user_data_source.go
- internal/sdkprovider/service/cassandra/cassandra_user.go
- internal/sdkprovider/service/influxdb/influxdb_user.go
- internal/sdkprovider/service/kafka/kafka_user.go
- internal/sdkprovider/service/m3db/m3db_user.go
- internal/sdkprovider/service/mysql/mysql_user.go
- internal/sdkprovider/service/pg/pg_user.go
- internal/sdkprovider/service/pg/pg_user_data_source.go
- internal/sdkprovider/service/redis/redis_user.go
- internal/sdkprovider/service/valkey/valkey_user.go
> refactor(alloydbomni_user): use pg_user handlers and schema

- CHANGELOG.md
- internal/common/client.go
- internal/schemautil/helpers.go
- internal/schemautil/service_user.go
- internal/schemautil/wait.go
- internal/sdkprovider/service/pg/pg_user.go
There is a lag between `ServiceUserCreate` and `ServiceUserCredentialsModify` changes take affect, and `ServiceUserGet` might get the outdated state.
Adds a waiter to make sure certain fields are updated.
> fix: service user update lag

- Makefile
Resolves the [dependency](https://github.com/aiven/terraform-provider-aiven/actions/runs/12901573049/job/35973859503#step:5:459).
> fix: missing mockery tool

- CHANGELOG.md
- internal/sdkprovider/service/grafana/grafana_test.go
Fix: services always created in the default VPC of the same cloud, 
when `project_vpc_id` wasn't set.
1. Uses [updated client](https://github.com/aiven/go-client-codegen/pull/227) that can send `nil` value in `project_vpc_id` (the client updated in this [PR](https://github.com/aiven/terraform-provider-aiven/pull/2009))
1. Adds a test
**Doesn't fix:** resetting `project_vpc_id` was never possible.
> fix: services always created in the default VPC

- docs/data-sources/kafka_mirrormaker.md
- docs/data-sources/mirrormaker_replication_flow.md
- docs/resources/kafka_mirrormaker.md
- docs/resources/mirrormaker_replication_flow.md
- examples/data-sources/aiven_kafka_mirrormaker/data-source.tf
- examples/data-sources/aiven_mirrormaker_replication_flow/data-source.tf
- examples/resources/aiven_kafka_mirrormaker/import.sh
- examples/resources/aiven_kafka_mirrormaker/resource.tf
- examples/resources/aiven_mirrormaker_replication_flow/import.sh
- examples/resources/aiven_mirrormaker_replication_flow/resource.tf
- internal/sdkprovider/service/kafka/kafka_mirrormaker.go
- internal/sdkprovider/service/kafka/kafka_mirrormaker_data_source.go
- internal/sdkprovider/service/kafka/kafka_mirrormaker_replication_flow_data_source.go
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
Improvements for docs for Mirrormaker resources and data sources.
> docs: update mirrormaker documentation

- CHANGELOG.md
- internal/sdkprovider/service/project/project_user.go
- internal/sdkprovider/service/project/project_user_data_source.go
- internal/sdkprovider/service/project/project_user_test.go
- replaced `client-v2` with `avngen` in `project_user` resource
> refactor(project_user): replaced client-v2 with avngen

- .github/workflows/acceptance-tests.yml
Fixes `Cannot open: File exists` error in [acceptance tests](https://github.com/aiven/terraform-provider-aiven/actions/runs/13000813509/job/36258930620#step:5:27).
Caching action is already used by [`actions/setup.go`](https://github.com/actions/setup-go/blob/5a083d0e9a84784eb32078397cf5459adecb4c40/package.json#L28).
So we don't need to use [`actions/cache`](https://github.com/orgs/community/discussions/58174#discussioncomment-7627691).
Additionally, sets `ACC_TEST_PARALLELISM=5` to reduce concurrency errors.
> ci: remove caching action

- CHANGELOG.md
- internal/schemautil/helpers.go
- internal/schemautil/wait.go
- internal/sdkprovider/service/grafana/grafana_test.go
- internal/sdkprovider/service/kafka/kafka_test.go
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow_test.go
- internal/sdkprovider/service/kafka/mirrormaker_test.go
- internal/sdkprovider/service/m3db/m3db_test.go
- internal/sdkprovider/service/organization/organization_user_group_test.go
- internal/sdkprovider/userconfig/converters/utils_test.go
- internal/sdkprovider/userconfig/diff/diff.go
- internal/sdkprovider/userconfig/diff/diff_test.go
New services get new default value for the `ip_filter` field: `["0.0.0.0/0", "::/0"]`.
- Suppresses `"::/0"` for the new services.
- Remove redundant (skipped) test
- Adds more `ip_filter` tests
- Improves Grafana waiter. Adds `ip_filter` object type support.
> fix(ip_filter): suppress ipv6 default value

- docs/data-sources/mysql.md
- docs/data-sources/mysql_database.md
- docs/data-sources/mysql_user.md
- docs/resources/mysql.md
- docs/resources/mysql_database.md
- docs/resources/mysql_user.md
- examples/data-sources/aiven_mysql/data-source.tf
- examples/data-sources/aiven_mysql_database/data-source.tf
- examples/data-sources/aiven_mysql_user/data-source.tf
- examples/resources/aiven_mysql/import.sh
- examples/resources/aiven_mysql/resource.tf
- examples/resources/aiven_mysql_database/import.sh
- examples/resources/aiven_mysql_database/resource.tf
- examples/resources/aiven_mysql_user/resource.tf
- internal/sdkprovider/service/mysql/mysql.go
- internal/sdkprovider/service/mysql/mysql_data_source.go
- internal/sdkprovider/service/mysql/mysql_database.go
- internal/sdkprovider/service/mysql/mysql_database_data_source.go
- internal/sdkprovider/service/mysql/mysql_user.go
- internal/sdkprovider/service/mysql/mysql_user_data_source.go
Docs updates for MySQL resources and data sources.
> docs: update descriptions for mysql resources and data sources

- docs/data-sources/account.md
- docs/data-sources/account_authentication.md
- docs/data-sources/organization_user.md
- docs/data-sources/project_user.md
- docs/resources/account.md
- docs/resources/account_authentication.md
- docs/resources/organization_user.md
- docs/resources/project_user.md
- internal/sdkprovider/provider/provider.go
- internal/sdkprovider/service/organization/organization_user.go
- internal/sdkprovider/service/project/project_user.go
Removes one line break to fix the formatting since callouts don't support multiple paragraphs. 
With just one line break:
Also removes a couple of duplicate deprecation notices.
> fix: formatting for deprecation callouts

- internal/sdkprovider/service/project/organization_project_test.go
- fixed a test for `aiven_organization_project`. The backend does not accept the `billing_group_id` which does not belong directly to this organization
> fix(aiven_organization_project): fixed test

- internal/sdkprovider/provider/provider.go
- internal/sdkprovider/service/organization/organization_project.go
- internal/sdkprovider/service/organization/organization_project_data_source.go
- internal/sdkprovider/service/organization/organization_project_test.go
Moves `aiven_organization_project` to the organization module where it belongs to.
> refactor(organization_project): move to organization module

- docs/data-sources/billing_group.md
- examples/data-sources/aiven_billing_group/data-source.tf
- internal/sdkprovider/service/project/billing_group_data_source.go
Fixes the example usage for billing group data sources to use the ID instead of the name. Adds a link to instructions on how to get the billing group ID from the Console.
> docs: fix example usage for billing group data source

- internal/plugin/errmsg/errmsg.go
- internal/plugin/util/diag.go
- internal/plugin/util/helpers.go
- internal/schemautil/userconfig/desc.go
Removes dead code using https://pkg.go.dev/golang.org/x/tools/internal/cmd/deadcode.
```bash
$ deadcode -f='{{range .Funcs}}{{println .Position}}{{end}}' -test ./internal/...
internal/acctest/acctest.go:272:6
internal/acctest/template.go:103:28
internal/acctest/template.go:111:28
internal/acctest/template.go:117:28
internal/acctest/template.go:162:30
internal/acctest/template.go:179:30
internal/plugin/util/diag.go:80:6
internal/plugin/util/helpers.go:29:6
internal/plugin/util/helpers.go:34:6
internal/schemautil/userconfig/desc.go:81:31
```
Code in `template.go` is left as-is.
> chore: remove dead code

- internal/sdkprovider/service/redis/redis_test.go
- internal/sdkprovider/service/redis/redis_user_test.go
- skip tests for `redis` resource due to the deprecation
> chore(redis): skip redis tests

- docs/data-sources/project_user.md
- docs/resources/organization_group_project.md
- docs/resources/organization_permission.md
- docs/resources/project_user.md
- internal/plugin/service/organization/organization_group_project.go
- internal/sdkprovider/service/organization/organization_permission.go
- internal/sdkprovider/service/project/project_user.go
Adds a warning to not use the `aiven_project_user` and `aiven_organization_group_project` resources together with the `aiven_organization_permission` resource.
> docs: add warning to project user and group project resources

- CHANGELOG.md
- internal/acctest/template/store_test.go
- internal/schemautil/schemautil.go
- internal/schemautil/schemautil_test.go
- internal/sdkprovider/service/account/account.go
- internal/sdkprovider/service/account/account_team.go
- internal/sdkprovider/service/account/account_team_member.go
- internal/sdkprovider/service/alloydbomni/alloydbomni_database.go
- internal/sdkprovider/service/flink/flink_jar_application.go
- internal/sdkprovider/service/flink/flink_jar_application_deployment.go
- internal/sdkprovider/service/flink/flink_jar_application_version.go
- internal/sdkprovider/service/kafka/kafka_native_acl.go
- internal/sdkprovider/service/kafka/kafka_quota.go
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
- internal/sdkprovider/service/organization/organization_application_user.go
- internal/sdkprovider/service/organization/organization_application_user_token.go
- internal/sdkprovider/service/organization/organization_user_group.go
- internal/sdkprovider/service/organization/organization_user_list_data_source.go
- internal/sdkprovider/service/organization/organizational_unit.go
- internal/sdkprovider/service/pg/pg_user.go
- internal/sdkprovider/service/pg/pg_user_retries_test.go
- internal/sdkprovider/service/pg/pg_user_test.go
When ForceNew field not in the DTO, terraform fails to import the resource.
Fixes #2065
> fix: set ForceNew fields, that are not in the DTO

- CHANGELOG.md
- internal/sdkprovider/service/organization/organization_application_user.go
Currently there is an issue with the API that returns 400 on the first delete request.
> fix(organization_application_user): retry delete

- CHANGELOG.md
- internal/acctest/template/store_test.go
- internal/plugin/service/organization/org/organization_data_source_test.go
- internal/sdkprovider/service/kafka/kafka_native_acl.go
- internal/sdkprovider/service/kafka/kafka_native_acl_test.go
host will get default value of * from Aiven API
if not provided. To reflect this to the schemas,
the field can be marked as computed. In addition,
document the default value.
Resolves: #2124
> patch: kafka-native-acl host field

- examples/kafka_connect/kafka_connect_service.tf
- examples/kafka_connect/kafka_service.tf
- examples/kafka_connect/output.tf
- examples/kafka_connect/variables.tf
- examples_tests/kafka_connect_test.go
Kafka and Kafka Connect services are in their own files so that each can be embedded in Aiven Docs for the Kafka and Connect get started guides respectively.
> docs: update kafka connect example for use in Aiven Docs

- CHANGELOG.md
- internal/sdkprovider/service/clickhouse/clickhouse_database.go
- internal/sdkprovider/service/clickhouse/clickhouse_database_test.go
- Sets required fields on import
- Removes the default value for `termination_protection` default value,
which caused unnecessary plan diffs
Resolves NEX-1357, #2132
> fix(clickhouse_database): import

- docs/resources/alloydbomni.md
- internal/sdkprovider/userconfig/service/alloydbomni.go
- ucgenerator/models.go
For the consistent result enum values must be always sorted.
> fix: sort userconfig enum values

- CHANGELOG.md
- internal/sdkprovider/service/clickhouse/clickhouse_grant.go
- internal/sdkprovider/service/clickhouse/clickhouse_grant_test.go
- internal/sdkprovider/service/clickhouse/escape.go
Privileges in Clickhouse can have numbers for example the S3 privilege,
this just changes the validation to allow numbers
This PR relies on this PR https://github.com/aiven/terraform-provider-aiven/pull/2148 to fix issue when specifying wildcards in database field so that one needs to be merged first.
Resolves: #xxxxx.
> fix(clickhouse_grant): allow S3 as privilege

- internal/plugin/service/organizationaddress/zz_converters.go
- internal/plugin/util/converters.go
- internal/schemautil/userconfig/desc.go
Expanders and Flatteners must return diags to align interfaces with supervising functions.
> refactor: convertors must return diags

- internal/plugin/service/organizationaddress/zz_converters.go
- internal/plugin/util/converters.go
The current implementation casts types straightforward because it relies on the Code-Generated models.
Which is fine mostly, but it might panic in case of a required+nullable field type.
> feat: support required+nullable fields

- CHANGELOG.md
- internal/sdkprovider/service/clickhouse/clickhouse_grant.go
The validation expected upper case letters while Clickhouse may return privileges with lower case letters, for example https://clickhouse.com/docs/sql-reference/statements/grant#dictget
Resolves NEX-1443
> fix: clickhouse_grant privilege case validation error

- docs/data-sources/organization_address.md
- docs/data-sources/organization_billing_group.md
- docs/resources/organization_address.md
- docs/resources/organization_billing_group.md
- internal/plugin/service/organization/address/address.go
- internal/plugin/service/organization/address/address_test.go
- internal/plugin/service/organization/address/zz_converters.go
- internal/plugin/service/organization/address/zz_datasource.go
- internal/plugin/service/organization/address/zz_resource.go
- internal/plugin/service/organization/billinggroup/billing_group.go
- internal/plugin/service/organization/billinggroup/zz_converters.go
- internal/plugin/service/organization/billinggroup/zz_datasource.go
- internal/plugin/service/organization/billinggroup/zz_resource.go
- internal/plugin/service/organization/billinggrouplist/zz_converters.go
- internal/plugin/service/organization/organization/organization.go
- internal/plugin/service/organization/organization/zz_converters.go
- internal/plugin/util/converters.go
The "plan" doesn't know if a field was removed. That comes from the "state".
- Extends `expandData` to support the "state"
- Improves array values drain (when removed from the config file)
- Ignores empty string values from Response, if the state doesn't have `""` explicitly
Contributes to NEX-1446.
> feat: add state to expandData

- docs/resources/clickhouse_grant.md
- examples/resources/aiven_clickhouse_grant/resource.tf
- internal/sdkprovider/service/clickhouse/clickhouse_grant.go
Adds a note about granting global privileges and includes an example of this.
> docs(clickhouse): add instructions for granting global privileges

- CHANGELOG.md
- internal/sdkprovider/service/clickhouse/clickhouse_grant.go
- internal/sdkprovider/service/clickhouse/clickhouse_grant_test.go
- added Set function to the `aiven_clickhouse_grant` to ignore case sensitive privilege names during the plan phase
- `DiffSuppressFunc` for `privilege` field does not works in this case, because the privilege is ForceNew and the hash is calculated before this function is called
- `StateFunc` for `privilege` field doesn't work because apparently there is a bug inside the plugin and when we'll transform the `Set` into the list like here: `d.Get("privilege_grant").(*schema.Set).List()` we will get additional elements in the list with empty values
- `CustomizeDiff` for the whole resource looks like a more complex option as it requires to disassemble quite complicated schema
> feat(clickhouse_grant): added ignore for case-sensitive privilege names

- TaskInternal.yml
By default, the docs generator uses the current directory name as the provider name. This prevents checking out the repository into a different directory.
For example, when setting up a separate development environment.
> refactor: generate docs with provider-name flag

- docs/resources/organization_project.md
- examples/resources/aiven_organization_project/resource.tf
Adds required `parent_id` field to the `aiven_organization_project` example.
> docs: fix example usage for aiven_organization_project

- internal/sdkprovider/service/clickhouse/clickhouse_grant_test.go
- Added test case demonstrating the issue with overlapping privileges like `DELETE`/`ALTER DELETE` and `ALTER ADD PROJECTION`/`ALTER PROJECTION`
- The `aiven_clickhouse_grant` resource produces non-empty Terraform plans after apply when users configure overlapping privileges. ClickHouse automatically merges overlapping grants (e.g., ALTER DELETE is subsumed by DELETE, ALTER PROJECTION is subsumed by ALTER ADD PROJECTION)
> feat(aiven_clickhouse_grant): added demonstration test

- CHANGELOG.md
- docs/resources/clickhouse_grant.md
- internal/sdkprovider/service/clickhouse/clickhouse_grant.go
- internal/sdkprovider/service/clickhouse/grant.go
-  skips the `NAMED COLLECTION` grants for the grants that were added outside of Terraform
- as we can not fully manage the NAMED COLLECTION grants in ClickHouse, [due](https://github.com/ClickHouse/ClickHouse/issues/80853) to the empty `database` field in `system.grants` table we will skip these types of GRANTS that it can be possible to assign them outside of Terraform
> feat(aiven_clickhouse_grant): skip named collection grants

- .github/workflows/acceptance-tests.yml
- .github/workflows/prepare-release.yml
- .github/workflows/reusable-acceptance-tests.yml
- change `acceptance_test` job to use [reusable_workflow](https://docs.github.com/en/actions/sharing-automations/reusing-workflows)
- Due to the [limitation](https://github.com/peter-evans/create-pull-request/issues/48) that PR-s created by GH actions does not trigger other actions, we need to find another way to call acceptance tests
> ci(GHA): improving pre-release job

- .github/workflows/publish-release.yml
- .gitignore
- fixed formatting for Release changelog
- pass the Changelog as a file, cause when we pass it through env variable all formats are lost
> ci: fixed release changelog formatting

- TaskInternal.yml
- Taskfile.dist.yml
Resolves: NEX-1667
- added quick formatter to the task to speed up the generation process instead of pre-commit fmt
> chore: quick formatting tool instead of pre-commit

- go.mod
- go.sum
- internal/schemautil/service.go
- internal/sdkprovider/service/pg/pg_database_test.go
Contributes to NEX-1674.
The `singleflight` uses a mutex per service.
Managing multiple databases from multiple services won't block each other.
> refactor(pg_database): use singleflight

- go.mod
- internal/schemautil/database.go
- internal/schemautil/database_test.go
- internal/schemautil/service.go
- internal/schemautil/wait.go
Contributes to NEX-1687.
Doesn't really cache the result, but can help with burst calls only.
> refactor: remove singleflight

- examples/kafka/karapace_schema_registry/README.md
- examples/kafka/karapace_schema_registry/kafka.tf
- examples/kafka/karapace_schema_registry/provider.tf
- examples/kafka/karapace_schema_registry/variables.tf
Adds the Karapace example from the Dev Center.
> docs(kafka): migrate karapace example from dev center

- TaskInternal.yml
- definitions/governance_access.yml
- definitions/organization_billing_group.yml
- definitions/organization_billing_group_list.yml
- definitions/organization_project.yml
- generators/plugin/examples.go
- generators/plugin/item.go
- generators/plugin/main.go
- generators/plugin/utils.go
Resolves NEX-1717.
- Fixes stack overflow in the plugin generator
- Adds a validation that prevents cycles
- Improves the patching: 
- it is possible to set now `optional` or `required` to `false` in yaml file
- improved merging: for instance, array element can be replaced without defining the whole node
- Reverts generator removal from the update command
> fix(plugin): infinitive recursion

- internal/sdkprovider/service/project/sweep.go
Resolves: NEX-1815
- Sweep billing groups with `test-` prefix instead of `test-acc`
> fix(billing_group): sweep all testing billing groups

- definitions/.schema.yml
- generators/plugin/imports.go
- generators/plugin/item.go
- generators/plugin/main.go
- generators/plugin/schemas.go
- generators/plugin/utils.go
- generators/plugin/validators.go
- internal/plugin/adapter/datasource.go
- internal/plugin/adapter/resource.go
- internal/plugin/adapter/view.go
- internal/plugin/service/organization/organization/organization.go
- internal/schemautil/userconfig/desc.go
Resolves NEX-1844.
- Generate validation rules from definition schema
- Child notes inherit `Computed` property from the parent.
This allows to mark a whole block as "computed" with just one attribute.
Validation rules do not apply to computed fields.
> feat(plugin): generate validation rules

- CHANGELOG.md
- internal/schemautil/schemautil.go
- internal/schemautil/schemautil_test.go
- internal/schemautil/service.go
Resolves: NEX-1864
- added validation for `maintenance_window_time` field requiring **HH:mm:ss** format
- validation matches API, so this should not be a breaking change
> feat: added validation to the service maintenance window time

- internal/sdkprovider/service/alloydbomni/alloydbomni_database_test.go
- internal/sdkprovider/service/alloydbomni/alloydbomni_user_test.go
Resolves: NEX-1890
- deprecated the AlloyDB tests due to the resource deprecation
> fix(alloydb): deprecated alloyDB tests

- internal/plugin/adapter/resource.go
- internal/plugin/adapter/view.go
- internal/plugin/service/governance/access/access.go
- internal/plugin/service/organization/address/address.go
- internal/plugin/service/organization/application_user/application_user.go
- internal/plugin/service/organization/application_user_token/application_user_token.go
- internal/plugin/service/organization/billinggroup/billing_group.go
- internal/plugin/service/organization/organization/organization.go
- internal/plugin/service/organization/permission/permission.go
- internal/plugin/service/organization/project/project.go
Resolves NEX-1927.
Enables distinguishing between user-defined and API default values. For resources like Kafka topics, this prevents marking API defaults as user-defined when sending only explicitly configured values.
> feat(plugin): add config parameter to resource Update method

- .golangci.yml
- definitions/.schema.yml
- generators/plugin/imports.go
- generators/plugin/item.go
- generators/plugin/main.go
- generators/plugin/models.go
- generators/plugin/schemas.go
- internal/plugin/adapter/datasource.go
- internal/plugin/adapter/resource.go
- internal/plugin/adapter/timeouts.go
- internal/plugin/adapter/timeouts_test.go
- internal/plugin/adapter/view.go
- internal/plugin/legacytimeouts/legacytimeouts.go
- internal/plugin/legacytimeouts/legacytimeouts_test.go
- internal/plugin/service/governance/access/zz_resource.go
- internal/plugin/service/organization/address/zz_datasource.go
- internal/plugin/service/organization/address/zz_resource.go
- internal/plugin/service/organization/application_user/zz_datasource.go
- internal/plugin/service/organization/application_user/zz_resource.go
- internal/plugin/service/organization/application_user_token/zz_resource.go
- internal/plugin/service/organization/billinggroup/zz_datasource.go
- internal/plugin/service/organization/billinggroup/zz_resource.go
- internal/plugin/service/organization/billinggrouplist/zz_datasource.go
- internal/plugin/service/organization/organization/zz_datasource.go
- internal/plugin/service/organization/organization/zz_resource.go
- internal/plugin/service/organization/permission/zz_resource.go
- internal/plugin/service/organization/project/zz_datasource.go
- internal/plugin/service/organization/project/zz_resource.go
- internal/plugin/validators/stringvalidator.go
- internal/schemautil/service.go
Resolves NEX-1907.
The Plugin Framework doesn't have the `default` timeout key. That's a breaking change for the resources we are migrating from SDKv2.
- Adds a custom `timeouts` block to the generator
- Adds timeouts string validator
- Uses timeouts to cancel the context in CRUD operations
- Disables `unused-parameter` linter rule (a waste of time)
> feat(plugin): generate legacy timeouts block
