aiven/terraform-provider-aiven

- resource_service_user.go
This PR depends on: https://github.com/jelmersnoeck/aiven/pull/3
> Resolve #8 Output Access Cert and Access Keys for users

- .travis.yml
- Makefile
- provider.go
- resource_database.go
- resource_project.go
- resource_service.go
- resource_service_user.go
- service_change.go
This will make sure everything works fine and is formatted properly.
> Integrate Travis.

- provider.go
@jelmersnoeck adds the option to authenticate with token auth in addition to username/password
> Adds token auth to the Aiven Provider

- Gopkg.lock
- Gopkg.toml
- resource_service.go
@jelmersnoeck @FranOis adds kafka connecton information export to the terraform provider
> Export Kafka Connection Information

- Gopkg.lock
- Gopkg.toml
- Makefile
- resource_service_integration_endpoint.go
- templates/integration_endpoints_user_config_schema.json
- templates/integrations_user_config_schema.json
- templates/service_user_config_schema.json
Also updated to latest user config options to support some other
new functionality.
> Support for Prometheus integration

- CHANGELOG.md
Support for Prometheus integration and some new config params
> Add changelog entry for 1.0.2

- Gopkg.lock
- Gopkg.toml
- resource_service.go
Also update to latest aiven-go-client
> Fix service_username property

- Makefile
> Build the linux build without CGO support for terraform Docker support

- CHANGELOG.md
- Makefile
- README.md
- go.mod
- provider.go
- resource_vpc_peering_connection.go
> add cross region vpc peering

- resource_database.go
- resource_service.go
> do not trigger change on unset attributes

- Makefile
- go.mod
- go.sum
- provider.go
- version.go
Depends on https://github.com/aiven/aiven-go-client/pull/31
> Pass User-Agent with version to client.

- resource_service.go
> mark service_uri as sensitive

- resource_service_integration_endpoint.go
- templates/integration_endpoints_user_config_schema.json
- templates/integrations_user_config_schema.json
- templates/service_user_config_schema.json
- add support for external Elasticsearch integration
- update syslog integration user config
- update service user config
> update user config and integration templates

- kafka_topic_change.go
The server may return 501 until the asynchronous topic creation op has
completed.
> Keep on retrying getting topic info when it fails with 501

- aiven/service_change.go
The check was already skipped in many cases because IP filter or VPC
may prevent connecting to the aux services to check their state.
Because the check is often skipped nothing can really rely on it so
the value it adds is very limited. The Aiven API should be extended
to provide more detailed state information for the aux services to
make this work properly.
This may possibly fix https://github.com/aiven/terraform-provider-aiven/issues/95
although I was unable to reproduce that.
> Do not wait for Kafka auxiliary services to start up

- aiven/templates/integration_endpoints_user_config_schema.json
- aiven/templates/integrations_user_config_schema.json
- aiven/templates/service_user_config_schema.json
This also enables creation of Elasticsearch version 7, Kafka version 2.4
and Postgresql version 12 services.
> schemas: update config schemas to match latest API

- aiven/resource_kafka_topic.go
- pkg/cache/kafka_topic_cache.go
I messed up my git history when trying to squash on #107, so raising this new PR instead.
> Enable topic caching

- CHANGELOG.md
new release CHANGELOG 1.0.18 notes
> new release CHANGELOG 1.0.18

- aiven/resource_service.go
- aiven/resource_service_test.go
- examples/service/project.tf
- examples/service/provider.tf
- examples/service/service.tf
- examples/service/variables.tf
Add service components to Aiven Terraform provider
> Add service components 

- aiven/provider.go
- aiven/version.go
Remove client version since it is always zero and not adding any value
> remove client version

- aiven/user_config.go
Should fix this issue: https://github.com/aiven/terraform-provider-aiven/issues/159.
The problem appears for optional bool user configuration options, and this is related to a previous PR https://github.com/aiven/terraform-provider-aiven/pull/134 which converts optional bool settings and without a default value to a string for internal representation, to prevent force setting of this configuration option for service.
An error was accruing even before but wasn't visible for a user, an error was omitted, after this PR https://github.com/aiven/terraform-provider-aiven/pull/150 we start throwing panic in case of an error which we probably should not do, but maybe send a warning instead.
> fix setting from API user_config optional bool fields

- README.md
- aiven/datasource_account.go
- aiven/datasource_account_team.go
- aiven/datasource_account_team_member.go
- aiven/datasource_account_team_project.go
- aiven/datasource_project.go
- aiven/provider.go
- aiven/resource_account.go
- aiven/resource_account_team.go
- aiven/resource_account_team_member.go
- aiven/resource_account_team_member_test.go
- aiven/resource_account_team_project.go
- aiven/resource_account_team_project_test.go
- aiven/resource_account_team_test.go
- aiven/resource_account_test.go
- aiven/resource_project.go
- aiven/resource_project_test.go
- aiven/resource_service_test.go
- examples/account/accounts.tf
- examples/account/project.tf
- examples/account/provider.tf
- go.mod
- go.sum
In this PR, added support for:
- accounts
- account teams
- account team members and invitations
- account projects 
Account Authentication methods support will be in a separate PR
> Add accounts support

- aiven/resource_service_pg_test.go
- aiven/resource_service_test.go
- aiven/service_change.go
Should fix this issue https://github.com/aiven/terraform-provider-aiven/issues/170
> fix a creation problem for read-only replica type DB services

- aiven/datasource_account_team_member_test.go
- aiven/datasource_account_team_test.go
- aiven/datasource_account_test.go
- aiven/datasource_projcect_user_test.go
- aiven/datasource_project_test.go
Added data source project, project user, account, account team and account team member tests
> testacc: add data source tests

- aiven/service_change.go
During the creation or update of Grafana service check availability of Grafana
> aiven_service wait during creation or change until grafana is reachable

- aiven/resource_project_vpc.go
- aiven/resource_project_vpc_test.go
project vpc graceful deletion and acceptance tests
> project vpc graceful deletion

- aiven/resource_service_integration_endpoint_test.go
- aiven/resource_service_integration_test.go
Acceptance tests for service integration and service integration endpoint TF resources
> testacc: service integration

- aiven/resource_service_grafana_test.go
- aiven/service_change.go
skip grafana service availability checks when IP filters different from default
> update grafana service change

- aiven/resource_kafka_acl_test.go
- aiven/resource_kafka_topic_test.go
Remove unnecessary use of fmt.Sprintf
> remove unnecessary use of fmt.Sprintf

- aiven/datasource_project_vpc.go
- aiven/resource_project_vpc.go
- aiven/resource_project_vpc_test.go
Typo corrected, Nothing fancy.
> Correct VCPSchema typo in project_vpc resource

- examples/kafka_connect/project.tf
- examples/kafka_connect/provider.tf
- examples/kafka_connect/services.tf
- examples/kafka_connect/variables.tf
Add Kafka connect example as was requested here https://github.com/aiven/terraform-provider-aiven/issues/193
> add kafka connect example

- README.md
- aiven/resource_project_vpc.go
- aiven/resource_project_vpc_test.go
- aiven/resource_vpc_peering_connection.go
- aiven/resource_vpc_peering_connection_test.go
As requested here https://github.com/aiven/terraform-provider-aiven/issues/204
> add vpc custom timeout properties

- aiven/provider.go
- aiven/provider_test.go
- aiven/resource_project_vpc.go
- aiven/resource_project_vpc_test.go
- aiven/resource_vpc_peering_connection.go
- aiven/resource_vpc_peering_connection_test.go
Update VPC client timeouts according to the new specification
> update VPC client timeouts format

- README.md
- examples/cassandra_fork/project.tf
- examples/cassandra_fork/provider.tf
- examples/cassandra_fork/service.tf
- examples/cassandra_fork/variables.tf
Added install instructions before we are available under Terraform
Added Cassandra service deployment example with forking a service (at customer request)
> Update README with examples outline and install instructions

- README.md
- examples/getting-started.tf
Added instructions for local install (useful for Terraform Cloud) users
> Single File Getting Started Example and Install Instructions

- README.md
https://github.com/aiven/terraform-provider-aiven/issues/219
> minor fix in documentation

- index.html
Index file needed to redirect as config does not redirect to README
> Add index for pages

- Makefile
Updated makefile using latest go and packr2 version, also disable `go vendor` to make it work properly with the modules and hopefully, it will fix a Jenkins job.
> Fix Jenkins job

- aiven/user_config.go
Intended to simplify code and remove auxiliary api_type logic.
> user configuration options refactoring

- docs/guides/syslog-service-integration.md
Based on customer request. Basic example with sample script.
> Add guide for adding syslog (or similar) service integrations

- Makefile
avoid compatibility troubles (alpine containers for I.E.)
cf: https://github.com/aiven/terraform-provider-aiven/issues/248
> force static compilation

- .travis.yml
Prevent cyclical builds deploying to master and watching for changes on master
> Remove target branch from travis

- .gitignore
- .goreleaser.yml
- .travis.yml
> use goreleaser to release terraform provider automatically

- aiven/datasource_account_team_project.go
- aiven/datasource_connection_pool.go
- aiven/datasource_kafka_connector.go
- aiven/resource_kafka.go
- aiven/resource_kafka_acl_test.go
found and fixed these small issues by running `golangci-lint`
> small fixes

- aiven/resource_vpc_peering_connection.go
extend VPC peering connection creation with new azure related optional fields
> extend VPC peering connection creation 

- aiven/resource_transit_gateway_vpc_attachement_test.go
- aiven/resource_vpc_peering_connection.go
- aiven/resource_vpc_peering_connection_test.go
New Azure settings that were added to VPC peering connection that brake Transit Gateway VPC attachment resource
>  fix transit gateway attachment

- README.md
- examples/kafka_prometheus/main.tf
- examples/kafka_prometheus/variables.tf
- sample.tf
Requested by customer due to confusion from the docs. Adding more detailed examples or guides for common use cases might be useful and I have it in my backlog
> Add examples for enabling Prometheus Public Access and adding a Service Integration

- aiven/kafka_topic_availability.go
- aiven/provider.go
- aiven/resource_kafka_topic.go
- aiven/resource_kafka_topic_test.go
- docs/data-sources/kafka_topic.md
- docs/resources/kafka_topic.md
- go.mod
- go.sum
- pkg/cache/kafka_topic_cache.go
- pkg/cache/kafka_topic_cache_test.go
- use new Kafka Topic config
- deprecate old fields
- change Kafka Topic cache, since list API method does not retrieve `config`
- update docs
> add support for new kafka topic features

- docs/guides/getting-started.md
- docs/guides/syslog-service-integration.md
Replace required_providers block
> small doc changes in guides

- docs/guides/upgrade-guide.md
This PR adds an initial guide document where we can record issues encountered during provider upgrades. I'm open for any and all restructuring / rewording / reorganising, just wanted to write something down for this case.
> Add guide for documenting issues encountered during upgrades

- aiven/kafka_topic_create.go
- aiven/resource_account.go
- aiven/resource_account_authentication.go
- aiven/resource_account_team.go
- aiven/resource_account_team_member.go
- aiven/resource_account_team_project.go
- aiven/resource_connection_pool.go
- aiven/resource_database.go
- aiven/resource_kafka_acl.go
- aiven/resource_kafka_connector.go
- aiven/resource_kafka_schema.go
- aiven/resource_kafka_topic.go
- aiven/resource_mirrormaker_replication_flow.go
- aiven/resource_project.go
- aiven/resource_project_user.go
- aiven/resource_project_vpc.go
- aiven/resource_service.go
- aiven/resource_service_integration.go
- aiven/resource_service_integration_endpoint.go
- aiven/resource_service_user.go
- aiven/resource_vpc_peering_connection.go
- go.mod
- go.sum
- add is already exists error handling for create operation
- add is not found for error handling for delete operation
> small improvements

- aiven/provider.go
- aiven/resource_kafka_topic_test.go
Used mainly for Kafka Topic Config float64 properties
> fix float to string conversion

- aiven/kafka_topic_create.go
- aiven/resource_kafka_topic_test.go
- aiven/resource_service.go
Fixes incorrect handling of an already exists error during creation of the topic.
> fix kafka topic creation typo

- .github/workflows/go.yml
We leave TravisCI for now, later should be deleted from the repo sitting and the codebase.
> add support for github actions 

- docs/index.md
using callouts based on this doc - https://www.terraform.io/docs/registry/providers/docs.html#callouts
> add terraform modules related docs

- aiven/kafka_topic_availability.go
`terraform plan` started to fail with `error waiting for Aiven Kafka topic to be ACTIVE: couldn't find resource (21 retries)`.
We have about Kafka 400 topics in a single project, and while reviewing the code we noticed a few issues introduced by #334:
1. Provider makes N+1 requests to the Aiven API while holding the semaphore.
2. Provider is not resilient to failures on the Aiven API and abandons the remaining unprocessed topics from the list on the first error (which will eventually cascade and lead to other N+1 requests).
This PR addresses both issues by:
1. Using `KafkaTopicAvailabilityWaiter.refresh()` to only refresh the list of known topics.
2. Returning a `resource.StateRefreshFunc` that only fetches the config for the topic that was requested.
This way we avoid `N-n` requests to …
> Load topic config on demand

- aiven/resource_billing_group.go
- aiven/resource_billing_group_test.go
- aiven/resource_pg.go
- aiven/resource_project.go
- go.mod
- go.sum
- waiting for go-client PR to be merged first
> billing group: change project fields behaviour

- aiven/resource_vpc_peering_connection.go
We use a VPC peering connection codebase for Azure, AWS, GCP, and AWS Transit Gateway Attachment. Depending on the situation, we silence errors when Terraform attempts to set a value to a field that does not exist. It all works fine when a client setting TF_SCHEMA_PANIC_ON_ERROR is turned off, but we see that it is not the case for some customers. When panic-on-error is on, Terraform SDK throws a panic on the attempt to set a none existing VPC peering connection field and interrupt the plan's execution.
Ideally, we would like to have a separate resource for each type of VPC peering connection, but this patch should resolve issues for customers with TF_SCHEMA_PANIC_ON_ERROR=on.
> isolating Azure fields settings for VPC peering connection

- aiven/kafka_topic_availability.go
- error when it is impossible to warm-up cache
- set PollInterval, which overrides MinTimeout to 30s
- add topics to the queue while waiting cache to be refreshed
> add kafka topic availability improvements

- docs/data-sources/project.md
- docs/resources/project.md
Resolves https://github.com/aiven/terraform-provider-aiven/issues/460
> Document missing non-deprecated project arguments and attributes

- docs/index.md
- examples/mysql/provider.tf
- examples/mysql/service.tf
- examples/mysql/variables.tf
Please vote on this pull request by adding :+1: ,comments to help the community
> added mysql code

- aiven/resource_service_user.go
- go.mod
- go.sum
It has a fix for service user read method
> use latest version of go-client

- README.md
- docs/data-sources/cassandra.md
- docs/data-sources/elasticsearch.md
- docs/data-sources/grafana.md
- docs/data-sources/influxdb.md
- docs/data-sources/kafka.md
- docs/data-sources/kafka_connect.md
- docs/data-sources/kafka_mirrormaker.md
- docs/data-sources/m3aggregator.md
- docs/data-sources/m3db.md
- docs/data-sources/mysql.md
- docs/data-sources/pg.md
- docs/data-sources/redis.md
- docs/guides/examples.md
- docs/guides/importing-resources.md
- docs/guides/install-terraform-v012.md
- docs/index.md
- docs/resources/cassandra.md
- docs/resources/elasticsearch.md
- docs/resources/grafana.md
- docs/resources/influxdb.md
- docs/resources/kafka.md
- docs/resources/kafka_connect.md
- docs/resources/kafka_mirrormaker.md
- docs/resources/m3aggregator.md
- docs/resources/m3db.md
- docs/resources/mysql.md
- docs/resources/pg.md
- docs/resources/redis.md
Hi there!
Just adding some small docs fixes and UTM tags to the signup pages.
> Small docs fixes

- aiven/resource_database.go
Sometimes deletion of database results in a 500 error
> add database delete waiter

- docs/resources/service_integration.md
- docs/resources/service_integration_endpoint.md
Add example of usage for a Prometheus integration and update available `endpoint_type` values in `aiven_service_integration_endpoint` resource
> Add Prometheus integration example

- aiven/resource_vpc_peering_connection.go
`vpc_peering_connection`: wait for deletion
Previously `vpc_peering_connections` would be deleted asynchronously. There is a race condition when deleting and recreating the resource, where recreation fails because the previous deletion has not finished yet. This PR fixes the race by waiting for the `vpc_peering_connection` to be deleted synchronously.
> DRAFT: use a waiter when deleting vpc peering connections

- aiven/resource_service_integration.go
For some reason, the update request was lacking user-config.
> fix service integration update

- aiven/templates/integration_endpoints_user_config_schema.json
The error message was slightly deceptive.
> Minor fix for error messages

- .github/CODEOWNERS
- .github/workflows/acceptance-tests.yml
- .github/workflows/changelog-checker.yml
- .semgrep.yml
- Makefile
- aiven/datasource_service_integration.go
- aiven/resource_azure_privatelink_test.go
- aiven/resource_flink_test.go
- aiven/resource_kafka_connector_test.go
- aiven/resource_kafka_topic_test.go
- aiven/resource_m3aggregator_test.go
- aiven/resource_m3db_test.go
- aiven/resource_mysql_test.go
- aiven/resource_pg_test.go
- aiven/resource_redis_test.go
- aiven/resource_service.go
- aiven/resource_service_integration_test.go
- aiven/resource_service_kafka_connect_test.go
- aiven/resource_service_mysql_test.go
- aiven/resource_service_pg_test.go
- aiven/resource_service_redis_test.go
- aiven/service_change.go
This PR aims to: 
* add code owners file to automatically assign reviewers
* bind acceptance tests to a label `needs-acceptance-tests`
* bind changelog check to a label `needs-changelog`
* run acceptance tests with more concurrency
* enable that resources get deleted more quickly
> improve acceptance tests; some repository fixes

- aiven/resource_opensearch_test.go
This PR adds a simple acceptance test for an ES -> OS migration with subsequent import of the remote OS into an opensearch resource.
> acc test for migration from es to os and consequent import

- CHANGELOG.md
- aiven/resource_flink_job.go
- aiven/resource_flink_table.go
- aiven/resource_flink_test.go
- docs/resources/flink_job.md
- docs/resources/flink_table.md
- examples/flink/main.tf
- examples/resources/aiven_flink_job/resource.tf
- examples/resources/aiven_flink_table/resource.tf
- examples/resources/aiven_pg/resource.tf
- go.mod
- go.sum
This PR aims to synchronize the flink resources ( table/job ) with the upstream API.
> sync flink resources

- aiven/resource_elasticsearch_acl_rule_test.go
This PR adds an acceptance test for importing es acl rules
> resource_elasticsearch_acl: add import test

- CHANGELOG.md
- aiven/resource_service.go
- aiven/resource_service_test.go
- docs/data-sources/service.md
- docs/resources/service.md
This PR fixes the deprecated service resource by adding the `disk_space_used` attribute again.
> resource_service: add disk_space_used

- aiven/internal/service/wait.go
- aiven/resource_pg_test.go
- aiven/resource_service.go
minor pr to cleanup a few static ip related methods
> static ips: minor cleanup

- aiven/resource_static_ip_test.go
This PR adds a import test for static ips to complement the newly added import functionality
> static_ip: add import test

- .github/workflows/acceptance-tests.yml
adapts to a breaking change in v5 of the github script release.
> workflows: try to fix acceptance test workflow

- README.md
Just removing a few stale paragraphs from the readme
> readme: remove old paragraphs

- docs/resources/flink_table.md
- examples/resources/aiven_flink_table/import.sh
- internal/service/clickhouse/resource_clickhouse_grant_test.go
- internal/service/flink/resource_flink_table.go
- internal/service/flink/resource_flink_test.go
Add support for `import` for aiven flink table
> Add import statement support for flink table

- examples/kafka_prometheus/main.tf
Removing "0.0.0.0/0" since this will allow all IP addresses and the filter will be of no use.
> Removing "0.0.0.0/0" that allows all IP addresses

- internal/schemautil/wait.go
- internal/service/redis/resource_service_redis_test.go
> fix WaitForServiceCreation when Redis persistence is off

- CHANGELOG.md
- examples/m3/provider.tf
- examples/m3/services_and_integrations.tf
- Updating service versions that were no longer in use
- Fixing M3DB namespace name in the example
- Updating provider version to latest
- Added the change to CHANGELOG
> Updating service versions and fix namespace issue

- internal/service/service_component/datasource_service_component.go
- internal/service/service_component/datasource_service_component_test.go
[DARK-473]
[DARK-473]: https://aiven.atlassian.net/browse/DARK-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Refine datasource service component error message

- docs/resources/aws_vpc_peering_connection.md
- examples/resources/aiven_aws_vpc_peering_connection/import.sh
- internal/service/vpc/resource_aws_vpc_peering_connection.go
- internal/service/vpc/resource_azure_vpc_peering_connection.go
- internal/service/vpc/resource_gcp_vpc_peering_connection.go
- internal/service/vpc/resource_vpc_peering_connection.go
> fix VPC peering connection import

- README.md
minor naming fix for some URLs in README.md
to make it unified with the name of actual docs those links refer to
> docs: minor naming fix in README.md

- CHANGELOG.md
fixed CHANGELOG.md inconsistency
to keep things consistent :)
> fix CHANGELOG.md inconsistency

- CHANGELOG.md
- docs/resources/service_integration.md
- templates/resources/service_integration.md.tmpl
> docs: fix typo for service integration docs

- CHANGELOG.md
- sample_project/sample.tf
fixes sample project version
Resolves: #799
> fix simple_project example

- CHANGELOG.md
- docs/data-sources/kafka_connector.md
- docs/resources/kafka_connector.md
- internal/service/kafka/resource_kafka_connector.go
- internal/service/kafka/resource_kafka_connector_test.go
> fix: mark config of kafka connector as sensitive

- CHANGELOG.md
- internal/service/static_ip/resource_static_ip.go
- internal/service/static_ip/resource_static_ip_test.go
small static IP import fix
to improve static IP import and tests
> small static IP import fix

- CHANGELOG.md
- internal/service/static_ip/resource_static_ip_test.go
adds acceptance test for validating 404 error handling during import
to improve test coverage
> add acceptance test for validating 404 error handling during import

- .gitignore
- CHANGELOG.md
- sample_project/sample.tf
drops deprecated resources from sample project
to make sample project up to date
> drop deprecated resources from sample project

- CHANGELOG.md
- docs/data-sources/account_authentication.md
- docs/resources/account_authentication.md
- go.mod
- go.sum
- internal/service/account/resource_account_authentication.go
- updates account authentication SAML fields
to match current API
> update account authentication SAML fields

- CHANGELOG.md
- internal/schemautil/custom_diff.go
- internal/service/flink/resource_flink_job.go
- internal/service/flink/resource_flink_table.go
- internal/service/flink/resource_flink_test.go
adds Flink SQL validation
users will struggle less when they know about SQL errors straight away and not during mid-apply
> add Flink SQL validation

- CHANGELOG.md
- sample_project/outputs.tf
adds outputs example to the sample project
resolves #507
to improve documentation
> add outputs example to the sample project

- .github/workflows/acceptance-tests.yml
- .github/workflows/unit-tests.yml
- CHANGELOG.md
- Makefile
- Beautifies and reworks `Makefile`
- Adds `make` targets `build` and `build-dev`
to improve the `Makefile`
> improve Makefile

- CHANGELOG.md
fixes Markdown formatting in `CHANGELOG.md`
because Markdown guidelines exist :)
> fix Markdown formatting in CHANGELOG.md

- .github/workflows/changelog-enforcer.yml
- CHANGELOG.md
fixes Changelog Enforcer GitHub Actions workflow
it doesn't works properly atm
> fix Changelog Enforcer GitHub Actions workflow

- .github/workflows/changelog-enforcer.yml
- CHANGELOG.md
delete me
adds no changelog label check in changelog-enforcer.yml
we need to skip changelog entries for some PRs
> add no changelog label check in changelog-enforcer.yml

- .github/workflows/codeql.yml
- CHANGELOG.md
adds CodeQL workflow
to have CodeQL analysis :)
> add CodeQL workflow

- CHANGELOG.md
- docs/resources/flink_table.md
- go.mod
- go.sum
- internal/service/flink/resource_flink_table.go
- internal/service/flink/resource_flink_test.go
adds opensearch_index support to aiven_flink_table
to follow the API updates
> add opensearch_index support to aiven_flink_table

- internal/acctest/provider_test.go
- internal/service/clickhouse/role.go
- internal/service/kafka/cache/kafka_acl_cache.go
- internal/service/kafka/cache/kafka_topic_cache.go
- main.go
ran JetBrains code cleanup
there's going to be a bunch of clean up PRs, I will add a changelog entry for it with the last PR
to clean the code up
> run JetBrains code cleanup

- .github/workflows/codeql.yml
- .github/workflows/lint.yml
- .github/workflows/release-artifacts.yml
- .github/workflows/unit-tests.yml
fixes workflow formatting
there's going to be a bunch of clean up PRs, I will add a changelog entry for it with the last PR
to improve the formatting
> fix workflow formatting

- examples/account/README.md
- examples/postgres/bin/apply
- examples/postgres/bin/destroy
- internal/provider/provider.go
- internal/schemautil/common.go
- internal/schemautil/schemautil.go
- internal/schemautil/service.go
- internal/schemautil/templates/gen.sh
- internal/schemautil/templates/schema.go
- internal/schemautil/user_config.go
- internal/service/database/datasource_database.go
- internal/service/database/resource_database.go
- internal/service/kafka/kafka_acl_cache.go
- internal/service/kafka/kafka_topic_availability.go
- internal/service/kafka/kafka_topic_cache.go
- internal/service/kafka/kafka_topic_cache_test.go
- internal/service/kafka/kafka_topic_create.go
- internal/service/kafka/resource_kafka_acl.go
- internal/service/kafka/resource_kafka_topic.go
- internal/service/mysql/resource_mysql_database_test.go
- internal/service/pg/resource_pg_database_test.go
- internal/service/service_integration/resource_service_integration.go
- internal/service/service_integration/resource_service_integration_endpoint.go
- internal/service/service_user/datasource_service_user.go
- internal/service/service_user/resource_service_user.go
- internal/service/vpc/datasource_vpc_peering_connection.go
- internal/service/vpc/resource_azure_privatelink_connection_approve.go
- internal/service/vpc/resource_transit_gateway_vpc_attachement.go
- internal/service/vpc/resource_vpc_peering_connection.go
fixes code warnings and errors
there's going to be a bunch of clean up PRs, I will add a changelog entry for it with the last PR
to improve code quality
> fix code warnings and errors

- CHANGELOG.md
- Makefile
- docs/data-sources/pg.md
- docs/resources/pg.md
- internal/schemautil/service.go
- internal/service/pg/resource_pg.go
- internal/service/pg/resource_service_pg_test.go
- sample_project/outputs.tf
adds PostgreSQL max connections and PgBouncer outputs
to make `sample_project` better, to let users have connection limit information available
> add PostgreSQL max connections and PgBouncer outputs

- .golangci.yml
- CHANGELOG.md
adds revive linter
to improve code quality
> add revive linter

- .github/workflows/release-artifacts.yml
fixes release artifacts workflow
it was broken
> fix release artifacts workflow

- .github/workflows/changelog-enforcer.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/lint.yml
- .github/workflows/unit-tests.yml
adds skip workflows label support
some PRs don't need to have any workflows ran for them, e.g. PRs that only change `CHANGELOG.md`
> add skip workflows label support

- .github/workflows/unit-tests.yml
fixes title case in `unit-tests.yml`, so that the name of this workflow is unified with all other workflows
to unify the naming with other workflows
> fix title case in unit-tests.yml

- CHANGELOG.md
> pre-release v3.6.0 

- CHANGELOG.md
- docs/data-sources/account.md
- docs/resources/account.md
- go.mod
- go.sum
- internal/service/account/datasource_account_test.go
- internal/service/account/resource_account.go
- internal/service/account/resource_account_test.go
Add support is_account_owner field https://api.aiven.io/doc/#operation/AccountList
> add is_account_owner computed field

- CHANGELOG.md
- internal/schemautil/ipfilter.go
- internal/schemautil/user_config.go
Fixes empty user config with empty element case
Resolves: #834.
> fix empty user_config and empty ip_filters

- CHANGELOG.md
- Makefile
- tools/go.mod
fixes `tools/` consistency and order of tools in `Makefile`
we want things to be consistent
> refactor: fix tools consistency

- CHANGELOG.md
- docs/data-sources/service_integration.md
- docs/resources/service_integration.md
- go.mod
- go.sum
- internal/service/service_integration/resource_service_integration.go
- internal/service/service_integration/resource_service_integration_test.go
Resolves: #888 
Add support of datadog specific user configurable settings.
> force send user_config on service integration update

- .github/CODEOWNERS
changes team in `CODEOWNERS` file
GitHub doesn't supports multiple `CODEOWNERS` entries so we decided to create a new team for it
> ci(codeowners): change team

- internal/schemautil/user_config/convert.go
- internal/schemautil/user_config/handle.go
- internal/schemautil/user_config/integration_endpoint_types.go
- internal/schemautil/user_config/integration_types.go
- internal/schemautil/user_config/service_types.go
- internal/schemautil/user_config/util.go
adds support for `array` types in user config static schema generator
to support `array` types :)
> feat: user config SSG, arrays

- CHANGELOG.md
releases v3.7.0
to make it happen
> pre-release: v3.7.0

- internal/schemautil/schemautil.go
- internal/schemautil/user_config/convert.go
- internal/schemautil/user_config/handle.go
- internal/schemautil/user_config/service_types.go
- internal/schemautil/user_config/util.go
adds support for properties like `ip_filter`
to support them
> feat: add support for properties like ip_filter

- internal/schemautil/user_config/convert.go
- internal/schemautil/user_config/handle.go
- internal/schemautil/user_config/service_types.go
- internal/schemautil/user_config/util.go
adds support for arrays with `one_of` property
to make them supported too
> feat: add support for arrays with one_of property

- docs/guides/syslog-service-integration.md
- docs/index.md
- templates/guides/syslog-service-integration.md
- templates/index.md
Fix link in the docs to the user config options 
Resolves: #906.
> fix: update links to user configuration options in the docs

- CHANGELOG.md
- internal/service/service_component/datasource_service_component.go
- internal/service/service_component/datasource_service_component_test.go
Fix service component optional parameters filtering
> fix service component optional parameters filters

- CHANGELOG.md
- internal/schemautil/user_config.go
> pre-release: v3.8.0

- CHANGELOG.md
- internal/schemautil/common.go
fixes `GetServiceUserValidateFunc`
it didn't match the error message it threw
> fix(common): GetServiceUserValidateFunc

- CHANGELOG.md
- go.mod
- go.sum
- internal/service/vpc/resource_azure_vpc_peering_connection.go
- internal/service/vpc/resource_project_vpc.go
- internal/service/vpc/resource_transit_gateway_vpc_attachement.go
- internal/service/vpc/resource_vpc_peering_connection.go
Fixes Azure vpc peering connection import.
> fix Azure vpc peering connection import

- CHANGELOG.md
- docs/resources/pg_user.md
- examples/resources/aiven_pg_user/import.sh
Adds pg user import example, covers #942
> add aiven_pg_user import example to docs

- go.mod
- go.sum
TF SDK update to the latest version, hopefully tests will work better on this version
> terraform sdk update to the latest version

- CHANGELOG.md
- docs/data-sources/grafana.md
- docs/resources/grafana.md
- go.mod
- go.sum
- internal/service/project/resource_project.go
- internal/service/project/resource_project_test.go
- omits empty `add_account_owners_admin_access` on create
- adds `add_account_owners_admin_access` on update
- updates aiven-go-client
> fix project create/update

- internal/schemautil/userconfig/apiconvert/fromapi_test.go
- internal/schemautil/userconfig/apiconvert/toapi.go
- internal/schemautil/userconfig/apiconvert/toapi_test.go
- internal/schemautil/userconfig/apiconvert/util_test.go
- internal/schemautil/userconfig/const.go
- internal/schemautil/userconfig/handle.go
- internal/schemautil/userconfig/util.go
adds tests for static schema generator
to deliver quality code
> test: static schema generator

- CHANGELOG.md
- Makefile
- internal/schemautil/ipfilter.go
- internal/service/vpc/resource_project_vpc.go
> v3.8.1 pre release

- internal/schemautil/custom_diff.go
- internal/schemautil/userconfig/apiconvert/toapi.go
- internal/schemautil/userconfig/handle.go
- internal/schemautil/userconfig/util.go
- internal/service/cassandra/resource_cassandra.go
- internal/service/clickhouse/resource_clickhouse.go
- internal/service/flink/resource_flink.go
- internal/service/grafana/resource_grafana.go
- internal/service/influxdb/resource_influxdb.go
- internal/service/kafka/resource_kafka.go
- internal/service/kafka/resource_kafka_connect.go
- internal/service/kafka/resource_kafka_mirrormaker.go
- internal/service/m3db/resource_m3aggregator.go
- internal/service/m3db/resource_m3db.go
- internal/service/mysql/resource_mysql.go
- internal/service/opensearch/resource_opensearch.go
- internal/service/pg/resource_pg.go
- internal/service/redis/resource_redis.go
disallows to set both `ip_filter` and `ip_filter_object`
because Terraform's `ConflictsWith` doesn't really works
> feat(ssg): many to one conflicts with

- CHANGELOG.md
- examples/kafka_connect/project.tf
- examples/kafka_connect/provider.tf
- examples/kafka_connect/services.tf
- examples/kafka_connect/variables.tf
- examples_tests/kafka_connect_test.go
- examples_tests/postgres_test.go
- internal/service/service_integration/resource_service_integration.go
- internal/sweep/sweep.go
Adds extra timeout for kafka_connect create. Adds example test.
> increase default timeout for kafka_connect service integration create, add example test

- internal/sweep/sweep.go
> fix sweep make command

- internal/service/project/resource_billing_group_test.go
- internal/service/project/resource_project.go
Fix project package acc tests
With the new ACLs it is impossible to copy from a project when a source project had no credit card
> test: fix project acc tests

- CHANGELOG.md
- docs/data-sources/service_integration.md
- docs/resources/service_integration.md
- internal/service/service_integration/resource_service_integration.go
- internal/service/service_integration/resource_service_integration_test.go
- Adds `clickhouse_postgresql` service integration type support
> support `clickhouse_postgresql` integration type in `aiven_service_integration`

- internal/service/grafana/resource_grafana_test.go
- internal/service/grafana/resource_service_grafana_test.go
Adds tests for `ip_filter` and `ip_filter_object` fields.
> add grafana ip_filter, ip_filter_object tests

- internal/service/grafana/resource_service_grafana_test.go
Currently the test won't work.
> skip grafana ip_filter_object test

- internal/service/vpc/resource_aws_privatelink_test.go
- internal/service/vpc/resource_aws_vpc_peering_connection_test.go
- internal/service/vpc/resource_transit_gateway_vpc_attachement_test.go
Adds `aiven_aws_privatelink` resource test.
> test: add aiven_aws_privatelink

- docs/resources/cassandra.md
- docs/resources/clickhouse.md
- docs/resources/flink.md
- docs/resources/grafana.md
- docs/resources/influxdb.md
- docs/resources/kafka.md
- docs/resources/kafka_connect.md
- docs/resources/kafka_mirrormaker.md
- docs/resources/m3aggregator.md
- docs/resources/m3db.md
- docs/resources/mysql.md
- docs/resources/opensearch.md
- docs/resources/pg.md
- docs/resources/redis.md
- internal/schemautil/userconfig/dist/service_types.go
- internal/schemautil/userconfig/handle.go
adds deprecation notice for `ip_filter` and `namespaces`
to inform our users about the upcoming changes
> refactor: add a deprecation notice for ip_filter and namespaces

- CHANGELOG.md
- docs/data-sources/mirrormaker_replication_flow.md
- docs/resources/mirrormaker_replication_flow.md
- internal/schemautil/common.go
- internal/service/kafka/resource_mirrormaker_replication_flow.go
- internal/service/kafka/resource_mirrormaker_replication_flow_test.go
Adds `offset_syncs_topic_location` support for `aiven_mirrormaker_replication_flow` resource.
> add offset_syncs_topic_location support

- CHANGELOG.md
- internal/schemautil/schemautil.go
- internal/schemautil/userconfig/apiconvert/fromapi.go
- internal/schemautil/userconfig/apiconvert/toapi.go
- internal/schemautil/userconfig/dist/integration_endpoint_types.go
- internal/schemautil/userconfig/dist/integration_types.go
- internal/schemautil/userconfig/dist/service_types.go
- internal/service/cassandra/resource_service_cassandra_test.go
- internal/service/kafka/resource_kafka_topic_test.go
- internal/service/kafka/resource_mirrormaker_replication_flow_test.go
- internal/service/kafka/resource_service_kafka_connect_test.go
- internal/service/kafka/resource_service_kafka_test.go
- internal/service/mysql/resource_service_mysql_test.go
- internal/service/opensearch/resource_opensearch_test.go
- internal/service/pg/resource_service_pg_test.go
- internal/service/redis/resource_service_redis_test.go
- internal/service/vpc/resource_azure_privatelink_test.go
- internal/service/vpc/resource_project_vpc_test.go
adds support for strict types in diff functions
to make the strict types function properly
> feat(ssg): support strict types in diff funcs

- CHANGELOG.md
- internal/schemautil/ipfilter.go
- internal/schemautil/sensitive.go
- internal/schemautil/service.go
- internal/schemautil/userconfig/util.go
- internal/service/pg/resource_pg_test.go
Saves admin credentials to the state to make plan work correctly 
Resolves: #997.
> fix admin credentials diff

- internal/schemautil/userconfig/apiconvert/toapi.go
- internal/schemautil/userconfig/apiconvert/toapi_test.go
fixes acceptance tests problems that were introduced recently due to incomplete function
to make acceptance tests great again
> fix(acctest): misbehavior due to incomplete fn

- CHANGELOG.md
- examples_tests/base.go
- go.mod
- go.sum
- internal/common/client.go
- internal/provider/provider.go
- internal/service/kafka/datasource_kafka_topic.go
- internal/service/kafka/datasource_kafka_topic_test.go
- internal/service/kafka/kafka_topic_availability.go
- internal/service/kafka/kafka_topic_cache.go
- internal/service/kafka/resource_kafka_topic.go
- internal/service/kafka/resource_kafka_topic_test.go
- internal/sweep/sweep.go
Recreates missing kafka topics (if service was off and on)
Resolves: #1004.
> recreate missing kafka topics

- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_cassandra.go
adds v0 stateupgrader for Cassandra
> feat(stateupgrader): cassandra v0

- CHANGELOG.md
> release: v3.11.0

- internal/service/account/sweep.go
- internal/service/cassandra/sweep.go
- internal/service/clickhouse/sweep.go
- internal/service/flink/sweep.go
- internal/service/grafana/sweep.go
- internal/service/influxdb/sweep.go
- internal/service/kafka/sweep.go
- internal/service/m3db/sweep.go
- internal/service/mysql/sweep.go
- internal/service/opensearch/sweep.go
- internal/service/pg/sweep.go
- internal/service/project/sweep.go
- internal/service/redis/sweep.go
- internal/service/service_integration/sweep.go
- internal/service/static_ip/sweep.go
- internal/sweep/sweep.go
- internal/sweep/sweep_test.go
Adds service integration endpoints sweeper
> add service integration endpoints sweeper

- CHANGELOG.md
- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_flink.go
adds v0 stateupgrader for Flink
> feat(stateupgrader): flink v0

- CHANGELOG.md
- internal/schemautil/userconfig/stateupgrader/typeupgrader/typeupgrader.go
- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_kafka.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_kafka_connect.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_kafka_mirrormaker.go
- internal/service/kafka/resource_kafka.go
- internal/service/kafka/resource_kafka_connect.go
adds v0 stateupgrader for Kafka
> feat(stateupgrader): kafka v0

- CHANGELOG.md
- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_influxdb.go
adds v0 stateupgrader for InfluxDB
> feat(stateupgrader): influxdb v0

- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_m3aggregator.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_m3db.go
- internal/service/m3db/resource_m3db.go
adds v0 stateupgrader for m3db
> feat(stateupgrader): m3db v0

- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_mysql.go
- internal/service/mysql/resource_mysql.go
adds v0 stateupgrader for MySQL
> feat(stateupgrader): mysql v0

- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_pg.go
- internal/service/pg/resource_pg.go
adds v0 stateupgrader for PostgreSQL
> feat(stateupgrader): pg v0

- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_redis.go
- internal/service/redis/resource_redis.go
adds v0 stateupgrader for Redis
> feat(stateupgrader): redis v0

- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_service_integration.go
- internal/service/service_integration/resource_service_integration.go
adds v0 stateupgrader for Service Integration
> feat(stateupgrader): service integration v0

- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/resource_service_integration_endpoint.go
- internal/service/service_integration/resource_service_integration_endpoint.go
adds v0 stateupgrader for Service Integration Endpoint
> feat(stateupgrader): service integration endpoint v0

- examples/account/accounts.tf
- examples/aws_privatelink/provider.tf
- examples/cassandra_fork/provider.tf
- examples/clickhouse/main.tf
- examples/clickhouse_integrations/kafka_source/provider.tf
- examples/clickhouse_integrations/postgres_source/provider.tf
- examples/datadog/provider.tf
- examples/flink/main.tf
- examples/gcp_marketplace/main.tf
- examples/getting-started.tf
- examples/kafka_connect/provider.tf
- examples/kafka_connectors/mongo_sink/provider.tf
- examples/kafka_connectors/os_sink/provider.tf
- examples/kafka_mirrormaker/provider.tf
- examples/kafka_mirrormaker_bidirectional/main.tf
- examples/kafka_prometheus/provider.tf
- examples/kafka_schemas/provider.tf
- examples/m3/provider.tf
- examples/mysql/provider.tf
- examples/opensearch/provider.tf
- examples/postgres/provider.tf
- examples/service/provider.tf
- examples/static_ips/main.tf
- examples/timescale/main.tf
- sample_project/sample.tf
Update the provider version in examples.
> update tf provider version in examples

- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/cassandra/cassandra.go
- internal/schemautil/userconfig/stateupgrader/v0/flink/flink.go
- internal/schemautil/userconfig/stateupgrader/v0/grafana/grafana.go
- internal/schemautil/userconfig/stateupgrader/v0/influxdb/influxdb.go
- internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka.go
- internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_connect.go
- internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_mirrormaker.go
- internal/schemautil/userconfig/stateupgrader/v0/m3/m3aggregator.go
- internal/schemautil/userconfig/stateupgrader/v0/m3/m3db.go
- internal/schemautil/userconfig/stateupgrader/v0/mysql/mysql.go
- internal/schemautil/userconfig/stateupgrader/v0/opensearch/opensearch.go
- internal/schemautil/userconfig/stateupgrader/v0/pg/pg.go
- internal/schemautil/userconfig/stateupgrader/v0/redis/redis.go
- internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration.go
- internal/schemautil/userconfig/stateupgrader/v0/serviceintegration/service_integration_endpoint.go
refactored `stateupgrader` package structure to match overall repository struct introduced by @ivan-savciuc 
to keep things identical
> refactor(stateupgrader): match with repo struct

- internal/schemautil/schemautil.go
- internal/schemautil/userconfig/stateupgrader/upgraders.go
- internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_topic.go
- internal/service/kafka/kafka_topic.go
adds v0 stateupgrader for Kafka Topic
also adds strict types for some fields in Kafka Topic config
> feat(stateupgrader): kafka topic v0

- internal/schemautil/userconfig/convert.go
- internal/schemautil/userconfig/dist/integration_endpoint_types.go
- internal/schemautil/userconfig/dist/integration_types.go
- internal/schemautil/userconfig/dist/service_types.go
- internal/schemautil/userconfig/handle.go
generates default values for user config options
to make life simpler
> feat(userconfig): default values

- docs/resources/cassandra.md
- docs/resources/clickhouse.md
- docs/resources/flink.md
- docs/resources/grafana.md
- docs/resources/influxdb.md
- docs/resources/kafka.md
- docs/resources/kafka_connect.md
- docs/resources/kafka_mirrormaker.md
- docs/resources/m3aggregator.md
- docs/resources/m3db.md
- docs/resources/mysql.md
- docs/resources/opensearch.md
- docs/resources/pg.md
- docs/resources/redis.md
- docs/resources/service_integration.md
- docs/resources/service_integration_endpoint.md
- internal/schemautil/userconfig/convert.go
- internal/schemautil/userconfig/dist/integration_endpoint_types.go
- internal/schemautil/userconfig/dist/integration_types.go
- internal/schemautil/userconfig/dist/service_types.go
- internal/schemautil/userconfig/handle.go
- internal/schemautil/userconfig/userconfig_test.go
- internal/schemautil/userconfig/util.go
adds support for required fields to userconfig generator
to have required fields in place
> feat(userconfig): required fields

- CHANGELOG.md
> chore: changelog update for v3.12.0

- CHANGELOG.md
- internal/schemautil/schemautil.go
- internal/service/kafka/kafka.go
fixes `default_acl` field incorrect behavior during import operation
to deliver quality product
> fix(kafka): default_acl

- docs/index.md
- templates/index.md
updates version from v3 to v4
to have up-to-date docs in place
> docs(version): update from v3 to v4

- .github/workflows/lint.yml
- CONTRIBUTING.md
Add commitlint to CI 
Standardize commit message prefixes
> ci(lint): add commitlint

- internal/service/account/sweep.go
Fixes not all account sweeping functions operate only on test accounts' objects.
Related accounts objects should only be removed from accounts created by test runs
> fix(sweep): use accounts with test prefix

- CHANGELOG.md
> chore: v4 pre release

- CHANGELOG.md
drops wrong entries from the changelog
these changes are a part of the v3 release, please see the v3 branch:
https://github.com/aiven/terraform-provider-aiven/tree/v3
to have proper changelog
> docs(changelog): drop wrong entries

- CHANGELOG.md
- internal/schemautil/schemautil.go
- internal/service/project/project.go
Fixes project `add_account_owners_admin_access` option.
> fix(project): add_account_owners_admin_access

- CHANGELOG.md
- docs/data-sources/flink_application_version.md
- docs/resources/flink_application_version.md
- internal/service/flink/flink_application_version.go
- internal/service/flink/flink_application_version_test.go
Renaming sinks to sink and sources to source to make it in line with other set fields in other resources.
> feat: rename flink application version field from plural singular

- docs/resources/flink.md
- examples/resources/aiven_flink/resource.tf
Fixes flink version in example. 1.15 is not supported anymore.
> fix(docs): update flink example version

- Makefile
fixes incorrect project structure specified in acctest make target
to have them working
> ci(acctest): fix project structure

- internal/sdkprovider/provider/provider.go
fixes imports in sdkprovider
it was incorrect
> refactor(sdkprovider): fix imports

- internal/sdkprovider/service/account/sweep.go
- internal/sdkprovider/service/cassandra/sweep.go
- internal/sdkprovider/service/clickhouse/sweep.go
- internal/sdkprovider/service/flink/sweep.go
- internal/sdkprovider/service/grafana/sweep.go
- internal/sdkprovider/service/influxdb/sweep.go
- internal/sdkprovider/service/kafka/sweep.go
- internal/sdkprovider/service/m3db/sweep.go
- internal/sdkprovider/service/mysql/sweep.go
- internal/sdkprovider/service/opensearch/sweep.go
- internal/sdkprovider/service/pg/sweep.go
- internal/sdkprovider/service/project/sweep.go
- internal/sdkprovider/service/redis/sweep.go
- internal/sdkprovider/service/serviceintegration/sweep.go
- internal/sdkprovider/service/staticip/sweep.go
- internal/sweep/sweep.go
> fix(sweep): import path in dependant modules

- CHANGELOG.md
> chore(release): v4.1.1

- CHANGELOG.md
- internal/service/kafka/kafka_topic_create.go
- internal/service/kafka/kafka_topic_test.go
> chore(release): v3.13.1

- .goreleaser.yml
- go.mod
- go.sum
- internal/acctest/acctest.go
- internal/acctest/provider_test.go
- internal/provider/provider.go
- internal/provider/provider_test.go
- internal/schemautil/service.go
- internal/sdkprovider/provider/provider.go
- main.go
adds new framework boilerplate
to begin moving to the new framework
> feat(provider): new framework boilerplate

- CHANGELOG.md
releases v4.1.2
to ship recent bug fixes
> chore(release): v4.1.2

- CHANGELOG.md
returns missing header in changelog
it's essential
> chore(changelog): return missing header

- CHANGELOG.md
- main.go
releases v4.1.3
resolves #1104
to fix it
> chore(release): v4.1.3

- CHANGELOG.md
- docs/data-sources/m3db.md
- docs/resources/m3db.md
- docs/resources/mysql.md
- docs/resources/opensearch.md
- docs/resources/pg.md
- docs/resources/redis.md
- go.mod
- go.sum
- internal/schemautil/userconfig/dist/service_types.go
- main.go
Adds `aiven_m3db` specific configuration options.
> feat(m3db): add configuration options

- CHANGELOG.md
- examples/gcp_vpc_peering/project.tf
- examples/gcp_vpc_peering/provider.tf
- examples/gcp_vpc_peering/variables.tf
add gcp virtual network peering example
https://github.com/aiven/devportal/pull/1844
> add gcp virtual network peering example

- CHANGELOG.md
releases v4.2.1
rolling out fixes and improvements
> chore(release): v4.2.1

- CHANGELOG.md
- docs/data-sources/service_integration_endpoint.md
- docs/resources/service_integration_endpoint.md
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
adds docs for `aiven_service_integration_endpoint`'s `endpoint_type` field, as well as validation for it
resolves https://github.com/aiven/terraform-provider-aiven/issues/1116
to have the issue addressed :)
> docs(service_integration_endpoint): endpoint_type

- CHANGELOG.md
- internal/sdkprovider/service/account/account_authentication.go
- internal/sdkprovider/service/account/account_authentication_test.go
Fix account authentication SAML field mapping set method
> fix(account): authentication SAML field mapping set

- CHANGELOG.md
- docs/data-sources/opensearch.md
- docs/resources/mysql.md
- docs/resources/opensearch.md
- docs/resources/service_integration.md
- docs/resources/service_integration_endpoint.md
- internal/schemautil/userconfig/dist/integration_endpoint_types.go
- internal/schemautil/userconfig/dist/integration_types.go
- internal/schemautil/userconfig/dist/service_types.go
- internal/schemautil/userconfig/userconfig_test.go
- `required` was not generated for top level fields previously
- this PR also updates userconfig options to the latest
TODO: automate this the same way we have it in https://github.com/aiven/aiven-operator
found while investigating #1142 
to ensure consistency
> fix(userconfig): required for top level fields

- .github/workflows/userconfig-generate-schema.yml
adds `userconfig-generate-schema.yml` workflow
currently, when dependabot's PRs are merged, we need to manually run `go generate ./...`
this PR makes the whole update process fully automatic
> ci: add userconfig-generate-schema.yml workflow

- docs/resources/cassandra_user.md
- docs/resources/clickhouse_user.md
- docs/resources/influxdb_user.md
- docs/resources/kafka_user.md
- docs/resources/m3db_user.md
- docs/resources/mysql_user.md
- docs/resources/opensearch_user.md
- docs/resources/redis_user.md
- examples/data-sources/aiven_elasticsearch/data-source.tf
- examples/data-sources/aiven_elasticsearch_acl/data-source.tf
- examples/data-sources/aiven_elasticsearch_acl_config/data-source.tf
- examples/data-sources/aiven_elasticsearch_acl_rule/data-source.tf
- examples/resources/aiven_cassandra_user/import.sh
- examples/resources/aiven_clickhouse_user/import.sh
- examples/resources/aiven_influxdb_user/import.sh
- examples/resources/aiven_kafka_user/import.sh
- examples/resources/aiven_m3db_user/import.sh
- examples/resources/aiven_mysql_user/import.sh
- examples/resources/aiven_opensearch_user/import.sh
- examples/resources/aiven_redis_user/import.sh
- adds missing import statements for various resources
- fixes `aiven_clickhouse_user` import statement
- removes deprecated data source examples
to improve the docs 🚀
> docs: add missing import statements

- CHANGELOG.md
> chore(release): v4.3.0

- .github/workflows/userconfig-generate-schema.yml
also runs `make docs` when generating userconfig schema
it's missing ☹️
> ci(userconfig-generate-schema): run make docs

- CHANGELOG.md
> chore(release): v4.4.0

- CHANGELOG.md
- internal/sdkprovider/service/kafka/kafka_schema.go
> fix(kafka_schema): suppress diff schema_type on resource import

- CHANGELOG.md
> chore: update changelog for v4.4.1 release

- CHANGELOG.md
- internal/service/kafka/kafka_topic_cache.go
- internal/service/kafka/kafka_topic_wait.go
Fix kafka topic error handling
> fix(kafka_topic): fix kafka topic 404 error handling

- CHANGELOG.md
> chore(release): v4.5.0

- internal/sdkprovider/service/vpc/project_vpc_test.go
fixes free tier error in VPC tests
make VPC tests better
> test(vpc): fix free tier error

- CHANGELOG.md
- go.mod
- go.sum
- internal/sdkprovider/provider/provider.go
- internal/sdkprovider/service/flink/flink_application_deployment.go
- internal/sdkprovider/service/flink/flink_application_version_test.go
adds `aiven_flink_application_deployment` resource
to have it in place
> feat(flink): application deployment

- docs/data-sources/opensearch_user.md
- internal/sdkprovider/service/opensearch/opensearch_user_data_source.go
> fix(opensearch): typo

- CHANGELOG.md
- docs/data-sources/billing_group.md
- docs/data-sources/project.md
- docs/resources/billing_group.md
- docs/resources/project.md
- internal/sdkprovider/service/project/billing_group.go
- internal/sdkprovider/service/project/project.go
- internal/sdkprovider/service/project/project_test.go
- internal/sdkprovider/service/project/util.go
rename `owner_entity_id` to `parent_id`
n.b. we are safe to do that because it wasn't released yet
it was mistakenly called this way
> chore(project): rename owner_entity_id to parent_id

- .github/workflows/acceptance-tests.yml
- .github/workflows/examples-tests.yml
- .github/workflows/lint.yml
- .github/workflows/release-artifacts.yml
- .github/workflows/sweep.yml
- .github/workflows/unit-tests.yml
- go.mod
- tools/go.mod
> chore(go): upgrade go 1.19

- CHANGELOG.md
- internal/sdkprovider/provider/provider.go
- internal/sdkprovider/service/organization/organization_user.go
- internal/sdkprovider/service/organization/organization_user_data_source.go
- internal/sdkprovider/service/organization/organization_user_data_source_test.go
- internal/sdkprovider/service/organization/organization_user_test.go
adds organization user resource and data source
to have them in place
> feat(organization): user resource and data source

- CHANGELOG.md
releases v4.7.0
to have it in place :)
> chore(release): v4.7.0

- CHANGELOG.md
- internal/sdkprovider/service/vpc/aws_privatelink_test.go
- internal/sdkprovider/service/vpc/azure_privatelink_connection_approve_test.go
fixes Privatelink typo
discovered in #931
we don't need typos in our project
> chore: fix Privatelink typo

- CHANGELOG.md
- internal/sdkprovider/provider/provider.go
- internal/sdkprovider/service/vpc/azure_privatelink_connection_approve.go
- internal/sdkprovider/service/vpc/azure_privatelink_connection_approve_test.go
- internal/sdkprovider/service/vpc/azure_privatelink_test.go
- internal/sdkprovider/service/vpc/gcp_privatelink.go
- internal/sdkprovider/service/vpc/gcp_privatelink_connection_approve.go
- internal/sdkprovider/service/vpc/gcp_privatelink_data_source.go
- internal/sdkprovider/service/vpc/gcp_privatelink_test.go
- internal/sdkprovider/service/vpc/util_test.go
adds GCP private service connect (Privatelink) support
to make it happen :)
> feat(vpc): gcp privatelink

- CHANGELOG.md
> chore(release): v4.8.0

- internal/provider/provider.go
- internal/sdkprovider/provider/provider.go
- main.go
fix failing build of the framework provider
we need to have it working
> fix(frameworkprovider): failing build

- .github/workflows/acceptance-tests.yml
> chore(tests): run organization tests

- CHANGELOG.md
- internal/sdkprovider/service/account/account.go
fix deletion flakiness in `account` resource
we want it to work :)
> fix(account): deletion flakiness

- internal/sdkprovider/service/account/account_test.go
- internal/sdkprovider/service/organization/organization_test.go
- internal/sdkprovider/service/project/project_test.go
fixes a problem with the acceptance tests: https://github.com/aiven/terraform-provider-aiven/actions/runs/5861938399
tests were broken by an API breaking change
> test(project): broken without account or organization link

- internal/schemautil/schemautil.go
- internal/sdkprovider/service/kafka/kafka_schema.go
Simplify Kafka schema import logic 
discovered in #1245
> refactor(kafka_schema): simplify kafka schema import

- .github/workflows/userconfig-generate-schema.yml
- CHANGELOG.md
- Makefile
- docs/data-sources/kafka.md
- docs/data-sources/kafka_connect.md
- docs/data-sources/opensearch.md
- docs/resources/kafka.md
- docs/resources/kafka_connect.md
- docs/resources/opensearch.md
- go.mod
- go.sum
- internal/schemautil/userconfig/dist/service_types.go
> chore: update user config schemas

- CHANGELOG.md
> release: v4.8.0

- go.mod
- go.sum
- internal/schemautil/userconfig/apiconvert/fromapi_test.go
- main.go
> fix: remove beta properties

- internal/sdkprovider/provider/provider.go
Fixes sdk provider configuration.
> fix: sdk provider config

- CHANGELOG.md
- internal/schemautil/mutations.go
Fix IP filter migrations error. Resolves #1297
> fix(migrations): ip filter migrations

- CHANGELOG.md
- internal/schemautil/userconfig/apiconvert/toapi.go
- internal/schemautil/userconfig/apiconvert/toapi_test.go
fixes improper omitting in `ToAPI` method of `apiconvert`
it doesn't works properly
> fix(apiconvert): toapi improper omitting

- CHANGELOG.md
> chore(release): v4.9.0

- .github/workflows/codeql.yml
> fix(ci): codeql job

- CHANGELOG.md
- internal/sdkprovider/service/project/project_user.go
Fix 409 project user error handling
> fix(project_user): invite error handling

- CHANGELOG.md
> chore(release): v4.9.1

- CHANGELOG.md
- internal/sdkprovider/service/organization/organization_user.go
Fixes `create_time` serialization.
> fix(organization_user): serialize create_time to string

- .github/workflows/userconfig-generate-schema.yml
> ci: fix code generation

- internal/sdkprovider/service/project/billing_group_test.go
fixes failing [billing group test](https://github.com/aiven/terraform-provider-aiven/actions/runs/6567987251/job/17841682556)
to have it working
> test: fix failing billing group test

- internal/sdkprovider/service/project/project_user_test.go
fix failing project tests
to make them work
> test(project): fix failing tests

- internal/sdkprovider/service/project/project_user_test.go
fix project test missing organization link in second step
to make the test work
> test(project): fix missing organization link

- internal/sdkprovider/service/kafkatopic/kafka_topic.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_cache.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_exists.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_wait.go
Fix Kafka Topic create and read performance
> Kafka Topic performance improvements for v4

- CHANGELOG.md
> v4.9.3 pre-release

- CHANGELOG.md
> chore(changelog): fix typo

- CHANGELOG.md
- docs/data-sources/mirrormaker_replication_flow.md
- docs/resources/mirrormaker_replication_flow.md
- go.mod
- go.sum
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow_test.go
adds `emit_backward_heartbeats_enabled` field support
to have it in place
> feat(mirrormaker): add emit_backward_heartbeats_enabled field support

- CHANGELOG.md
- docs/data-sources/service_integration_endpoint.md
- docs/resources/service_integration_endpoint.md
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
Adds `external_postgresql` and `external_google_cloud_bigquery` service integration endpoints
> feat: add external_postgresql and external_google_cloud_bigquery

- internal/sdkprovider/service/project/sweep.go
adds billing group support for sweeper
to avoid congesting the organizations with irrelevant billing groups
> feat(sweeper): add billing group support

- CHANGELOG.md
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
A workaround to fix API race issues.
> fix(mirrormaker_replication_flow): race on create/update/delete operations

- CHANGELOG.md
- internal/sdkprovider/kafkatopicrepository/create.go
- internal/sdkprovider/kafkatopicrepository/create_test.go
Fixes kafka topic creation error.
> fix(kafka_topic): retry creation

- CHANGELOG.md
- internal/schemautil/userconfig/stateupgrader/v0/kafka/kafka_topic.go
Fix Kafka Topic migration from v3 to v4
> fix(kafka_topic): migration from v3

- CHANGELOG.md
> chore(release): v4.10.0

- CHANGELOG.md
Fixes change log after auto merge
> chore(changelog): fix after automerge

- CHANGELOG.md
> chore(changelog): 4.11.0 release notes

- CHANGELOG.md
> chore(release): v4.12.0

- CHANGELOG.md
- go.mod
- go.sum
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
Fixes kafka topic read of optional fields.
> fix(kafka_topic): config optional fields

- internal/sdkprovider/service/vpc/sweep.go
- internal/sweep/sweep_test.go
> test: enable vpc sweepers

- CHANGELOG.md
> chore(release): v4.13.0

- Makefile
- internal/sdkprovider/service/account/sweep.go
- internal/sdkprovider/service/cassandra/sweep.go
- internal/sdkprovider/service/clickhouse/sweep.go
- internal/sdkprovider/service/connectionpool/sweep.go
- internal/sdkprovider/service/flink/sweep.go
- internal/sdkprovider/service/grafana/sweep.go
- internal/sdkprovider/service/influxdb/sweep.go
- internal/sdkprovider/service/kafka/sweep.go
- internal/sdkprovider/service/m3db/sweep.go
- internal/sdkprovider/service/mysql/sweep.go
- internal/sdkprovider/service/opensearch/sweep.go
- internal/sdkprovider/service/organization/sweep.go
- internal/sdkprovider/service/pg/sweep.go
- internal/sdkprovider/service/project/sweep.go
- internal/sdkprovider/service/redis/sweep.go
- internal/sdkprovider/service/serviceintegration/sweep.go
- internal/sdkprovider/service/staticip/sweep.go
- internal/sdkprovider/service/vpc/sweep.go
- internal/sweep/sweep.go
- internal/sweep/sweep_test.go
Add support for sweepers check, that validates if all resources have sweepers (with some known exceptions)
> test: add sweepers check

- CHANGELOG.md
- internal/sdkprovider/service/organization/organization_user_data_source.go
Fix `aiven_organization_user` datasource get method
> fix(org): org user datasource

- CHANGELOG.md
- docs/resources/organization_user.md
- internal/sdkprovider/service/organization/organization_user.go
> chore: release 4.13.1

- CHANGELOG.md
- internal/plugin/service/organization/organization_application_user.go
- internal/plugin/service/organization/organization_user_group_member.go
Fix org user and group model fill
> fix(org): org user and group member model fill

- docs/resources/kafka_topic.md
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
> docs(kafka_topic): fix local_retention field desc

- CHANGELOG.md
> chore: release 4.13.2

- docs/resources/organization_application_user.md
- internal/plugin/service/organization/organization_application_user.go
Add more info to the application users description about this feature and that it is in the LA stage.
> docs: update app users description

- docs/data-sources/billing_group.md
- docs/resources/billing_group.md
- internal/sdkprovider/service/project/billing_group.go
- internal/sdkprovider/service/project/billing_group_data_source.go
Refine the documentation for billing group resource and data source.
> docs: improve descriptions for billing groups

- CHANGELOG.md
- internal/plugin/service/organization/organization_user_group_member.go
> fix(org): removal of org group member

- .github/workflows/acceptance-tests.yml
- .github/workflows/examples-tests.yml
adds missing `fetch-depth` to workflows
it's better to have it than the other way around
> ci(checkout): add missing fetch-depth

- README.md
- docs/guides/creating-static-ip-addresses.md
- docs/index.md
- examples/organization/README.md
- examples/organization/org_units_projects.tf
- examples/organization/secrets.tfvars.tmp
- internal/sdkprovider/service/kafka/kafka.go
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
- internal/sdkprovider/service/vpc/azure_vpc_peering_connection_test.go
- templates/guides/creating-static-ip-addresses.md
- templates/index.md
Minor fixes to the organizations example to update links to the new docs site and fix example project names.
> docs: fix links and project names

- docs/guides/examples.md
- templates/guides/examples.md
> fix(docs): fix examples list links

- CHANGELOG.md
> chore(release): v4.14.0

- CHANGELOG.md
- internal/sdkprovider/service/kafkaschema/kafka_schema.go
fixes `kafka_schema` Protobuf normalization
the test was failing, the normalization mechanism wasn't perfect
> fix(kafka_schema): protobuf normalization

- .github/workflows/acceptance-tests.yml
- .github/workflows/examples-tests.yml
adds `setup-go` step to the `selproj` jobs that we have
it was missing 🤷
> ci(selproj): add setup-go step

- docs/data-sources/organizational_unit.md
- docs/resources/organizational_unit.md
- examples/data-sources/aiven_organizational_unit/data-source.tf
- examples/resources/aiven_organizational_unit/import.sh
- examples/resources/aiven_organizational_unit/resource.tf
- internal/sdkprovider/service/organization/organizational_unit.go
- internal/sdkprovider/service/organization/organizational_unit_data_source.go
Add link to conceptual documentation and align examples/import with new standard format.
> docs: update org units resource and data source

- docs/index.md
- templates/index.md
Adds a section on environment variables that can be set for the provider plus some updates to the rest of the main page text and conceptual information.
> docs: add environment variables to main page

- .github/workflows/incremental-acceptance-tests.yml
adds incremental `acctest` support, which runs the acceptance tests following this algorithm:
- if resource/datasource X changed, it will run all the acceptance tests where the resource/datasource is used
- if a dependency of resource/datasource X is changed, it will run all the acceptance tests where the resource/datasource is used
- if a test of resource/datasource X is changed, it will find all resources/datasources that are used in the changed test, and will run their tests too
it works by iterating through the dependency tree, comparing the current Git changes, and pattern matching to find tests that are needed
changes were made in the following files:
- `internal/sdkprovider/kafkatopicrepository/repository.go`
- `internal/plugin/service/organization/organization_application_user_toke …
> test(acctest): incremental run support

- CHANGELOG.md
> chore(release): v4.15.0

- CHANGELOG.md
- internal/common/client.go
- internal/schemautil/database.go
- internal/schemautil/wait.go
- internal/sdkprovider/service/kafka/kafka_connector.go
- internal/sdkprovider/service/pg/pg.go
- internal/sdkprovider/service/project/project.go
- internal/sdkprovider/service/serviceintegration/service_integration.go
- internal/sdkprovider/service/staticip/static_ip.go
- internal/sdkprovider/service/vpc/aws_privatelink.go
- internal/sdkprovider/service/vpc/aws_vpc_peering_connection.go
- internal/sdkprovider/service/vpc/azure_privatelink.go
- internal/sdkprovider/service/vpc/azure_privatelink_connection_approve.go
- internal/sdkprovider/service/vpc/azure_vpc_peering_connection.go
- internal/sdkprovider/service/vpc/gcp_privatelink.go
- internal/sdkprovider/service/vpc/gcp_privatelink_connection_approve.go
- internal/sdkprovider/service/vpc/gcp_vpc_peering_connection.go
- internal/sdkprovider/service/vpc/project_vpc.go
- internal/sdkprovider/service/vpc/vpc_peering_connection.go
- unifies delay and mintimeout values in all statechangeconf instances
- fixes incorrect timeout values used in some resources
qol improvement
> chore(statechangeconf): unified delay and mintimeout values

- docs/data-sources/kafka.md
- docs/data-sources/kafka_topic.md
- docs/resources/kafka.md
- docs/resources/kafka_topic.md
- examples/data-sources/aiven_kafka/data-source.tf
- examples/data-sources/aiven_kafka_topic/data-source.tf
- examples/resources/aiven_kafka/import.sh
- examples/resources/aiven_kafka/resource.tf
- examples/resources/aiven_kafka_topic/import.sh
- examples/resources/aiven_kafka_topic/resource.tf
- internal/sdkprovider/service/kafka/kafka.go
- internal/sdkprovider/service/kafka/kafka_data_source.go
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_data_source.go
Update descriptions and examples for Kafka and Kafka topic documentation.
> docs: update kafka and topic documentation

- docs/resources/cassandra.md
- docs/resources/opensearch.md
- docs/resources/service_integration.md
- internal/sdkprovider/userconfig/service/cassandra.go
- internal/sdkprovider/userconfig/service/opensearch.go
- internal/sdkprovider/userconfig/serviceintegration/metrics.go
- internal/sdkprovider/userconfig/serviceintegration/prometheus.go
- ucgenerator/main.go
Generates user config description with leading uppercase letter.
> docs(userconfig): uppercase first description letter

- CHANGELOG.md
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
- Doesn't submit kafka topic config default values 
- Fix sending `false` values in kafka topic config
> fix(kafka_topic): send false values

- CHANGELOG.md
- internal/sdkprovider/kafkatopicrepository/read.go
- internal/sdkprovider/kafkatopicrepository/repository.go
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
- internal/sdkprovider/service/kafkatopic/kafka_topic_test.go
Validates topic conflicts on plan command.
> feat(aiven_kafka_topic): validate conflict on plan

- CHANGELOG.md
- internal/schemautil/service.go
Removes redundant code block for generic service.
> chore: remove generic service connection info

- .github/workflows/incremental-acceptance-tests.yml
Changes the approach that runs the test files.
Current approach fails to share functions across the same package.
> ci(incacctest): different running approach

- .github/workflows/incremental-acceptance-tests.yml
Adds a result job in the Incremental Acceptance Tests workflow.
To be able to set up status check dependencies.
> ci(incacctest): add result job

- CHANGELOG.md
- docs/resources/kafka.md
- docs/resources/kafka_connect.md
- docs/resources/pg.md
- docs/resources/service_integration_endpoint.md
- internal/sdkprovider/userconfig/converters/converters.go
- internal/sdkprovider/userconfig/converters/utils.go
- internal/sdkprovider/userconfig/converters/utils_test.go
- internal/sdkprovider/userconfig/diff/diff.go
- internal/sdkprovider/userconfig/service/kafka.go
- internal/sdkprovider/userconfig/service/kafka_connect.go
- internal/sdkprovider/userconfig/service/pg.go
- internal/sdkprovider/userconfig/service/service.go
- internal/sdkprovider/userconfig/serviceintegration/serviceintegration.go
- internal/sdkprovider/userconfig/serviceintegrationendpoint/external_google_cloud_bigquery.go
- internal/sdkprovider/userconfig/serviceintegrationendpoint/external_google_cloud_logging.go
- internal/sdkprovider/userconfig/serviceintegrationendpoint/serviceintegrationendpoint.go
- ucgenerator/main.go
- ucgenerator/models.go
Adds ability to override empty maps.
> feat(userconfigs): expand maps

- CHANGELOG.md
> chore(release): v4.16.0

- CHANGELOG.md
- internal/sdkprovider/service/kafka/kafka_connector.go
Fixes kafka connector create error.
> fix(kafka_connector): ignore 201 create error

- CHANGELOG.md
- docs/resources/organization_application_user.md
- docs/resources/organization_application_user_token.md
- internal/plugin/provider.go
- internal/plugin/service/organization/organization_application_user.go
- internal/plugin/service/organization/organization_application_user_token.go
Removes beta flag from app users and tokens
> feat: remove beta flag from app users and tokens

- CHANGELOG.md
> chore(release): v4.17.0

- docs/index.md
- templates/index.md
Added frontmatter to the homepage for the docs.
> docs: add frontmatter to docs homepage

- CHANGELOG.md
- internal/sdkprovider/userconfig/converters/converters.go
- internal/sdkprovider/userconfig/converters/utils.go
- internal/sdkprovider/userconfig/converters/utils_test.go
Converts `ip_filter` values into the target type.
> fix: convert ip_filter values into the target type

- .github/workflows/incremental-acceptance-tests.yml
Adds a comment to temporarily disable incremental acceptance tests until the team exapnds.
Currently, there's no need for them.
> chore(incacctests): temporarily disable

- CHANGELOG.md
> chore(release): v4.18.0

- CHANGELOG.md
- docs/data-sources/mirrormaker_replication_flow.md
- docs/resources/mirrormaker_replication_flow.md
- go.mod
- go.sum
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow_test.go
- Add `aiven_mirrormaker_replication_flow` replication factor
- Remove `aiven_mirrormaker_replication_flow` global mutex, the backend has been fixed
> feat(aiven_mirrormaker_replication_flow): add replication factor

- CHANGELOG.md
- docs/resources/cassandra.md
- docs/resources/flink.md
- docs/resources/kafka.md
- docs/resources/m3aggregator.md
- docs/resources/m3db.md
- docs/resources/mysql.md
- docs/resources/opensearch.md
- docs/resources/pg.md
- docs/resources/redis.md
- internal/sdkprovider/userconfig/service/cassandra.go
- internal/sdkprovider/userconfig/service/flink.go
- internal/sdkprovider/userconfig/service/kafka.go
- internal/sdkprovider/userconfig/service/m3aggregator.go
- internal/sdkprovider/userconfig/service/m3db.go
- internal/sdkprovider/userconfig/service/mysql.go
- internal/sdkprovider/userconfig/service/opensearch.go
- internal/sdkprovider/userconfig/service/pg.go
- internal/sdkprovider/userconfig/service/redis.go
- ucgenerator/main.go
- ucgenerator/models.go
Allows to run new service versions.
> refactor: remove service version validations

- CHANGELOG.md
> chore(release): v4.19.0

- CHANGELOG.md
> chore(release): v4.19.1

- CHANGELOG.md
- go.mod
- go.sum
Include https://github.com/aiven/aiven-go-client/commit/0a97dd47f14a98754e3e5e7e666544103c22dea3
> fix(deps): use correct aiven-go-client version

- docs/data-sources/project.md
- docs/resources/organization.md
- docs/resources/organization_group_project.md
- docs/resources/organization_user_group.md
- docs/resources/organization_user_group_member.md
- docs/resources/organizational_unit.md
- docs/resources/project.md
- examples/organization/README.md
- internal/plugin/service/organization/organization_group_project.go
- internal/plugin/service/organization/organization_resource.go
- internal/plugin/service/organization/organization_user_group_member.go
- internal/sdkprovider/service/organization/organization_user_group.go
- internal/sdkprovider/service/organization/organizational_unit.go
- internal/sdkprovider/service/project/project.go
> docs: fix broken links to conceptual docs

- CHANGELOG.md
- docs/resources/grafana.md
- docs/resources/service_integration_endpoint.md
- internal/sdkprovider/userconfig/service/grafana.go
- internal/sdkprovider/userconfig/serviceintegrationendpoint/external_aws_cloudwatch_logs.go
- internal/sdkprovider/userconfig/serviceintegrationendpoint/external_aws_cloudwatch_metrics.go
- ucgenerator/main.go
Marks sensitive fields to mask values in the output.
> feat(userconfigs): mark sensitive fields

- internal/sdkprovider/service/account/account_team_data_source_test.go
- internal/sdkprovider/service/account/account_team_member_data_source_test.go
- internal/sdkprovider/service/account/account_team_member_test.go
- internal/sdkprovider/service/account/account_team_project_test.go
- internal/sdkprovider/service/account/account_team_test.go
> chore: skip account team tests

- internal/sdkprovider/service/serviceintegration/service_integration_endpoint_test.go
Fixes `TestAccAivenServiceIntegrationEndpointExternalPostgresql` test.
> fix(tests): ssl_mode is required

- CHANGELOG.md
> chore(release): v4.20.0

- docs/data-sources/flink.md
- docs/data-sources/flink_application.md
- docs/data-sources/flink_application_version.md
- docs/resources/flink.md
- docs/resources/flink_application.md
- docs/resources/flink_application_deployment.md
- docs/resources/flink_application_version.md
- examples/data-sources/aiven_flink/data-source.tf
- examples/data-sources/aiven_flink_application/data-source.tf
- examples/data-sources/aiven_flink_application_version/data-source.tf
- examples/resources/aiven_flink/import.sh
- examples/resources/aiven_flink/resource.tf
- examples/resources/aiven_flink_application/import.sh
- examples/resources/aiven_flink_application/resource.tf
- examples/resources/aiven_flink_application_deployment/import.sh
- examples/resources/aiven_flink_application_deployment/resource.tf
- examples/resources/aiven_flink_application_version/import.sh
- examples/resources/aiven_flink_application_version/resource.tf
- internal/sdkprovider/service/flink/flink.go
- internal/sdkprovider/service/flink/flink_application.go
- internal/sdkprovider/service/flink/flink_application_data_source.go
- internal/sdkprovider/service/flink/flink_application_deployment.go
- internal/sdkprovider/service/flink/flink_application_version.go
- internal/sdkprovider/service/flink/flink_application_version_data_source.go
- internal/sdkprovider/service/flink/flink_data_source.go
Align docs for the Flink resources and data sources with style guide and link to some conceptual docs.
> docs(flink): improve Flink docs

- CHANGELOG.md
- go.mod
- go.sum
- internal/sdkprovider/provider/provider.go
- internal/sdkprovider/service/thanos/thanos.go
- internal/sdkprovider/service/thanos/thanos_data_source.go
- internal/sdkprovider/service/valkey/valkey.go
- internal/sdkprovider/service/valkey/valkey_data_source.go
- internal/sdkprovider/service/valkey/valkey_user.go
- internal/sdkprovider/service/valkey/valkey_user_data_source.go
Adds beta to description automatically.
> refactor: auto beta description

- CHANGELOG.md
> chore(release): v4.22.0

- CHANGELOG.md
- docs/data-sources/account_team_project.md
- docs/data-sources/mysql_user.md
- docs/data-sources/project_user.md
- docs/data-sources/project_vpc.md
- docs/resources/account_team_project.md
- docs/resources/mysql_user.md
- docs/resources/project_user.md
- docs/resources/project_vpc.md
- internal/plugin/service/organization/organization_group_project.go
- internal/schemautil/userconfig/desc.go
- internal/sdkprovider/service/account/account_authentication.go
- internal/sdkprovider/service/account/account_team_project.go
- internal/sdkprovider/service/connectionpool/connection_pool.go
- internal/sdkprovider/service/kafka/kafka_acl.go
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
- internal/sdkprovider/service/kafkaschema/kafka_schema.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_configuration.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl.go
- internal/sdkprovider/service/mysql/mysql_user.go
- internal/sdkprovider/service/opensearch/opensearch_acl_rule.go
- internal/sdkprovider/service/project/project_user.go
- internal/sdkprovider/service/vpc/project_vpc.go
- internal/sdkprovider/service/vpc/project_vpc_data_source.go
This way TF will get all new values automatically.
> fix: use code-generated enum choices

- docs/data-sources/pg.md
- docs/data-sources/pg_database.md
- docs/data-sources/pg_user.md
- docs/resources/pg.md
- docs/resources/pg_database.md
- docs/resources/pg_user.md
- examples/data-sources/aiven_pg/data-source.tf
- examples/data-sources/aiven_pg_database/data-source.tf
- examples/data-sources/aiven_pg_user/data-source.tf
- examples/resources/aiven_pg/import.sh
- examples/resources/aiven_pg/resource.tf
- examples/resources/aiven_pg_database/import.sh
- examples/resources/aiven_pg_database/resource.tf
- examples/resources/aiven_pg_user/import.sh
- examples/resources/aiven_pg_user/resource.tf
- internal/sdkprovider/service/pg/pg.go
- internal/sdkprovider/service/pg/pg_data_source.go
- internal/sdkprovider/service/pg/pg_database.go
- internal/sdkprovider/service/pg/pg_database_data_source.go
- internal/sdkprovider/service/pg/pg_user.go
- internal/sdkprovider/service/pg/pg_user_data_source.go
Improves docs for PG service, database, and service user resources.
> docs: improve pg documentation

- CHANGELOG.md
> chore(release): v4.23.0

- CHANGELOG.md
> chore(release): v4.24.0

- internal/sdkprovider/service/project/project_user_data_source_test.go
- internal/sdkprovider/service/project/project_user_test.go
Disables project user tests. Users can no longer be created.
> chore: disable project user tests

- CHANGELOG.md
- docs/resources/opensearch.md
- docs/resources/pg.md
- docs/resources/thanos.md
- go.mod
- go.sum
- internal/common/client.go
- internal/schemautil/helpers.go
- internal/schemautil/service.go
- internal/sdkprovider/service/opensearch/opensearch.go
- internal/sdkprovider/service/pg/pg.go
- internal/sdkprovider/service/thanos/thanos.go
- internal/sdkprovider/service/thanos/thanos_test.go
Usese `ServiceGet` from generated client. Requests secrets.
> feat: use generated service get

- CHANGELOG.md
- go.mod
- internal/sdkprovider/service/serviceintegration/service_integration.go
- internal/sdkprovider/service/serviceintegration/service_integration_data_source.go
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint.go
- internal/sdkprovider/service/serviceintegration/service_integration_endpoint_data_source.go
> feat: use codegen client with service integrations

- CHANGELOG.md
- internal/sdkprovider/service/kafka/kafka_connector.go
One minutes is not enough https://github.com/aiven/terraform-provider-aiven/actions/runs/10821614984/job/30024000684#step:6:61
> fix(aiven_kafka_connector): increase create polling timeout

- docs/data-sources/connection_pool.md
- docs/data-sources/grafana.md
- docs/data-sources/m3db.md
- docs/data-sources/m3db_user.md
- docs/resources/connection_pool.md
- docs/resources/grafana.md
- docs/resources/m3db.md
- docs/resources/m3db_user.md
- examples/data-sources/aiven_connection_pool/data-source.tf
- examples/data-sources/aiven_grafana/data-source.tf
- examples/data-sources/aiven_m3db/data-source.tf
- examples/data-sources/aiven_m3db_user/data-source.tf
- examples/resources/aiven_connection_pool/import.sh
- examples/resources/aiven_connection_pool/resource.tf
- examples/resources/aiven_grafana/import.sh
- examples/resources/aiven_grafana/resource.tf
- examples/resources/aiven_m3db/import.sh
- examples/resources/aiven_m3db/resource.tf
- examples/resources/aiven_m3db_user/import.sh
- examples/resources/aiven_m3db_user/resource.tf
- internal/sdkprovider/service/connectionpool/connection_pool.go
- internal/sdkprovider/service/connectionpool/connection_pool_data_source.go
- internal/sdkprovider/service/grafana/grafana.go
- internal/sdkprovider/service/grafana/grafana_data_source.go
- internal/sdkprovider/service/m3db/m3db.go
- internal/sdkprovider/service/m3db/m3db_data_source.go
- internal/sdkprovider/service/m3db/m3db_user.go
- internal/sdkprovider/service/m3db/m3db_user_data_source.go
Aligns documentation for M3DB, Grafana, and PG connection pooling resources and data sources with the style guide
> docs: improve M3, Grafana, connection pools

- CHANGELOG.md
> chore(release): v4.25.0

- CHANGELOG.md
> chore(release): v4.26.0

- docs/data-sources/account_team_project.md
- docs/data-sources/project_user.md
- docs/resources/account_team_project.md
- docs/resources/organization_group_project.md
- docs/resources/organization_permission.md
- docs/resources/project_user.md
- go.mod
- go.sum
- internal/schemautil/schemautil.go
- internal/sdkprovider/service/mysql/mysql_user.go
- internal/sdkprovider/service/serviceintegration/service_integration.go
- internal/sdkprovider/service/serviceintegration/service_integration_data_source.go
- internal/sdkprovider/service/valkey/valkey_user.go
The updated client doesn't have `serviceuser` module anymore.
> refactor: replace avngen serviceuser

- CHANGELOG.md
> chore(release): v4.27.0

- CHANGELOG.md
- docs/data-sources/kafka_schema.md
- docs/data-sources/kafka_schema_configuration.md
- docs/resources/kafka_schema.md
- go.mod
- go.sum
- internal/sdkprovider/service/kafkaschema/kafka_schema.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_test.go
Runs AVRO schema validation on the client side.
> feat: validate avro schema client-side

- CHANGELOG.md
- changelog/formatter.go
- changelog/formatter_test.go
- changelog/main.go
- Formats `CHANGELOG.md` with the given line max length
- Adds new entries
> feat(changelog): add changelog parser

- docs/data-sources/mirrormaker_replication_flow.md
- docs/data-sources/service_component.md
- docs/resources/kafka_topic.md
- docs/resources/mirrormaker_replication_flow.md
- internal/sdkprovider/service/account/account_authentication.go
- internal/sdkprovider/service/account/account_team_project.go
- internal/sdkprovider/service/connectionpool/connection_pool.go
- internal/sdkprovider/service/kafka/kafka_acl.go
- internal/sdkprovider/service/kafka/mirrormaker_replication_flow.go
- internal/sdkprovider/service/kafkaschema/kafka_schema_registry_acl.go
- internal/sdkprovider/service/kafkatopic/kafka_topic.go
- internal/sdkprovider/service/mysql/mysql_user.go
- internal/sdkprovider/service/opensearch/opensearch_acl_rule.go
- internal/sdkprovider/service/organization/organization_permission.go
- internal/sdkprovider/service/servicecomponent/service_component_data_source.go
Uses code-generated enum values.
> refactor: use code-generated enums

- .github/workflows/update-schemas.yml
> fix(update-schemas): workflow

- .github/dependabot.yml
- CHANGELOG.md
- changelog/types.go
- docs/data-sources/opensearch.md
- docs/data-sources/thanos.md
- docs/resources/kafka.md
- docs/resources/kafka_connect.md
- docs/resources/opensearch.md
- docs/resources/thanos.md
- go.mod
- go.sum
- internal/sdkprovider/userconfig/service/kafka.go
- internal/sdkprovider/userconfig/service/kafka_connect.go
- internal/sdkprovider/userconfig/service/opensearch.go
- internal/sdkprovider/userconfig/service/service.go
- internal/sdkprovider/userconfig/service/thanos.go
- main.go
- Fixes changelog entries without description
- Removes elasticsearch user config exclusion
- Updates libs
- Fixes dependabot schemas update
> fix: changelog entries without description

- docs/data-sources/billing_group.md
- docs/resources/billing_group.md
- internal/sdkprovider/service/project/billing_group.go
Fixes address state description. Resolves #1920
> docs: fix address state description

- CHANGELOG.md
- internal/sdkprovider/service/kafka/kafka_native_acl.go
> chore(release): v4.30.0

- internal/sdkprovider/service/organization/organization_user_group.go
- internal/sdkprovider/service/organization/organization_user_group_data_source.go
- internal/sdkprovider/service/organization/organization_user_group_test.go
Replaced `aiven-go-client` with `avngen` in `OrganizationUserGroup` resource
> refactor(organization_user_group): replaced client-v2 with avngen

- CHANGELOG.md
- docs/resources/pg.md
- internal/schemautil/service.go
- internal/schemautil/wait.go
- internal/sdkprovider/service/pg/pg_test.go
Removes `disaster_recovery` service integration.
Not expected for LA.
> feat: remove disaster recovery integration

- internal/schemautil/helpers.go
- internal/schemautil/helpers_test.go
- internal/sdkprovider/service/organization/organizational_unit.go
- internal/sdkprovider/service/organization/organizational_unit_data_source.go
- internal/sdkprovider/service/organization/organizational_unit_test.go
- internal/sdkprovider/service/project/billing_group.go
- internal/sdkprovider/service/project/project.go
- internal/sdkprovider/service/project/util.go
Replaced `aiven-go-client` with `avngen` in OrganizationalUnit resource
> refactor(organizational_unit): replaced client-v2 with avngen

- CHANGELOG.md
- internal/sdkprovider/service/project/project.go
> fix(aiven_project): validate whether `billing_group` has changed before calling admin API

- internal/sdkprovider/service/account/account_team_member.go
- internal/sdkprovider/service/account/account_team_member_data_source.go
- internal/sdkprovider/service/account/account_team_member_test.go
- replaced `client-v2` with `avngen` in `account_team_member` resource
> refactor(account_team_member): replaced client-v2 with avngen

- internal/sdkprovider/service/account/account.go
- internal/sdkprovider/service/account/account_data_source.go
- internal/sdkprovider/service/account/account_test.go
- replaced `client-v2` with `avngen` in `account` resource
> refactor(account): replaced client-v2 with avngen

- internal/plugin/util/helpers.go
- internal/sdkprovider/service/account/account_authentication.go
- internal/sdkprovider/service/account/account_authentication_data_source.go
- replaced `client-v2` with `avngen` in `account_authentication` resource
> refactor(account_authentication): replaced client-v2 with avngen

- .github/workflows/changelog-enforcer.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/incremental-acceptance-tests.yml
- .github/workflows/lint.yml
- .github/workflows/unit-tests.yml
- Duplicated workflows in GitHub Actions have been removed
> fix(gh_actions): removed duplicated workflows in GitHub Actions

- internal/sdkprovider/service/kafka/kafka_quota.go
- internal/sdkprovider/service/kafka/kafka_quota_test.go
- added retries to kafka_quota resource
> feat(kafka_quota): added retries to kafka_quota resource

- CHANGELOG.md
- internal/schemautil/service_user.go
- internal/sdkprovider/service/cassandra/cassandra_user.go
- internal/sdkprovider/service/influxdb/influxdb_user.go
- internal/sdkprovider/service/kafka/kafka_user.go
- internal/sdkprovider/service/m3db/m3db_user.go
- internal/sdkprovider/service/mysql/mysql_user.go
- internal/sdkprovider/service/pg/pg_user.go
- internal/sdkprovider/service/pg/pg_user_data_source.go
- internal/sdkprovider/service/pg/pg_user_test.go
- internal/sdkprovider/service/redis/redis_user.go
- internal/sdkprovider/service/valkey/valkey_user.go
- Fixes `aiven_pg_user`: creating in bulk occasionally results in a 404 error
- Refactors service users: uses avngen to delete resources
> fix(pg_user): creating in bulk occasionally results in a 404 error

- CHANGELOG.md
> chore(release): v4.32.0

- docs/resources/organization_user_group_member.md
- internal/plugin/service/organization/organization_user_group_member.go
Adds details on what users can be added to groups and how they are managed within Aiven. Updates info on how to grant roles and permissions to groups with the new permission resource.
> docs: update user group member resource description

- CHANGELOG.md
> chore(release): v4.33.0

- CHANGELOG.md
- docs/resources/pg.md
- internal/schemautil/service.go
- internal/schemautil/wait.go
- internal/sdkprovider/service/pg/pg_test.go
This reverts commit fa2ce0dad304b61ac252e6e5170290334d88cf60.
> feat(crdr): enable disaster recovery integration

- docs/resources/organization_application_user_token.md
- internal/sdkprovider/service/organization/organization_application_user_token.go
Updates the description for the `max_age_seconds` and clarifies what happens when it's not set.
> docs: update description for max_age_seconds for application tokens

- internal/sdkprovider/service/organization/organization_user_group.go
- internal/sdkprovider/service/organization/organization_user_group_test.go
- fixed non-empty plan during the import
Resolves: #2036
> fix(aiven_organization_user_group): fixed resource import

- CHANGELOG.md
- internal/sdkprovider/service/serviceintegration/service_integration_test.go
- internal/sdkprovider/userconfig/diff/diff.go
Fixes `clickhouse_kafka` table removal.
> fix(service_integration): type `clickhouse_kafka` crashes

- CHANGELOG.md
> chore(release): v4.35.0

- CHANGELOG.md
> chore(release): v4.36.0

- internal/schemautil/userconfig/desc.go
Replaces the sales email address with a link to the contact form.
> docs: replace sales email address with contact form link

- CHANGELOG.md
- docs/resources/organization_application_user_token.md
- internal/sdkprovider/service/organization/organization_application_user_token.go
- internal/sdkprovider/service/organization/organization_application_user_token_test.go
- internal/sdkprovider/service/organization/organization_project_test.go
Add `aiven_organization_application_user_token` resource field `ip_allowlist`: List of allowed IP ranges.
> feat(organization_application_user_token): add ip_allowlist

- CHANGELOG.md
- internal/sdkprovider/service/organization/organization_permission.go
`PermissionsSet` sends `PUT` which can clear any artificial permissions.
> refactor: use PermissionsSet

- CHANGELOG.md
- internal/common/error.go
- internal/plugin/service/organization/organization_group_project.go
- internal/plugin/service/organization/organization_group_project_test.go
- internal/sdkprovider/service/project/project_user.go
To prevent conflicts between deprecated and new resources:
- restricted `project_user` resource modification
- restricted `organization_group_project` resource modification
> fix(project_user|organization_group_project): restricted resources modification

- docs/resources/organization_permission.md
- internal/sdkprovider/service/organization/organization_permission.go
Clarifies how to assign permissions to multiple principals on the same resource in an org.
> docs: add instructions on assigning permissions to multiple principals

- docs/guides/update-deprecated-resources.md
- templates/guides/update-deprecated-resources.md
Updates the migration instructions for `aiven_organization_permission` and adds a warning to not use it with
the resources it replaces. Changes the reference for `principal_id` to use the organization users list data source. Also fixes the indentation for some code blocks under steps.
> docs: update deprecation guide

- CHANGELOG.md
> chore(release): v4.37.0

- CHANGELOG.md
- go.mod
- internal/schemautil/userconfig/stateupgrader/typeupgrader/typeupgrader_test.go
- internal/sdkprovider/service/servicecomponent/service_component_data_source_test.go
- tools/go.mod
- upgraded `go` version to _1.24_
> chore(go): upgrade go version

- .github/workflows/acceptance-tests.yml
- scripts/retry_test.sh
- Added retries to the acceptance tests on CI to deal with flaky issues
> chore(ci): added retries to the acceptance tests on CI

- CHANGELOG.md
- docs/data-sources/organization_user_list.md
- internal/sdkprovider/provider/provider.go
- marked `aiven_organization_user_list` datasource as GA
> feat(aiven_organization_user_list): marked datasource as GA

- docs/guides/update-deprecated-resources.md
- docs/resources/organization_permission.md
- examples/get-started/README.md
- examples/get-started/get-started.tf
- examples/resources/aiven_organization_permission/resource.tf
- templates/guides/update-deprecated-resources.md
Fixes the code for the `principal_id`. Updates the get started example to use the new resource and also fixes outdated UI labels. Makes some other minor improvements to the example.
> docs: update migration guide and get started

- .semgrep.yml
- CHANGELOG.md
- internal/sdkprovider/service/clickhouse/clickhouse_grant.go
- internal/sdkprovider/service/clickhouse/clickhouse_grant_test.go
- Adds missing importer
- Removes Clickhouse plan validator to use a cheaper plan for the test
Resolves NEX-1356, #2134
> fix(clickhouse_grant): import

- docs/data-sources/service_integration.md
- docs/resources/service_integration.md
- examples/data-sources/aiven_service_integration/data-source.tf
- examples/resources/aiven_service_integration/resource.tf
- sample_project/outputs.tf
- sample_project/sample.tf
> docs: change M3DB to Thanos

- CHANGELOG.md
- docs/data-sources/organization_project.md
- docs/resources/organization_project.md
- internal/sdkprovider/service/organization/organization_project.go
- internal/sdkprovider/service/organization/organization_project_test.go
- added `base_port` field to the `aiven_organization_project` resource
> feat(aiven_organization_project): added base_port field

- examples/alloydbomni/output.tf
- examples/alloydbomni/provider.tf
- examples/alloydbomni/service.tf
- examples/alloydbomni/variables.tf
> docs: add alloydb example for getting started

- docs/index.md
- templates/index.md
> docs: update Aiven description with brand guidelines

- CHANGELOG.md
- docs/resources/organization_application_user.md
- internal/sdkprovider/service/organization/organization_application_user.go
…field
- Deprecated `is_super_admin` in the `aiven_organization_application_user` resource
> feat(aiven_organization_application_user): deprecated field

- docs/guides/disk-autoscaler.md
- docs/resources/service_integration.md
- templates/guides/disk-autoscaler.md
- templates/resources/service_integration.md.tmpl
Consolidates some info now that the autoscaler guide is published and adds a link to it from the service integrations.
> docs: refine autoscaler docs

- go.mod
- go.sum
- internal/sdkprovider/service/governance/sweep.go
- internal/sweep/sweep_test.go
- mocks/client.go
- added sweepers for `aiven_governance_access` resource
> fix(sweep): added sweepers for aiven_governance_access

- internal/plugin/service/organization/address/address.go
- internal/plugin/service/organization/address/zz_converters.go
- internal/plugin/service/organization/billinggroup/billing_group.go
- internal/plugin/service/organization/billinggroup/zz_converters.go
- internal/plugin/service/organization/billinggrouplist/zz_converters.go
- internal/plugin/service/organization/organization/organization.go
- internal/plugin/service/organization/organization/zz_converters.go
> fix: set id fields values to update generated resources

- docs/data-sources/organization_address.md
- docs/data-sources/organization_billing_group.md
- docs/data-sources/organization_billing_group_list.md
- docs/resources/organization_address.md
- docs/resources/organization_billing_group.md
- internal/plugin/service/organization/address/zz_datasource.go
- internal/plugin/service/organization/address/zz_resource.go
- internal/plugin/service/organization/billinggroup/zz_datasource.go
- internal/plugin/service/organization/billinggroup/zz_resource.go
- internal/plugin/service/organization/billinggrouplist/zz_datasource.go
Turns the timeout attribute into a block for consistency.
Resolves NEX-1452.
> refactor: generate timeout blocks

- internal/plugin/provider.go
- internal/plugin/service/organization/project/organization_group_project.go
- internal/plugin/service/organization/project/organization_group_project_test.go
- internal/plugin/service/organization/usergroup/organization_user_group_member.go
- internal/plugin/service/organization/usergroup/organization_user_group_member_test.go
Moves `project` and `usergroup` files in own packages.
> refactor: restructure the organization package

- docs/guides/creating-static-ip-addresses.md
- docs/guides/importing-resources.md
- docs/guides/manage-read-replicas.md
- docs/guides/syslog-service-integration.md
- docs/guides/upgrade-guide-v1-to-v2.md
- docs/guides/upgrade-guide-v2-to-v3.md
- docs/guides/upgrade-guide-v3-to-v4.md
- docs/guides/upgrade-guide-version_1_2_4.md
- docs/guides/use-pg-provider-for-config.md
- templates/guides/creating-static-ip-addresses.md
- templates/guides/importing-resources.md
- templates/guides/manage-read-replicas.md
- templates/guides/syslog-service-integration.md
- templates/guides/upgrade-guide-v1-to-v2.md
- templates/guides/upgrade-guide-v2-to-v3.md
- templates/guides/upgrade-guide-v3-to-v4.md
- templates/guides/upgrade-guide-version_1_2_4.md
- templates/guides/use-pg-provider-for-config.md
Consolidates content by moving guides over from Aiven Docs.
> docs: move guides to TF docs

- CHANGELOG.md
- internal/plugin/service/organization/groupproject/organization_group_project.go
> feat(organization_group_project): ignore 404 on delete

- CHANGELOG.md
> chore(release): v4.40.0

- internal/acctest/template/store_test.go
- internal/plugin/adapter/common.go
- internal/plugin/adapter/datasource.go
- internal/plugin/adapter/resource.go
- internal/plugin/provider.go
- internal/plugin/service/externalidentity/external_identity_data_source.go
- internal/plugin/service/organization/address/address.go
- internal/plugin/service/organization/address/zz_converters.go
- internal/plugin/service/organization/address/zz_datasource.go
- internal/plugin/service/organization/address/zz_resource.go
- internal/plugin/service/organization/billinggroup/billing_group.go
- internal/plugin/service/organization/billinggroup/zz_converters.go
- internal/plugin/service/organization/billinggroup/zz_datasource.go
- internal/plugin/service/organization/billinggroup/zz_resource.go
- internal/plugin/service/organization/billinggrouplist/billing_group_list.go
- internal/plugin/service/organization/billinggrouplist/zz_converters.go
- internal/plugin/service/organization/billinggrouplist/zz_datasource.go
- internal/plugin/service/organization/groupproject/organization_group_project.go
- internal/plugin/service/organization/organization/organization.go
- internal/plugin/service/organization/organization/zz_converters.go
- internal/plugin/service/organization/organization/zz_datasource.go
- internal/plugin/service/organization/organization/zz_resource.go
- internal/plugin/service/organization/project/project.go
- internal/plugin/service/organization/project/zz_converters.go
- internal/plugin/service/organization/project/zz_datasource.go
- internal/plugin/service/organization/project/zz_resource.go
- internal/plugin/service/organization/usergroupmember/organization_user_group_member.go
- Tries to improve the naming of numerous types and entities
- Removes validation rules for computed-only fields
- Adds missing resource `ConfigValidators`
- Adds base view struct
> refactor: improve naming in generated files

- Taskfile.dist.yml
- examples/mysql/output.tf
- examples/mysql/variables.tf
- examples_tests/base.go
- examples_tests/mysql_test.go
> chore(tests): fixed example tests

- CHANGELOG.md
- docs/resources/organization_permission.md
- internal/plugin/util/helpers.go
- internal/sdkprovider/service/organization/organization_permission.go
- internal/sdkprovider/service/organization/organization_permission_test.go
> feat(organization_permission): add conflict validation

- internal/plugin/service/organization/address/address_test.go
- internal/plugin/service/organization/organization/organization_test.go
Uses conventional plain text configs for tests for the plugin resources.
> refactor(tests): use plain config strings

- .github/workflows/acceptance-tests.yml
- .github/workflows/prepare-release.yml
- Taskfile.dist.yml
- This PR introduces the first part of release automation using GitHub Actions
After this is tested and working:
- Part 2: Automated tag creation and GitHub release publishing (on PR merge)
> chore(GHA): added pre-release job

- .github/workflows/acceptance-tests.yml
- .github/workflows/prepare-release.yml
- Taskfile.dist.yml
- upgrading release preparation job
> chore(GHA): improving pre-release job

- .github/workflows/acceptance-tests.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/lint.yml
- .github/workflows/prepare-release.yml
- .github/workflows/release-artifacts.yml
- .github/workflows/reusable-gatekeeper.yml
- .github/workflows/unit-tests.yml
- added some comments to the jobs
- switched the gatekeeper to reusable workflow
> ci(GHA): improving pre-release job

- .github/workflows/reusable-acceptance-tests.yml
- TaskInternal.yml
- tools/cmd/root.go
- tools/cmd/tests.go
- tools/test/matrix.go
- tools/test/matrix_test.go
- updated Acceptance tests output
> chore: updated Acceptance tests output

- internal/sdkprovider/service/clickhouse/clickhouse_database_test.go
- internal/sdkprovider/service/clickhouse/clickhouse_grant_test.go
- changed the plan for ClickHouse in acc tests
> fix(clickhouse): fixed clickhouse plan in acc tests

- docs/guides/disk-autoscaler.md
- docs/resources/service_integration.md
- templates/guides/disk-autoscaler.md
- templates/resources/service_integration.md.tmpl
- Improves autoscaler guide
- Adds "how to remove" section
> docs: improve autoscaler guide

- examples/autoscaler_integration/autoscaler.tf
- examples/autoscaler_integration/service.tf
- examples/autoscaler_integration/variables.tf
- examples/grafana/output.tf
- examples/grafana/project.tf
- examples/grafana/provider.tf
- examples/grafana/service.tf
- examples/grafana/variables.tf
Fixes variable reference in the autoscaler example and cleans up the Grafana example.
> docs(grafana): clean up grafana example and fix variable

- examples/clickhouse/clickhouse_service/README.md
> docs: add overview for simple CH grants example

- internal/sdkprovider/service/clickhouse/clickhouse_database_test.go
- internal/sdkprovider/service/clickhouse/clickhouse_grant_test.go
Resolves: NEX-1682
- fixed plan in acc tests for ClickHouse
> fix(clickhouse): fixed plan in acc tests for ClickHouse

- generators/changelog/main.go
- generators/changelog/plugin_framework.go
Resolves: NEX-1438
- added plugin framework resources to Changelog generation
> feat: added plugin framework resources to Changelog generation

- .github/workflows/slack-notify.yml
- docs/data-sources/clickhouse.md
- docs/resources/clickhouse.md
- examples/clickhouse/clickhouse_service/README.md
- examples/clickhouse/clickhouse_service/output.tf
- examples/clickhouse/clickhouse_service/service.tf
- internal/sdkprovider/service/clickhouse/clickhouse.go
Resolves: NEX-1666
- added example for HTTPS connection
- removed author from Slack notifications for scheduled jobs
> docs(clickhouse): added example for HTTPS connection

- CONTRIBUTING.md
> docs: add build-dev instructions

- TaskInternal.yml
> refactor(plugin): temporary disable the generator

- internal/schemautil/custom_diff.go
Resolves: NEX-1895
- ignore plan validation if project does not exist
> fix(service): ignore plan validation if project does not exist

- internal/acctest/acctest.go
Contributes to: NEX-1901
- added separate user-agent version to acc tests
> chore: added user agent for HTTP client in tests
